import { useEffect, useState } from 'react'
import { call, post } from './api'
import { download, Report, timeLabel } from './data'

export function StyleSources({evidence}: {evidence:any}) {
  return <div className="lab-style-columns">
    <section><h3>规则判断</h3><p className="lab-muted">相对匹配分，最高值可能固定为 1。</p>{evidence.rules.length ? evidence.rules.map((s:any)=><div key={s.path}><b>{s.raw.primary_genre || s.raw.primary_style || '规则候选'}</b>{(s.raw.genres||[]).map((g:any)=><p key={g.name}>{g.name} <span>{typeof g.confidence==='number'?g.confidence.toFixed(3):'未提供匹配分'}</span></p>)}<details><summary>规则依据 · {s.path}</summary><pre>{JSON.stringify(s.raw,null,2)}</pre></details></div>):<p>本曲未保存独立规则结果</p>}</section>
    <section><h3>舞种适配</h3><p className="lab-muted">保留原有评分尺度。</p>{evidence.dance.length ? evidence.dance.map((s:any)=><div key={s.path}>{Object.entries(s.raw).map(([k,v])=><p key={k}><b>{k}</b> {typeof v==='number'?v.toFixed(3):JSON.stringify(v)}</p>)}<details><summary>评分来源</summary><pre>{JSON.stringify(s,null,2)}</pre></details></div>):<p>本曲尚无舞种评分记录</p>}{evidence.fine_rules.map((s:any)=><details key={s.path}><summary>已有细分风格规则</summary><pre>{JSON.stringify(s,null,2)}</pre></details>)}</section>
    <section><h3>原有人工标签</h3><p className="lab-muted">原记录保留，修正在下方另存。</p>{evidence.manual.length ? evidence.manual.map((s:any)=><div key={s.path}><b>{s.labels.join(' · ')||'未提供标签名'}</b><details><summary>原始标注依据</summary><pre>{JSON.stringify(s.raw,null,2)}</pre></details></div>):<p>本曲尚无原始人工标签</p>}{evidence.metadata.map((s:any)=><details key={s.path}><summary>外部平台标签</summary><pre>{JSON.stringify(s,null,2)}</pre></details>)}</section>
  </div>
}

export default function StylePanel({report,onRun,busy,onSeek}: {report:Report;onRun:()=>Promise<void>;busy:boolean;onSeek:(t:number)=>void}) {
  const [e,setEvidence]=useState<any>(null), [error,setError]=useState(''), [notice,setNotice]=useState('')
  const [labels,setLabels]=useState(''),[note,setNote]=useState(''),[status,setStatus]=useState('confirmed'),[saving,setSaving]=useState(false)
  const [query,setQuery]=useState(''),[audit,setAudit]=useState<any>(null),[auditing,setAuditing]=useState(false)
  const [compareQuery,setCompareQuery]=useState('')
  function install(value:any){setEvidence(value);setLabels((value.review.current?.labels||[]).join('\n'));setNote(value.review.current?.note||'');setStatus(value.review.current?.status||'confirmed')}
  useEffect(()=>{let cancelled=false;call<any>(`/reports/${report.id}/styles`).then(v=>{if(!cancelled)install(v)}).catch(err=>{if(!cancelled)setError(err.message)});return()=>{cancelled=true}},[report.id])
  const model=e?.model||report.extensions.genre, data=model?.data
  const scores=[...(data?.scores||[])].sort((a:any,b:any)=>b.score-a.score).filter((x:any)=>x.label.toLowerCase().includes(query.toLowerCase()))
  async function save(){setSaving(true);setError('');try{const review=await post(`/reports/${report.id}/style-review`,{expected_revision:e.review.revision,labels:labels.split(/\n/).map(s=>s.trim()).filter(Boolean),note,status});install({...e,review});setAudit(null);setNotice('人工修正已保存，原始分析未改变')}catch(err){setError((err as Error).message)}finally{setSaving(false)}}
  async function inspect(){setAuditing(true);setError('');try{setAudit(await call('/styles/audit'))}catch(err){setError((err as Error).message)}finally{setAuditing(false)}}
  return <div className="lab-panel lab-style"><div className="lab-panel-title"><div><h2>风格判断与人工确认</h2><p className="lab-muted">不同来源并列保留，模型候选暂不参与自动选歌。</p></div><button disabled={busy} onClick={onRun}>仅分析风格</button></div>
    {error&&<p className="lab-alert" role="alert">{error}</p>}{notice&&<p className="lab-notice" role="status">{notice}</p>}
    <section className="lab-style-model"><h3>模型风格候选 · Discogs400</h3><p className="lab-muted">原始分数 0–1，未经准确率校准。大类取最高子类分数；各类无需加总为 1。</p>
      {model?.status==='ready'&&data ? <><div className="lab-style-parents">{data.parents?.slice(0,4).map((x:any)=><span key={x.label}>{x.label} <b>{x.score.toFixed(3)}</b></span>)}</div><ol className="lab-style-top">{data.top?.map((x:any)=><li key={x.label}><span>{x.parent}<strong>{x.style}</strong></span><b>{x.score.toFixed(3)}</b><meter min={0} max={1} value={x.score}/></li>)}</ol><details><summary>全部 {data.scores?.length} 个细分类别与原始分数</summary><input className="lab-search" aria-label="筛选模型风格" placeholder="搜索 House、Boom Bap…" value={query} onChange={ev=>setQuery(ev.target.value)}/><button onClick={()=>download('discogs400-raw.json',JSON.stringify(model,null,2))}>导出全部模型结果</button><div className="lab-style-scroll"><table><thead><tr><th>大类 / 细分风格</th><th>原始分数</th></tr></thead><tbody>{scores.map((x:any)=><tr key={x.label}><td>{x.label.replace('---',' / ')}</td><td>{x.score.toFixed(6)}</td></tr>)}</tbody></table></div></details><details><summary>分段候选 · 每 30 秒</summary><p className="lab-muted">窗口独立推理；整曲结果按实际特征帧数汇总。</p><div className="lab-style-scroll"><table><thead><tr><th>时间</th><th>前几个候选及分数</th></tr></thead><tbody>{data.segments?.map((s:any)=><tr key={s.start}><td><button onClick={()=>onSeek(s.start)}>{timeLabel(s.start)}–{timeLabel(s.end)}</button></td><td>{s.top.map((x:any)=>`${x.style} ${x.score.toFixed(3)}`).join(' · ')}</td></tr>)}</tbody></table></div></details><details><summary>模型版本、文件指纹与缓存</summary><pre>{JSON.stringify({model_files:data.model_files,backend:data.backend,aggregation:data.aggregation,embedding_cache:data.embedding_cache,license:data.license},null,2)}</pre></details></>:<p className="lab-notice">{model?.reason||({not_run:'本曲尚未运行模型',unavailable:'模型运行条件未满足',failed:'模型计算失败'} as any)[model?.status]||'本曲尚未运行模型'}。可点击“仅分析风格”，其余分析结果会保留。</p>}
    </section>
    {e ? <><StyleSources evidence={e}/><section className="lab-style-review"><h3>人工确认 / 修正</h3><p>当前确认：{e.review.current ? `${e.review.current.labels.join(' · ')||'待填写'}（${e.review.current.status==='confirmed'?'已确认':'待复核'}，版本 ${e.review.revision}）`:'尚未新增确认'}</p><label>人工风格标签<textarea aria-label="人工风格标签" value={labels} placeholder="例如 Hip Hop---Boom Bap；每行一个标签，标签内的逗号会保留" onChange={ev=>setLabels(ev.target.value)}/></label><label>判断备注<textarea aria-label="判断备注" maxLength={1000} value={note} onChange={ev=>setNote(ev.target.value)}/></label><label>确认状态<select aria-label="确认状态" value={status} onChange={ev=>setStatus(ev.target.value)}><option value="confirmed">已试听确认</option><option value="needs_review">待复核</option></select></label><div className="lab-actions"><button className="primary" disabled={saving||(!labels.trim()&&status==='confirmed')} onClick={save}>{saving?'正在保存':'保存人工修正'}</button><button onClick={()=>call(`/reports/${report.id}/styles`).then(install).catch(err=>setError(err.message))}>重新载入标注</button><button onClick={()=>download('style-evidence-and-reviews.json',JSON.stringify(e,null,2))}>导出全部风格依据与标注</button></div><details><summary>修正记录 · {e.review.history.length} 次</summary><pre>{JSON.stringify(e.review.history,null,2)}</pre></details></section></>:<p role="status">正在读取规则与人工依据…</p>}
    <section className="lab-style-audit"><h3>曲库覆盖与对照</h3><p className="lab-muted">优先核对正式曲库，按曲目取最新报告，再按音频去重。已有人工标签用于初步核对；舞种名称不强行映射成音乐风格。</p><button disabled={auditing} onClick={inspect}>{auditing?'正在核对曲库…':'更新覆盖与对照'}</button>{audit&&<><div className="lab-style-parents">{Object.entries({曲目:audit.coverage.tracks,规则:audit.coverage.rules,原有人工:audit.coverage.manual,舞种评分:audit.coverage.dance,细分规则:audit.coverage.fine_rules,模型已完成:audit.coverage.model_ready,新增人工确认:audit.coverage.reviewed}).map(([k,v])=><span key={k}>{k} <b>{String(v)}</b></span>)}</div><p>可映射人工标签的对照曲目：{audit.comparison.eligible} 首；首选一致 {audit.comparison.top1_agreements} 首，前五候选一致 {audit.comparison.top5_agreements} 首。</p><p className="lab-muted">{audit.comparison.definition}</p><input className="lab-search" aria-label="搜索风格对照" placeholder="搜索曲名、标签或模型候选" value={compareQuery} onChange={ev=>setCompareQuery(ev.target.value)}/><div className="lab-style-scroll"><table><thead><tr><th>曲目</th><th>人工标签</th><th>规则候选</th><th>模型前五候选</th><th>核对</th></tr></thead><tbody>{audit.rows.filter((r:any)=>JSON.stringify(r).toLowerCase().includes(compareQuery.toLowerCase())).map((r:any)=><tr key={r.report_id}><td>{r.title}</td><td>{r.human.join(' · ')||'未标注'}</td><td>{r.rules.join(' · ')||'无独立记录'}</td><td>{r.model_top.join(' · ')||'尚无结果'}</td><td>{r.uncovered_labels.length?`未覆盖：${r.uncovered_labels.join(' · ')}`:r.top5_agrees===null?'暂不可比较':r.top5_agrees?'前五一致':'待复核'}</td></tr>)}</tbody></table></div><details><summary>部署与标签映射依据</summary><pre>{JSON.stringify({deployment:audit.deployment,mapping:audit.comparison.mapping,matching:audit.comparison.matching},null,2)}</pre></details><button onClick={()=>download('style-library-comparison.json',JSON.stringify(audit,null,2))}>导出曲库对照</button></>}</section>
  </div>
}
