import {useEffect,useRef,useState} from 'react'
import {guardPlan,type GuardCatalog} from './planner'
import {LiveTransport} from '../realtime/transport'
import DecisionHistory from '../realtime/DecisionHistory'
import logo from '../analysis/assets/harbeat-logo.png'
import '../realtime/realtime.css'
import './guarded.css'
const base=new URL('.',location.href)
export default function AutoLab(){
 const [catalog,setCatalog]=useState<GuardCatalog|null>(null),[aId,setA]=useState(''),[bId,setB]=useState(''),[error,setError]=useState(''),[,refresh]=useState(0),player=useRef<LiveTransport|null>(null),runToken=useRef(0)
 useEffect(()=>{let alive=true;fetch(new URL('auto-catalog.json',base)).then(async r=>{if(!r.ok)throw Error('自动保护目录加载失败');const c=await r.json() as GuardCatalog;if(alive){setCatalog(c);setA(c.tracks.find(t=>t.title==='Cold')!.id);setB(c.tracks.find(t=>t.title==='Crazy Love')!.id)}}).catch(e=>setError(String(e)));return()=>{alive=false;runToken.current++;player.current?.dispose()}},[])
 if(!catalog)return <main className="guard"><h1>自动保护混音</h1><p>{error||'正在读取声学检查结果…'}</p></main>
 const a=catalog.tracks.find(t=>t.id===aId)!,b=catalog.tracks.find(t=>t.id===bId)!,p=player.current,locked=!!p?.busy||!!p?.active
 const search=guardPlan(catalog,{},a,catalog.tracks,0,{kind:'next',targetId:bId},new Set(),a.duration,false),plan=search.best
 const pairs=catalog.tracks.flatMap(x=>catalog.tracks.filter(y=>y.id!==x.id).flatMap(y=>{const r=guardPlan(catalog,{},x,catalog.tracks,0,{kind:'next',targetId:y.id},new Set(),x.duration,false);return r.best?[{a:x,b:y,plan:r.best}]:[]}))
 async function ensure(){if(player.current)return player.current;const t=new LiveTransport(catalog!.tracks,()=>refresh(n=>n+1),base,{planner:(a,tracks,pos,intent,ready,budget=18,requireReady=true)=>guardPlan(catalog!,{},a,tracks,pos,intent,ready,budget,requireReady),autoNext:false,prewarm:false,noPlanMessage:'当前没有通过声学保护的可执行转场，A 继续播放；详见排除原因。',policyVersion:'protected-auto-v1'});player.current=t;try{await t.initialize();t.log('automatic_catalog',{schema:'harbeat.protected.auto.v1',evidence:catalog!.evidence,humanReviewsGenerated:false});return t}catch(e){t.dispose();player.current=null;throw e}}
 async function run(fn:()=>Promise<void>){setError('');try{await fn()}catch(e){setError((e as Error).message)}}
 async function mix(near:boolean){if(!plan)return;const token=++runToken.current;const t=await ensure();if(token!==runToken.current)return;t.busy=true;try{t.cache.protected=new Set([a.native.url,b.native.url,plan.asset.url]);t.log('automatic_preload',{from:a.id,to:b.id,planId:plan.id,assets:[a.native,b.native,plan.asset]});for(const asset of [a.native,b.native,plan.asset]){await t.cache.load(asset);if(token!==runToken.current)return}}finally{t.busy=false;refresh(n=>n+1)}if(token!==runToken.current)return;const offset=near?Math.max(0,plan.start-5):0;await t.start(a.id,offset);if(token!==runToken.current||!t.active)return;await t.request({kind:'next',targetId:b.id},a.duration-t.position);}
 return <main className="guard"><header><img src={logo} alt="HarBeat"/><div><h1>自动保护混音 · 直接试听</h1><p>先找到可执行的保护窗口，再自动完成接歌。无需逐项勾选确认。</p></div></header><nav><a href="manual.html">人工核验对照模式</a><a href="../v3-live-baseline-20260922/index.html">保留的 V3 实时版</a><a href="/analysis-lab">分析平台</a></nav>
 <aside>这是自动声学候选版：检查段尾附近的人声低活动间隙、原曲无人声入口和拍点映射。它可以实际混音，但尚不能证明歌词语义句末或段落标签完全正确。能量与风格不参与本次选点。</aside>
 <section><h2>1 · 选择自动转场</h2><label>已找到可执行窗口的曲对（{pairs.length} 组）<select disabled={locked} value={pairs.some(x=>x.a.id===aId&&x.b.id===bId)?`${aId}|${bId}`:''} onChange={e=>{const [x,y]=e.target.value.split('|');setA(x);setB(y)}}><option value="" disabled>查看下方未通过原因</option>{pairs.map(x=><option value={`${x.a.id}|${x.b.id}`} key={`${x.a.id}|${x.b.id}`}>{x.a.title} → {x.b.title} · A {x.plan.end.toFixed(2)} 秒交接</option>)}</select></label><div className="fields"><label>A 当前歌曲<select value={aId} disabled={locked} onChange={e=>{setA(e.target.value);if(e.target.value===bId)setB(catalog.tracks.find(t=>t.id!==e.target.value)!.id)}}>{catalog.tracks.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label>B 下一首<select value={bId} disabled={locked} onChange={e=>setB(e.target.value)}>{catalog.tracks.filter(t=>t.id!==aId).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label></div>
 {plan?<><h3>{a.title} → {b.title}</h3><ol><li>A 播放到 {plan.start.toFixed(3)} 秒时，B 无人声片段开始铺入。</li><li>A 在 {plan.end.toFixed(3)} 秒的人声间隙退出；模型段尾是 {(plan as any).protection.exit.sectionEnd.toFixed(3)} 秒。</li><li>B 从原曲 {plan.window.end.toFixed(3)} 秒接管，之后按原速播放。进入窗口为 {plan.window.start.toFixed(3)}–{plan.window.end.toFixed(3)} 秒，同属 {plan.window.role} 段。</li></ol><div className="actions"><button disabled={locked} onClick={()=>run(()=>mix(true))}>自动混音试听（从转场前开始）</button><button disabled={locked} onClick={()=>run(()=>mix(false))}>从 A 开头播放并自动接歌</button></div><p>两种方式都由浏览器实时执行 EQ 与渐变，先准备 A、B 和变速进入片段，再启动播放。第一种从混入前 5 秒开始，方便比较多个曲对。</p></>:<><p>这个曲对目前没有合格的自动窗口。可以选择上方已有窗口的曲对直接试听，或只播放 A。</p><ul>{search.exclusions.map((x,i)=><li key={i}>{x.track}：{x.reason}</li>)}</ul></>}
 <div className="actions"><button disabled={locked} onClick={()=>run(async()=>{const t=await ensure();await t.start(a.id)})}>只播放 A</button><button disabled={!p?.playing||p.busy||!!p.pending} onClick={()=>run(async()=>{await p!.request({kind:'next',targetId:b.id},p!.current!.duration-p!.position)})}>按当前位置请求保护接歌</button><button disabled={!p?.active&&!p?.busy} onClick={()=>{runToken.current++;p?.stop()}}>停止</button><button disabled={!p} onClick={()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(p!.export(),null,2)],{type:'application/json'}));const x=document.createElement('a');x.href=u;x.download='HarBeat-auto-protected-session.json';x.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}}>导出完整日志</button></div><p role="status">{p?.status||'选择曲对后，点击自动混音试听'} · {p?.current?.title||a.title} {p?.position.toFixed(2)||'0.00'} 秒</p>{error&&<p role="alert">{error}</p>}{p?.pending&&<p>正在执行：A 退出时间 {p.pending.plan.end.toFixed(3)} 秒，接管歌曲 {catalog.tracks.find(t=>t.id===p.pending!.plan.to)?.title}。</p>}</section>
 <section><h2>2 · 放行与排除依据</h2><p>自动模式没有生成人工确认。A 必须经过模型段尾，并在其后最多两小节、最长 4 秒内找到人声低活动间隙；B 全部进入窗口需同时通过原有人声区间和分离人声能量检查。找不到就继续 A，不因 18 秒等待目标放宽。</p><p>前奏拍网格仍为候选；本轮使用原曲中的无人声入口，沿用 V3 EQ 与渐变。部分歌曲尚无可用入口或段尾，所以并非六首任意组合都能放行。当前素材为原演示裁切版，最长 150 秒。</p><details><summary>试听前完整计划、数值、音频来源和文件指纹</summary><pre>{JSON.stringify({plan,evidence:{a:catalog.evidence[a.id],b:catalog.evidence[b.id]},sources:{a:a.provenance,b:b.provenance},exclusions:search.exclusions},null,2)}</pre></details>{p?.lastPlan&&<details><summary>实际执行的计划（与点击时位置重新核对）</summary><pre>{JSON.stringify(p.lastPlan,null,2)}</pre></details>}</section>{p&&<DecisionHistory logs={p.logs} tracks={catalog.tracks} eventCount={p.logs.length}/>}</main>
}
