import {useEffect,useRef,useState} from 'react'
import {guardPlan,type GuardCatalog,type Reviews} from './planner'
import {LiveTransport} from '../realtime/transport'
import DecisionHistory from '../realtime/DecisionHistory'
import '../realtime/realtime.css'
import './guarded.css'
import logo from '../analysis/assets/harbeat-logo.png'
const base=new URL('.',location.href)
function download(data:unknown){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='HarBeat-protected-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function Preview({url,start,end,marker,label,disabled,onDone}:{url:string;start:number;end:number;marker?:number;label:string;disabled:boolean;onDone:()=>void}){
 const ref=useRef<HTMLAudioElement>(null),last=useRef(start),heard=useRef(0);const [done,setDone]=useState(false),[error,setError]=useState(''),[position,setPosition]=useState(start)
 return <div className="preview"><p>{label} · {start.toFixed(3)}–{end.toFixed(3)} 秒{marker!==undefined?`；核验点 ${marker.toFixed(3)} 秒`:''}</p><audio ref={ref} preload="none" src={new URL(url,base).href} onError={()=>setError('素材加载失败，请重试')} onTimeUpdate={()=>{const a=ref.current!;setPosition(a.currentTime);const delta=a.currentTime-last.current;if(delta>0&&delta<1&&a.playbackRate===1)heard.current+=delta;last.current=a.currentTime;if(a.currentTime>=end-.05){a.pause();if(heard.current>=end-start-.4){setDone(true);onDone()}}}} onEnded={()=>{if(heard.current>=end-start-.4){setDone(true);onDone()}}}/><button disabled={disabled} onClick={async()=>{const a=ref.current!;document.querySelectorAll('audio').forEach(other=>other.pause());a.currentTime=start;last.current=start;heard.current=0;setError('');try{await a.play()}catch(e){setError(String(e))}}}>试听此片段</button> <button onClick={()=>ref.current?.pause()}>暂停试听</button> <span>播放位置 {position.toFixed(2)} 秒 · {marker!==undefined?(position<marker?"核验点之前":"核验点之后")+" · ":""}{done?'已完整播放，请根据听感决定是否确认':'尚未完整试听'}</span>{error&&<p role="alert">{error}</p>}</div>
}
export default function GuardedLab(){
 const [catalog,setCatalog]=useState<GuardCatalog|null>(null),[catalogHash,setHash]=useState(''),[reviews,setReviews]=useState<Reviews>({}),reviewsRef=useRef<Reviews>({}),player=useRef<LiveTransport|null>(null),[,render]=useState(0),[error,setError]=useState(''),[aId,setA]=useState(''),[bId,setB]=useState(''),[exitId,setExit]=useState(''),[windowId,setWindow]=useState(''),[offset,setOffset]=useState(0),[heard,setHeard]=useState<Record<string,boolean>>({})
 useEffect(()=>{let alive=true;fetch(new URL('guard-catalog.json',base)).then(async r=>{if(!r.ok)throw Error('分析目录加载失败');const bytes=await r.arrayBuffer(),h=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');const c=JSON.parse(new TextDecoder().decode(bytes)) as GuardCatalog;if(!alive)return;setCatalog(c);setHash(h);setA(c.tracks[1].id);setB(c.tracks[2].id);try{const saved=JSON.parse(localStorage.getItem('guard-reviews:'+h)||'{}');setReviews(saved);reviewsRef.current=saved}catch{} }).catch(e=>setError(String(e)));return()=>{alive=false;player.current?.dispose()}},[])
 if(!catalog)return <main className="guard"><h1>HarBeat · 保护模式</h1><p>{error||'正在读取素材与边界证据…'}</p></main>
 const a=catalog.tracks.find(t=>t.id===aId)!,b=catalog.tracks.find(t=>t.id===bId)!,exits=catalog.evidence[a.id].exits,exit=exits.find(x=>x.id===exitId)||exits[0],windows=b.windows.filter(w=>w.variants[a.id]),w=windows.find(x=>x.id===windowId)||windows[0],asset=w?.variants[a.id],ev=w&&catalog.evidence[b.id].windows[w.id],p=player.current,locked=!!p?.active||!!p?.busy
 const ak=exit?`${a.id}:${exit.id}`:'',bk=w?`${b.id}:${w.id}:${a.id}`:'',reviewKey=`${ak}:${bk}`,ar=reviews.exits?.[ak],br=reviews.entries?.[bk]
 function save(next:Reviews){setReviews(next);reviewsRef.current=next;try{localStorage.setItem('guard-reviews:'+catalogHash,JSON.stringify(next))}catch{setError('确认未能写入浏览器，请导出留存')}player.current?.log('guard_review',{catalogHash,reviews:next});}
 async function ensure(){if(player.current)return player.current;const created=new LiveTransport(catalog!.tracks,()=>render(x=>x+1),base,{planner:(a,tracks,position,intent,ready,budget=18,requireReady=true)=>guardPlan(catalog!,reviewsRef.current,a,tracks,position,intent,ready,budget,requireReady),autoNext:false,prewarm:false,noPlanMessage:'保护条件未满足，当前歌曲继续播放。请查看待确认项和排除原因。',policyVersion:'protected-v1'});player.current=created;try{await created.initialize();created.log('guard_catalog',{catalogHash,reviews:reviewsRef.current});return created}catch(e){created.dispose();player.current=null;throw e}}
 async function run(fn:()=>Promise<unknown>){setError('');try{await fn()}catch(e){setError(String(e))}}
 const preview=guardPlan(catalog,reviews,a,catalog.tracks,offset,{kind:'next',targetId:b.id},new Set(),a.duration-offset,false)
 return <main className="guard"><header><img src={logo} alt="HarBeat"/><div><h1>实时混音 · 乐段与人声保护</h1><p>先核验完整退出点，再铺入 B 伴奏。A 退出之后，B 原曲正文接管。</p></div></header><nav><a href="../v3-live-baseline-20260922/index.html">返回保留的 V3 实时版</a><a href="../v3-quality-multi-20260923/index.html">多曲对照实验</a><a href="/analysis-lab">分析平台</a></nav>
 <aside>这里的边界和前奏拍点仍是候选。初次打开没有人工确认记录，因此会阻止接歌。试听确认仅保存在当前浏览器；素材版本变化会失效。伴奏由鼓、贝斯、其他分轨组成，仍需检查分轨残留人声。本轮关闭能量与风格目标，保留 V3 的 EQ 和渐变。</aside>
 <section><h2>1 · 选择与核验</h2><div className="fields"><label>A 当前歌曲<select disabled={locked} value={aId} onChange={e=>{setA(e.target.value);setExit('');if(e.target.value===bId)setB(catalog.tracks.find(t=>t.id!==e.target.value)!.id)}}>{catalog.tracks.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><label>B 下一首<select disabled={locked} value={bId} onChange={e=>{setB(e.target.value);setWindow('')}}>{catalog.tracks.filter(t=>t.id!==aId).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label></div>
 <p>核验时请先停止主播放器，避免试听声音互相干扰。两首歌的原始分轨、报告和文件指纹可在下方展开。</p>
 {exit?<><label>A 退出候选<select disabled={locked} value={exit.id} onChange={e=>setExit(e.target.value)}>{exits.map(x=><option key={x.id} value={x.id}>{x.label} · {x.start.toFixed(2)}–{x.sectionEnd.toFixed(2)} 秒 → 退出 {x.cut.toFixed(3)} 秒</option>)}</select></label><Preview key={ak} url={a.native.url} start={Math.max(0,exit.cut-8)} end={Math.min(a.duration,exit.cut+3)} marker={exit.cut} label="A 段尾原曲：确认人声尾音已结束、乐段已完整" disabled={locked} onDone={()=>setHeard(v=>({...v,[ak]:true}))}/><button disabled={locked||!heard[ak]} onClick={()=>save({...reviews,exits:{...reviews.exits,[ak]:{masterSha256:String(a.provenance!.masterSha256),cut:exit.cut,confirmedAt:new Date().toISOString(),phraseEnded:true}}})}>{ar?'已人工确认 · 可再次确认':'我已试听：此点乐段完整、人声尾音没有被截断'}</button></>:<p>此曲没有可用的段尾候选，不能作为保护模式的出歌曲。</p>}
 {w&&asset?<><label>B 进入候选<select disabled={locked} value={w.id} onChange={e=>setWindow(e.target.value)}>{windows.map(x=><option key={x.id} value={x.id}>{x.role} · {x.start.toFixed(3)}–{x.end.toFixed(3)} 秒 · {x.bars} 小节伴奏</option>)}</select></label><p>窗口所属段落 {ev.sectionStart.toFixed(3)}–{ev.sectionEnd.toFixed(3)} 秒；拍网格：{ev.gridSource==='intro_phase_candidate'?'根据拍点延伸的前奏候选，需要试听核验':'已有拍网格候选'}。伴奏变速 {asset.rate.toFixed(4)} 倍；交接后正文恢复原速。</p><Preview key={bk} url={asset.url} start={0} end={asset.duration} label="B 实际进入伴奏：确认无明显人声残留、节拍可用" disabled={locked} onDone={()=>setHeard(v=>({...v,[bk]:true}))}/><Preview key={bk+':body'} url={b.native.url} start={Math.max(0,w.end-2)} end={Math.min(b.duration,w.end+8)} marker={w.end} label="B 原曲正文：从核验点接管，不能从人声半句开始" disabled={locked} onDone={()=>setHeard(v=>({...v,[bk+':body']:true}))}/><button disabled={locked||!heard[bk]||!heard[bk+':body']} onClick={()=>save({...reviews,entries:{...reviews.entries,[bk]:{assetSha256:asset.sha256,bodySha256:b.native.sha256,confirmedAt:new Date().toISOString(),noVocalEntry:true,bodyStartsClean:true}}})}>{br?'已人工确认 · 可再次确认':'我已试听：伴奏无人声冲突、正文完整起句、拍点可用'}</button></>:<p>当前曲对没有满足变速范围的进入素材，请更换曲目。</p>}
 <p>检测区间不等于歌词乐句。人工确认是在以上精确切点核验；若与检测器不一致，日志同时保留两者，不改写原分析。</p><button disabled={locked} onClick={()=>{save({});setHeard({})}}>撤销全部确认</button></section>
 <section><h2>2 · 试听前计划与实时播放</h2><label>A 开始播放位置（秒）<input disabled={locked} type="number" min="0" max={a.duration-1} value={offset} onChange={e=>setOffset(Math.max(0,Math.min(a.duration-1,Number(e.target.value)||0)))}/></label><p>搜索到当前素材末尾，不受 18 秒强制交接。只使用已核验的窗口；确认多个窗口后选最早可执行的组合。</p>{preview.best?<p>候选计划：A {preview.best.start.toFixed(3)} 秒开始铺入 B 伴奏；A {preview.best.end.toFixed(3)} 秒完全退出，同时从 B {preview.best.window.end.toFixed(3)} 秒接管。实际点击时重新检查素材与时间。</p>:<ul>{preview.exclusions.map((x,i)=><li key={i}>{x.track}：{x.reason}</li>)}</ul>}
 <div className="actions"><button disabled={locked||!asset} onClick={()=>run(async()=>{const t=await ensure();t.busy=true;try{t.cache.protected=new Set([a.native.url,b.native.url,asset!.url]);for(const item of [a.native,b.native,asset!])await t.cache.load(item);t.status="所选素材已准备，可以播放 A"}finally{t.busy=false;render(x=>x+1)}})}>提前准备所选素材</button><button disabled={locked} onClick={()=>run(async()=>{document.querySelectorAll('audio').forEach(x=>x.pause());const t=await ensure();await t.start(a.id,offset)})}>播放 A</button><button disabled={!p?.playing||p.busy||!!p.pending} onClick={()=>run(async()=>{await p!.request({kind:'next',targetId:b.id},Math.max(0,p!.current!.duration-p!.position))})}>请求保护接歌 → {b.title}</button><button disabled={!p?.active} onClick={()=>p?.stop()}>停止</button><button disabled={!p} onClick={()=>download({...p!.export(),guard:{catalogHash,reviews}})}>导出完整日志</button></div><p role="status">{p?.status||'尚未播放'} · {p?.current?.title||a.title} {p?.position.toFixed(2)||'0.00'} 秒</p>{error&&<p role="alert">{error}</p>}{p?.lastSearch&&!p.lastSearch.best&&<ul>{p.lastSearch.exclusions.map((x:any,i:number)=><li key={i}>{x.track}：{x.reason}</li>)}</ul>}{p?.lastPlan&&<details><summary>实际采用的保护证据与计划</summary><pre>{JSON.stringify(p.lastPlan,null,2)}</pre></details>}</section>
 <details><summary>完整素材来源、段落、拍网格、人声区间与确认记录</summary><pre>{JSON.stringify({catalogHash,a,b,evidence:{a:catalog.evidence[a.id],b:catalog.evidence[b.id]},reviews,reviewKey},null,2)}</pre></details>{p&&<DecisionHistory logs={p.logs} tracks={catalog.tracks} eventCount={p.logs.length}/>}</main>
}
