"""ChromaDB vector store with CLAP cross-modal embeddings.

- Audio embeddings: generated by _run_clap_audio.py subprocess during
  background analysis (Phase 3).  Produces a 512-d vector from the actual
  audio waveform.
- Text embeddings: generated by _run_clap_text.py subprocess at query time.
  Produces a 512-d vector from natural-language vibe description.

Both live in the same vector space so cosine similarity measures how well
a text description matches the *sound* of a song — not just its metadata.

Subprocess isolation keeps the ~1.5 GB CLAP model out of the uvicorn
worker's resident memory.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
from typing import List, Optional

import chromadb
from chromadb.utils.embedding_functions import DefaultEmbeddingFunction

logger = logging.getLogger(__name__)

CHROMA_PATH = os.environ.get("CHROMA_PATH", "./data/chroma_db")
COLLECTION_CLAP = "harbeat_clap"           # CLAP audio embeddings
COLLECTION_TEXT = "harbeat_songs"          # fallback text embeddings (old)

_CLAP_AUDIO_SCRIPT = os.path.join(os.path.dirname(__file__), "_run_clap_audio.py")
_CLAP_TEXT_SCRIPT = os.path.join(os.path.dirname(__file__), "_run_clap_text.py")

# CLAP embedding dimension
CLAP_DIM = 512


def _get_client() -> chromadb.ClientAPI:
    os.makedirs(CHROMA_PATH, exist_ok=True)
    return chromadb.PersistentClient(path=CHROMA_PATH)


def get_clap_collection():
    """Get the CLAP collection (no default embedding function — we supply vectors)."""
    client = _get_client()
    return client.get_or_create_collection(
        name=COLLECTION_CLAP,
        metadata={"hnsw:space": "cosine"},
    )


def get_text_collection():
    """Get the text-based fallback collection (uses ChromaDB default embeddings)."""
    client = _get_client()
    return client.get_or_create_collection(name=COLLECTION_TEXT)


# ── Subprocess helpers ──────────────────────────────────────────────

def _run_clap_audio_subprocess(audio_path: str) -> List[float]:
    """Run CLAP audio embedding in a child process. Returns 512-d vector."""
    result = subprocess.run(
        [sys.executable, _CLAP_AUDIO_SCRIPT, audio_path],
        capture_output=True, text=True, timeout=300,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()[-500:]
        raise RuntimeError(f"CLAP audio subprocess exit={result.returncode} stderr={stderr}")
    return json.loads(result.stdout)


def _run_clap_text_subprocess(query: str) -> List[float]:
    """Run CLAP text embedding in a child process. Returns 512-d vector."""
    result = subprocess.run(
        [sys.executable, _CLAP_TEXT_SCRIPT, query],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()[-500:]
        raise RuntimeError(f"CLAP text subprocess exit={result.returncode} stderr={stderr}")
    return json.loads(result.stdout)


# ── Build metadata text (for display & fallback) ────────────────────

def _build_document(title: str, artist: str, style: Optional[str] = None,
                    energy: Optional[str] = None, groove: Optional[str] = None,
                    bpm: Optional[float] = None) -> str:
    parts = [f"{title} by {artist}"]
    if style:
        parts.append(f"style: {style}")
    if energy:
        parts.append(f"energy: {energy}")
    if groove:
        parts.append(f"groove: {groove}")
    if bpm:
        parts.append(f"bpm: {int(bpm)}")
    return ", ".join(parts)


# ── Index a single song with CLAP audio embedding ───────────────────

def index_song_clap(song_id: str, audio_path: str, title: str, artist: str,
                    style: Optional[str] = None, energy: Optional[str] = None,
                    groove: Optional[str] = None, bpm: Optional[float] = None) -> bool:
    """Generate CLAP audio embedding and store in ChromaDB.

    Returns True on success, False on failure.
    """
    try:
        embedding = _run_clap_audio_subprocess(audio_path)
    except Exception:
        logger.exception("[clap] failed to generate audio embedding for %s", song_id)
        return False

    collection = get_clap_collection()
    doc = _build_document(title, artist, style, energy, groove, bpm)
    metadata = {"song_id": str(song_id), "title": title, "artist": artist}
    if style:
        metadata["style"] = style
    if energy:
        metadata["energy"] = energy
    if groove:
        metadata["groove"] = groove
    if bpm is not None:
        metadata["bpm"] = float(bpm)

    collection.upsert(
        ids=[str(song_id)],
        embeddings=[embedding],
        documents=[doc],
        metadatas=[metadata],
    )
    logger.info("[clap] indexed song %s with CLAP audio embedding", song_id)
    return True


# ── Index song with text-only fallback (no audio file needed) ────────

def index_song(song_id: str, title: str, artist: str,
               style: Optional[str] = None, energy: Optional[str] = None,
               groove: Optional[str] = None, bpm: Optional[float] = None,
               collection_name: str = COLLECTION_TEXT) -> None:
    """Add song to text-based fallback collection."""
    collection = get_text_collection()
    doc = _build_document(title, artist, style, energy, groove, bpm)
    metadata = {"song_id": str(song_id), "title": title, "artist": artist}
    if style:
        metadata["style"] = style
    if energy:
        metadata["energy"] = energy
    if groove:
        metadata["groove"] = groove
    if bpm is not None:
        metadata["bpm"] = float(bpm)

    collection.upsert(
        ids=[str(song_id)],
        documents=[doc],
        metadatas=[metadata],
    )


# ── Search: prefer CLAP, fallback to text ────────────────────────────

def search_songs(query: str, top_k: int = 12) -> List[dict]:
    """Semantic search using CLAP text→audio cross-modal matching.

    Generates a CLAP text embedding for the query, then finds the closest
    audio embeddings in the CLAP collection.  Falls back to text-based
    search if the CLAP collection is empty or the subprocess fails.
    """
    # Try CLAP cross-modal search first
    clap_col = get_clap_collection()
    if clap_col.count() > 0:
        try:
            query_embedding = _run_clap_text_subprocess(query)
            results = clap_col.query(
                query_embeddings=[query_embedding],
                n_results=min(top_k, clap_col.count()),
                include=["metadatas", "distances", "documents"],
            )
            rows = _parse_results(results)
            if rows:
                logger.info("[clap] search returned %d results (CLAP cross-modal)", len(rows))
                return rows
        except Exception:
            logger.warning("[clap] CLAP text subprocess failed, falling back to text search", exc_info=True)

    # Fallback: text-based search
    text_col = get_text_collection()
    if text_col.count() == 0:
        return []

    results = text_col.query(
        query_texts=[query],
        n_results=min(top_k, text_col.count()),
        include=["metadatas", "distances", "documents"],
    )
    return _parse_results(results)


def _parse_results(results: dict) -> List[dict]:
    metadatas = results.get("metadatas", [[]])[0] or []
    distances = results.get("distances", [[]])[0] or []
    documents = results.get("documents", [[]])[0] or []
    rows = []
    for meta, dist, doc in zip(metadatas, distances, documents):
        item = dict(meta or {})
        item["distance"] = float(dist)
        item["document"] = doc
        rows.append(item)
    return rows


# ── Batch reindex ────────────────────────────────────────────────────

def index_all_songs_from_db() -> int:
    """Index all songs into the text-based collection.

    For CLAP audio embeddings, use the /reindex-clap endpoint or let
    the background analysis pipeline handle them one by one.
    """
    from app.shared.database import SessionLocal
    from app.modules.playlists.models import Song, SongTag

    db = SessionLocal()
    try:
        rows = db.query(Song, SongTag).outerjoin(SongTag, SongTag.song_id == Song.id).all()
        collection = get_text_collection()
        ids, docs, metas = [], [], []
        for song, tags in rows:
            sid = str(song.id)
            style = tags.style if tags else None
            energy = tags.energy if tags else None
            groove = tags.groove_tag if tags else None
            bpm_val = float(tags.bpm) if tags and tags.bpm else None

            doc = _build_document(song.title, song.artist, style, energy, groove, bpm_val)
            meta = {"song_id": sid, "title": song.title, "artist": song.artist}
            if style:
                meta["style"] = style
            if energy:
                meta["energy"] = energy
            if groove:
                meta["groove"] = groove
            if bpm_val is not None:
                meta["bpm"] = bpm_val

            ids.append(sid)
            docs.append(doc)
            metas.append(meta)

        if ids:
            for i in range(0, len(ids), 500):
                collection.upsert(
                    ids=ids[i:i+500],
                    documents=docs[i:i+500],
                    metadatas=metas[i:i+500],
                )

        logger.info("[vector-store] text-indexed %d songs", len(ids))
        return len(ids)
    finally:
        db.close()


def reindex_all_clap() -> dict:
    """Generate CLAP audio embeddings for ALL songs that have audio files.

    This is slow (~30-60s per song). Use sparingly — normally the background
    analysis pipeline handles this automatically for new songs.
    """
    from app.shared.database import SessionLocal
    from app.modules.library.models import LibrarySong
    from app.modules.playlists.models import Song, SongTag

    db = SessionLocal()
    try:
        # Find all library songs with audio files
        lib_songs = (
            db.query(LibrarySong)
            .filter(LibrarySong.source_path.isnot(None), LibrarySong.source_path != "")
            .all()
        )

        # Deduplicate by song_id (pick one file per catalog song)
        seen_song_ids: dict[int, LibrarySong] = {}
        for ls in lib_songs:
            if ls.song_id and ls.song_id not in seen_song_ids and os.path.isfile(ls.source_path):
                seen_song_ids[ls.song_id] = ls

        success, fail = 0, 0
        for song_id, ls in seen_song_ids.items():
            tags = db.query(SongTag).filter(SongTag.song_id == song_id).first()
            ok = index_song_clap(
                song_id=str(song_id),
                audio_path=ls.source_path,
                title=ls.title,
                artist=ls.artist,
                style=tags.style if tags else None,
                energy=tags.energy if tags else None,
                groove=tags.groove_tag if tags else None,
                bpm=float(tags.bpm) if tags and tags.bpm else (ls.bpm if ls.bpm else None),
            )
            if ok:
                success += 1
            else:
                fail += 1

        return {"success": success, "failed": fail, "total": len(seen_song_ids)}
    finally:
        db.close()


def get_collection_stats(collection_name: str = COLLECTION_CLAP) -> dict:
    """Return stats for the CLAP collection."""
    try:
        clap_col = get_clap_collection()
        text_col = get_text_collection()
        return {
            "collection": COLLECTION_CLAP,
            "count": clap_col.count(),
            "text_count": text_col.count(),
        }
    except Exception as e:
        return {"collection": collection_name, "count": 0, "error": str(e)}
