"""ChromaDB vector store with CLAP cross-modal embeddings.

- Audio embeddings: generated by _run_clap_audio.py subprocess during
  background analysis (Phase 3).  Produces a 512-d vector from the actual
  audio waveform.
- Text embeddings: generated by _run_clap_text.py subprocess at query time.
  Produces a 512-d vector from natural-language vibe description.

Both live in the same vector space so cosine similarity measures how well
a text description matches the *sound* of a song — not just its metadata.

Subprocess isolation keeps the ~1.5 GB CLAP model out of the uvicorn
worker's resident memory.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
from typing import List, Optional

import chromadb

logger = logging.getLogger(__name__)

CHROMA_PATH = os.environ.get("CHROMA_PATH", "./data/chroma_db")
COLLECTION_CLAP = "harbeat_clap"           # CLAP audio embeddings
COLLECTION_TEXT = "harbeat_songs"          # fallback text embeddings (old)

_CLAP_AUDIO_SCRIPT = os.path.join(os.path.dirname(__file__), "_run_clap_audio.py")
_CLAP_TEXT_SCRIPT = os.path.join(os.path.dirname(__file__), "_run_clap_text.py")

# CLAP embedding dimension
CLAP_DIM = 512


def _get_client() -> chromadb.ClientAPI:
    os.makedirs(CHROMA_PATH, exist_ok=True)
    return chromadb.PersistentClient(path=CHROMA_PATH)


def get_clap_collection():
    """Get the CLAP collection (no default embedding function — we supply vectors)."""
    client = _get_client()
    return client.get_or_create_collection(
        name=COLLECTION_CLAP,
        metadata={"hnsw:space": "cosine"},
    )


def get_text_collection():
    """Get the text-based fallback collection.

    Uses a PyTorch-backed sentence-transformer embedding function instead of
    ChromaDB's DefaultEmbeddingFunction (which relies on onnxruntime and
    crashes with SIGABRT on Jetson ARM64).
    """
    client = _get_client()
    ef = _get_safe_embedding_function()
    try:
        return client.get_or_create_collection(name=COLLECTION_TEXT, embedding_function=ef)
    except ValueError:
        # Embedding function conflict: collection was created with a different EF.
        # Delete and recreate with the current EF.
        logger.warning("[vector_store] EF conflict on %s, recreating collection", COLLECTION_TEXT)
        client.delete_collection(name=COLLECTION_TEXT)
        return client.get_or_create_collection(name=COLLECTION_TEXT, embedding_function=ef)


def _get_safe_embedding_function():
    """Return a ChromaDB-compatible embedding function that does NOT use onnxruntime."""
    try:
        # Use HuggingFace mirror for Chinese network
        import os
        os.environ.setdefault("HF_ENDPOINT", "https://hf-mirror.com")
        from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction
        import torch
        device = "cuda" if torch.cuda.is_available() else "cpu"
        logger.info("[vector_store] SentenceTransformer device=%s", device)
        return SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2",
            device=device,
        )
    except Exception as exc:
        logger.warning("[vector_store] SentenceTransformerEmbeddingFunction unavailable (%s), using noop", exc)
        # DO NOT fall back to DefaultEmbeddingFunction — it uses onnxruntime
        # which crashes with SIGABRT on Jetson ARM64.
        return _NoopEmbeddingFunction()


class _NoopEmbeddingFunction:
    """Minimal embedding function that returns zero vectors.

    Used as last-resort fallback so ChromaDB can still operate without
    onnxruntime (which crashes on Jetson ARM64).  Semantic quality is
    lost but the server stays alive.
    """

    def name(self) -> str:
        return "noop"

    def __call__(self, input: list[str]) -> list[list[float]]:
        return [[0.0] * 384 for _ in input]


# ── Subprocess helpers ──────────────────────────────────────────────

def _run_clap_audio_subprocess(audio_path: str) -> List[float]:
    """Run CLAP audio embedding in a child process. Returns 512-d vector."""
    result = subprocess.run(
        [sys.executable, _CLAP_AUDIO_SCRIPT, audio_path],
        capture_output=True, text=True, timeout=300,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()[-500:]
        raise RuntimeError(f"CLAP audio subprocess exit={result.returncode} stderr={stderr}")
    return json.loads(result.stdout)


def _run_clap_text_subprocess(query: str) -> List[float]:
    """Run CLAP text embedding in a child process. Returns 512-d vector."""
    result = subprocess.run(
        [sys.executable, _CLAP_TEXT_SCRIPT, query],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()[-500:]
        raise RuntimeError(f"CLAP text subprocess exit={result.returncode} stderr={stderr}")
    return json.loads(result.stdout)


def _run_clap_text_batch_subprocess(texts: List[str]) -> List[List[float]]:
    """Run CLAP text embedding in batch mode. Returns list of 512-d vectors."""
    result = subprocess.run(
        [sys.executable, _CLAP_TEXT_SCRIPT, "--batch"],
        input=json.dumps(texts),
        capture_output=True, text=True, timeout=300,
    )
    if result.returncode != 0:
        stderr = (result.stderr or "").strip()[-500:]
        raise RuntimeError(f"CLAP text batch subprocess exit={result.returncode} stderr={stderr}")
    return json.loads(result.stdout)


# ── Build metadata text (for display & fallback) ────────────────────

def _build_document(title: str, artist: str, style: Optional[str] = None,
                    energy: Optional[str] = None, groove: Optional[str] = None,
                    bpm: Optional[float] = None) -> str:
    parts = [f"{title} by {artist}"]
    if style:
        parts.append(f"style: {style}")
    if energy:
        parts.append(f"energy: {energy}")
    if groove:
        parts.append(f"groove: {groove}")
    if bpm:
        parts.append(f"bpm: {int(bpm)}")
    return ", ".join(parts)


# ── Index a single song with CLAP audio embedding ───────────────────

def index_song_clap(song_id: str, audio_path: str, title: str, artist: str,
                    style: Optional[str] = None, energy: Optional[str] = None,
                    groove: Optional[str] = None, bpm: Optional[float] = None) -> bool:
    """Generate CLAP audio embedding and store in ChromaDB.

    Returns True on success, False on failure.
    """
    try:
        embedding = _run_clap_audio_subprocess(audio_path)
    except Exception:
        logger.exception("[clap] failed to generate audio embedding for %s", song_id)
        return False

    collection = get_clap_collection()
    doc = _build_document(title, artist, style, energy, groove, bpm)
    metadata = {"song_id": str(song_id), "title": title, "artist": artist}
    if style:
        metadata["style"] = style
    if energy:
        metadata["energy"] = energy
    if groove:
        metadata["groove"] = groove
    if bpm is not None:
        metadata["bpm"] = float(bpm)

    collection.upsert(
        ids=[str(song_id)],
        embeddings=[embedding],
        documents=[doc],
        metadatas=[metadata],
    )
    logger.info("[clap] indexed song %s with CLAP audio embedding", song_id)
    return True


# ── Index song with text-only fallback (no audio file needed) ────────

def index_song(song_id: str, title: str, artist: str,
               style: Optional[str] = None, energy: Optional[str] = None,
               groove: Optional[str] = None, bpm: Optional[float] = None,
               collection_name: str = COLLECTION_TEXT) -> None:
    """Add song to text-based fallback collection."""
    collection = get_text_collection()
    doc = _build_document(title, artist, style, energy, groove, bpm)
    metadata = {"song_id": str(song_id), "title": title, "artist": artist}
    if style:
        metadata["style"] = style
    if energy:
        metadata["energy"] = energy
    if groove:
        metadata["groove"] = groove
    if bpm is not None:
        metadata["bpm"] = float(bpm)

    collection.upsert(
        ids=[str(song_id)],
        documents=[doc],
        metadatas=[metadata],
    )


# ── Search: prefer CLAP, fallback to text ────────────────────────────

def search_songs(query: str, top_k: int = 12) -> List[dict]:
    """Semantic search using CLAP text→audio cross-modal matching.

    Generates a CLAP text embedding for the query, then finds the closest
    audio embeddings in the CLAP collection.  Falls back to text-based
    search if the CLAP collection is empty or the subprocess fails.
    """
    # Try CLAP cross-modal search first
    clap_col = get_clap_collection()
    if clap_col.count() > 0:
        try:
            query_embedding = _run_clap_text_subprocess(query)
            results = clap_col.query(
                query_embeddings=[query_embedding],
                n_results=min(top_k, clap_col.count()),
                include=["metadatas", "distances", "documents"],
            )
            rows = _parse_results(results)
            if rows:
                logger.info("[clap] search returned %d results (CLAP cross-modal)", len(rows))
                return rows
        except Exception:
            logger.warning("[clap] CLAP text subprocess failed, falling back to text search", exc_info=True)

    # Fallback: text-based semantic search via sentence-transformers (PyTorch).
    # Uses SentenceTransformerEmbeddingFunction instead of ChromaDB's
    # DefaultEmbeddingFunction to avoid onnxruntime SIGABRT on Jetson ARM64.
    try:
        text_col = get_text_collection()
        if text_col.count() > 0:
            results = text_col.query(
                query_texts=[query],
                n_results=min(top_k, text_col.count()),
                include=["metadatas", "distances", "documents"],
            )
            rows = _parse_results(results)
            if rows:
                logger.info("[clap] fallback text search returned %d results", len(rows))
                return rows
    except Exception:
        logger.warning("[clap] text fallback search failed", exc_info=True)
    return []


def _parse_results(results: dict) -> List[dict]:
    metadatas = results.get("metadatas", [[]])[0] or []
    distances = results.get("distances", [[]])[0] or []
    documents = results.get("documents", [[]])[0] or []
    rows = []
    for meta, dist, doc in zip(metadatas, distances, documents):
        item = dict(meta or {})
        item["distance"] = float(dist)
        item["document"] = doc
        rows.append(item)
    return rows


# ── Collection-aware search (ported from FinalReco search_service.py) ──


def search_collection(
    query_text: str,
    collection_name: str = COLLECTION_CLAP,
    top_k: int = 10,
) -> List[dict]:
    """Semantic search within a named ChromaDB collection.

    Uses CLAP text→audio cross-modal when collection has vectors;
    falls back to text-based search for collections using an embedding function.
    """
    try:
        collection = _get_client().get_collection(name=collection_name)
    except Exception:
        logger.warning("[vector_store] collection %s not found", collection_name)
        return []

    # Try CLAP text embedding for cross-modal search
    try:
        query_embedding = _run_clap_text_subprocess(query_text)
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=min(top_k, collection.count()),
            include=["metadatas", "distances", "documents"],
        )
        return _parse_results(results)
    except Exception:
        logger.debug("[vector_store] CLAP search failed, trying text fallback")

    # Text fallback
    try:
        results = collection.query(
            query_texts=[query_text],
            n_results=min(top_k, collection.count()),
            include=["metadatas", "distances", "documents"],
        )
        return _parse_results(results)
    except Exception:
        logger.warning("[vector_store] search_collection failed", exc_info=True)
        return []


def fetch_with_multiplier(
    collection_name: str,
    target_length: int,
    multiplier: int = 5,
    query_text: Optional[str] = None,
    recall_all_under: int = 0,
) -> List[dict]:
    """Fetch oversampled candidate pool from a ChromaDB collection.

    Used by DJ planning to get more candidates than needed, so downstream
    filtering (energy/style scoring) has enough material to work with.
    """
    if target_length <= 0:
        return []

    try:
        collection = _get_client().get_collection(name=collection_name)
    except Exception:
        return []

    collection_size = collection.count()
    top_k = max(target_length * max(1, multiplier), target_length)
    if recall_all_under > 0 and collection_size > 0 and collection_size <= recall_all_under:
        top_k = collection_size

    if query_text and query_text.strip():
        try:
            query_embedding = _run_clap_text_subprocess(query_text)
            results = collection.query(
                query_embeddings=[query_embedding],
                n_results=min(top_k, collection_size),
                include=["metadatas", "distances", "documents"],
            )
            return _parse_results(results)
        except Exception:
            logger.warning("[vector_store] CLAP query failed in fetch_with_multiplier")

    # No query: fetch all available
    payload = collection.get(
        limit=top_k,
        include=["metadatas", "documents"],
    )
    metadatas = payload.get("metadatas", []) or []
    documents = payload.get("documents", []) or []
    rows: List[dict] = []
    for idx, meta in enumerate(metadatas):
        item = dict(meta or {})
        item["distance"] = 1.0
        item["document"] = documents[idx] if idx < len(documents) else ""
        rows.append(item)
    return rows[:top_k]


def fetch_stage_candidates(
    collection_name: str,
    target_length: int,
    target_energy_curve: List[float],
    style_ratios: Dict[str, float],
    multiplier: int = 5,
    query_text: Optional[str] = None,
    recall_all_under: int = 0,
) -> Dict[str, object]:
    """Stage-wise candidate recall with energy band + style quota filtering.

    Ported from FinalReco/services/search_service.py.

    Returns {"pool": merged_candidates, "stages": stage_outputs}.
    """
    from math import floor

    base_rows = fetch_with_multiplier(
        collection_name=collection_name,
        target_length=target_length,
        multiplier=multiplier,
        query_text=query_text,
        recall_all_under=recall_all_under,
    )

    # Normalize style_ratios
    cleaned: Dict[str, float] = {}
    for k, v in (style_ratios or {}).items():
        name = str(k).strip().lower()
        if not name:
            continue
        try:
            ratio = float(v)
        except (TypeError, ValueError):
            continue
        if ratio > 0:
            cleaned[name] = ratio
    total = sum(cleaned.values())
    if total > 0:
        cleaned = {k: v / total for k, v in cleaned.items()}

    # Split energy curve into 3 macro stages
    curve = [max(1.0, min(10.0, float(v))) for v in (target_energy_curve or [])]
    if not curve:
        curve = [7.0] * target_length
    if len(curve) < target_length:
        curve.extend([curve[-1]] * (target_length - len(curve)))
    curve = curve[:target_length]

    stage_count = min(3, target_length)
    base = target_length // stage_count
    remainder = target_length % stage_count
    stages: List[dict] = []
    cursor = 0
    for stage_idx in range(stage_count):
        slot_count = base + (1 if stage_idx < remainder else 0)
        values = curve[cursor:cursor + slot_count]
        cursor += slot_count
        e_min = max(1.0, min(values) - 0.6)
        e_max = min(10.0, max(values) + 0.6)
        stages.append({
            "stage_idx": stage_idx,
            "slot_count": slot_count,
            "energy_min": round(e_min, 3),
            "energy_max": round(e_max, 3),
            "target_curve": values,
        })

    def _extract_energy(row: dict) -> float:
        raw = row.get("energy", 5.0)
        try:
            return max(1.0, min(10.0, float(raw)))
        except (TypeError, ValueError):
            return 5.0

    def _extract_styles(row: dict) -> List[str]:
        styles = row.get("dominant_styles") or []
        if isinstance(styles, list):
            return [str(s).strip().lower() for s in styles if str(s).strip()]
        if styles:
            return [str(styles).strip().lower()]
        return []

    def _style_bonus(row: dict) -> float:
        if not cleaned:
            return 0.0
        styles = _extract_styles(row)
        return max((cleaned.get(s, 0.0) for s in styles), default=0.0)

    used_ids: set[str] = set()
    merged_pool: List[dict] = []
    stage_outputs: List[dict] = []

    for stage in stages:
        slot_count = int(stage["slot_count"])
        e_min = float(stage["energy_min"])
        e_max = float(stage["energy_max"])

        energy_filtered = [
            row for row in base_rows
            if e_min <= _extract_energy(row) <= e_max
        ]
        if not energy_filtered:
            energy_filtered = list(base_rows)

        energy_filtered.sort(key=lambda r: (r.get("distance", 1.0), -_style_bonus(r)))

        # Style quota allocation
        style_target: Dict[str, int] = {}
        if cleaned and slot_count > 0:
            floors: Dict[str, int] = {}
            fractional: List[tuple] = []
            used = 0
            for style, ratio in cleaned.items():
                raw = ratio * slot_count
                val = floor(raw)
                floors[style] = val
                used += val
                fractional.append((raw - val, style))
            fractional.sort(reverse=True)
            idx = 0
            while used < slot_count and fractional:
                s = fractional[idx % len(fractional)][1]
                floors[s] = floors.get(s, 0) + 1
                used += 1
                idx += 1
            style_target = floors

        local_used = set(used_ids)
        stage_selected: List[dict] = []

        for style, quota in style_target.items():
            picked: List[dict] = []
            for row in energy_filtered:
                track_id = str(row.get("spotify_id") or row.get("track_id") or row.get("id") or "").strip()
                if not track_id or track_id in local_used:
                    continue
                if style in _extract_styles(row):
                    picked.append(row)
                    local_used.add(track_id)
                    if len(picked) >= quota:
                        break
            stage_selected.extend(picked)

        for row in energy_filtered:
            if len(stage_selected) >= slot_count:
                break
            track_id = str(row.get("spotify_id") or row.get("track_id") or row.get("id") or "").strip()
            if not track_id or track_id in local_used:
                continue
            stage_selected.append(row)
            local_used.add(track_id)

        used_ids = local_used
        merged_pool.extend(stage_selected)
        stage_outputs.append({
            "stage_idx": stage["stage_idx"],
            "slot_count": slot_count,
            "energy_min": stage["energy_min"],
            "energy_max": stage["energy_max"],
            "target_curve": stage["target_curve"],
            "style_target": style_target,
            "style_actual": {},  # filled by caller
            "candidates": stage_selected,
        })

    # Fill missing slots
    if len(merged_pool) < target_length:
        for row in base_rows:
            track_id = str(row.get("spotify_id") or row.get("track_id") or row.get("id") or "").strip()
            if not track_id or track_id in used_ids:
                continue
            merged_pool.append(row)
            used_ids.add(track_id)
            if len(merged_pool) >= target_length:
                break

    return {"pool": merged_pool, "stages": stage_outputs}


# ── Batch reindex ────────────────────────────────────────────────────

def index_all_songs_from_db() -> int:
    """Index all songs into the text-based collection.

    For CLAP audio embeddings, use the /reindex-clap endpoint or let
    the background analysis pipeline handle them one by one.
    """
    from app.shared.database import SessionLocal
    from app.modules.playlists.models import Song, SongTag

    db = SessionLocal()
    try:
        rows = db.query(Song, SongTag).outerjoin(SongTag, SongTag.song_id == Song.id).all()
        collection = get_text_collection()
        ids, docs, metas = [], [], []
        for song, tags in rows:
            sid = str(song.id)
            style = tags.style if tags else None
            energy = tags.energy if tags else None
            groove = tags.groove_tag if tags else None
            bpm_val = float(tags.bpm) if tags and tags.bpm else None

            doc = _build_document(song.title, song.artist, style, energy, groove, bpm_val)
            meta = {"song_id": sid, "title": song.title, "artist": song.artist}
            if style:
                meta["style"] = style
            if energy:
                meta["energy"] = energy
            if groove:
                meta["groove"] = groove
            if bpm_val is not None:
                meta["bpm"] = bpm_val

            ids.append(sid)
            docs.append(doc)
            metas.append(meta)

        if ids:
            for i in range(0, len(ids), 500):
                collection.upsert(
                    ids=ids[i:i+500],
                    documents=docs[i:i+500],
                    metadatas=metas[i:i+500],
                )

        logger.info("[vector-store] text-indexed %d songs", len(ids))
        return len(ids)
    finally:
        db.close()


def reindex_all_clap() -> dict:
    """Generate CLAP audio embeddings for ALL songs that have audio files.

    This is slow (~30-60s per song). Use sparingly — normally the background
    analysis pipeline handles this automatically for new songs.
    """
    from app.shared.database import SessionLocal
    from app.modules.library.models import LibrarySong
    from app.modules.playlists.models import Song, SongTag

    db = SessionLocal()
    try:
        # Find all library songs with audio files
        lib_songs = (
            db.query(LibrarySong)
            .filter(LibrarySong.source_path.isnot(None), LibrarySong.source_path != "")
            .all()
        )

        # Deduplicate by song_id (pick one file per catalog song)
        seen_song_ids: dict[int, LibrarySong] = {}
        for ls in lib_songs:
            if ls.song_id and ls.song_id not in seen_song_ids and os.path.isfile(ls.source_path):
                seen_song_ids[ls.song_id] = ls

        success, fail = 0, 0
        for song_id, ls in seen_song_ids.items():
            tags = db.query(SongTag).filter(SongTag.song_id == song_id).first()
            ok = index_song_clap(
                song_id=str(song_id),
                audio_path=ls.source_path,
                title=ls.title,
                artist=ls.artist,
                style=tags.style if tags else None,
                energy=tags.energy if tags else None,
                groove=tags.groove_tag if tags else None,
                bpm=float(tags.bpm) if tags and tags.bpm else (ls.bpm if ls.bpm else None),
            )
            if ok:
                success += 1
            else:
                fail += 1

        return {"success": success, "failed": fail, "total": len(seen_song_ids)}
    finally:
        db.close()


def get_collection_stats(collection_name: str = COLLECTION_CLAP) -> dict:
    """Return stats for the CLAP collection."""
    try:
        clap_col = get_clap_collection()
        text_col = get_text_collection()
        return {
            "collection": COLLECTION_CLAP,
            "count": clap_col.count(),
            "text_count": text_col.count(),
        }
    except Exception as e:
        return {"collection": collection_name, "count": 0, "error": str(e)}
