from pathlib import Path
path = Path(r'd:\harbeat\GrooveEngine\web_app.py')
text = path.read_text(encoding='utf-8')
text = text.replace('from audio.offline_renderer import OfflineDualDeckRenderer\n', 'from audio.artifacts import export_playlist_artifact, export_transition_artifact\nfrom audio.offline_renderer import OfflineDualDeckRenderer\n')
text = text.replace("U=B/'temp_uploads'; R=B/'temp_songformer_results'; M=B/'temp_metadata'; O=B/'temp_outputs'\nfor d in [U,R,M,O]: d.mkdir(exist_ok=True)\n", "U=B/'temp_uploads'; R=B/'temp_songformer_results'; M=B/'temp_metadata'; O=B/'temp_outputs'; A=B/'temp_artifacts'\nfor d in [U,R,M,O,A]: d.mkdir(exist_ok=True)\n")
old = "def mix_playlist(track_ids):\n    items=ordered_renderables(track_ids)\n    metadata=[MetadataStorage.load(item['metadata_path']) for item in items]\n    playlist_plan=playlist_planner.plan(metadata)\n    ordered_items=[LIB[track_id] for track_id in playlist_plan.ordered_track_ids]\n    ordered_md=[MetadataStorage.load(item['metadata_path']) for item in ordered_items]\n    current=la(ordered_md[0].path,44100); transitions=[]\n    for index,transition in enumerate(playlist_plan.transitions,1):\n        result=renderer.render_transition(current,ordered_md[index-1],ordered_items[index-1]['title'],transition.plan,la(ordered_md[index].path,44100),ordered_md[index],ordered_items[index]['title'])\n        current=result.audio; transitions.append(result.transition_summary)\n    out=O/f'medley_{uuid4().hex[:8]}.wav'; sf.write(out,np.clip(current,-1,1),44100)\n    return {'audio_url':f'/outputs/{out.name}','filename':out.name,'duration_seconds':len(current)/44100,'track_count':len(ordered_items),'ordered_track_ids':playlist_plan.ordered_track_ids,'ordered_titles':playlist_plan.ordered_titles,'average_score':playlist_plan.average_score,'playlist_notes':playlist_plan.notes,'transitions':transitions}\n"
new = "def mix_playlist(track_ids):\n    items=ordered_renderables(track_ids)\n    metadata=[MetadataStorage.load(item['metadata_path']) for item in items]\n    playlist_plan=playlist_planner.plan(metadata)\n    ordered_items=[LIB[track_id] for track_id in playlist_plan.ordered_track_ids]\n    ordered_md=[MetadataStorage.load(item['metadata_path']) for item in ordered_items]\n    current=la(ordered_md[0].path,44100); transitions=[]; transition_artifacts=[]; run_id=uuid4().hex[:8]\n    for index,transition in enumerate(playlist_plan.transitions,1):\n        result=renderer.render_transition(current,ordered_md[index-1],ordered_items[index-1]['title'],transition.plan,la(ordered_md[index].path,44100),ordered_md[index],ordered_items[index]['title'])\n        current=result.audio; transitions.append(result.transition_summary)\n        artifact_path=A/f'transition_{index}_{run_id}.json'\n        export_transition_artifact(artifact_path,track_a_title=ordered_items[index-1]['title'],track_b_title=ordered_items[index]['title'],plan=transition.plan,transition_summary=result.transition_summary,render_trace=result.render_trace)\n        transition_artifacts.append({'path':str(artifact_path),'summary':result.transition_summary})\n    out=O/f'medley_{run_id}.wav'; sf.write(out,np.clip(current,-1,1),44100)\n    mix_result={'audio_url':f'/outputs/{out.name}','filename':out.name,'duration_seconds':len(current)/44100,'track_count':len(ordered_items),'ordered_track_ids':playlist_plan.ordered_track_ids,'ordered_titles':playlist_plan.ordered_titles,'average_score':playlist_plan.average_score,'playlist_notes':playlist_plan.notes,'transitions':transitions}\n    playlist_artifact=A/f'playlist_{run_id}.json'; export_playlist_artifact(playlist_artifact,playlist_plan=playlist_plan,mix_result=mix_result,transition_artifacts=transition_artifacts)\n    return {**mix_result,'artifact_path':str(playlist_artifact),'transition_artifacts':transition_artifacts}\n"
text = text.replace(old, new)
path.write_text(text, encoding='utf-8')
