import {describe,it,expect} from 'vitest'
import {planNext,type Track} from '../realtime/planner'
import {makeV30Planner,assessExit} from './planner'
import {buildV30Eq} from './eq'
function track(id:string):Track {return {id,title:id,bpm:120,style:'Trap',styleScore:1,duration:80,native:{url:id,sha256:'encoded',duration:80,bytes:1},provenance:{masterSha256:'m',reportSha256:'r',vocalSha256:'v'},bars:Array.from({length:40},(_,i)=>i*2),sections:[{start:0,end:80,label:'verse'}],vocals:[[0,80]],energy:[{start:0,end:80,value:.4}],windows:[{id:'w',start:0,end:8,bars:4,role:'intro',energy:.4,variants:{a:{url:'clip',sha256:'c',duration:8,bytes:1,rate:1}}}],alignment:{schema:'x',status:'candidate',source:{reportId:'report',masterSha256:'m',reportSha256:'r',vocalSha256:'v'},bars:Array.from({length:39},(_,i)=>({index:i,start:i*2,end:i*2+2,lastBeat:i*2+1.5,beats:[0,.5,1,1.5].map(x=>x+i*2),valid:true})),phrases:[{id:'p',start:0,end:11,tailEnd:11.1,nextStart:null,sectionIndex:0,sourceRows:{vad:[0],rms:[0]},semanticStatus:'unverified'}],exits:[],conflicts:[],bandFrames:[{start:0,end:80,rmsDbfs:-15,low:-20,mid:-22,high:-30}],limitations:[]}}}
const args=(a:Track,b:Track,budget=18)=>[a,[a,b] as Track[],0,{kind:'next' as const,targetId:b.id},new Set<string>(),budget,false] as const
describe('V3 small correction',()=>{
 it('keeps exact V3 plan when correction is off; only adds evidence',()=>{const a=track('a'),b=track('b'),old=planNext(...args(a,b)).best!,p=makeV30Planner(false,'fixed')(...args(a,b)).best!;expect(p.id).toBe(old.id);expect(p.duration).toBe(8);expect(p.automation).toBeUndefined();expect(p.phrase).toBeUndefined();expect(p.v30Tune?.shiftSec).toBe(0)})
 it('moves the whole overlap one existing bar later to avoid cutting an active phrase',()=>{const a=track('a'),b=track('b'),old=planNext(...args(a,b)).best!,p=makeV30Planner(true,'fixed')(...args(a,b)).best!;expect(old.end).toBe(10);expect(p.end).toBe(12);expect(p.start-old.start).toBe(2);expect(p.duration).toBe(old.duration);expect(p.asset).toEqual(old.asset);expect(p.window).toEqual(old.window);expect(p.v30Tune?.before.activePhraseId).toBe('p');expect(p.v30Tune?.after.activePhraseId).toBeNull()})
 it('keeps original if next bar exceeds budget, evidence is stale, or still cuts voice',()=>{for(const kind of ['budget','stale','voice']){const a=track('a'),b=track('b');if(kind==='stale')a.alignment!.source.reportSha256='stale';if(kind==='voice')a.alignment!.phrases[0].tailEnd=70;const input=args(a,b,kind==='budget'?11:18);expect(makeV30Planner(true,'fixed')(...input).best!.id).toBe(planNext(...input).best!.id)}})
 it('retains V3 when VAD/RMS disagree near either exit',()=>{const a=track('a'),b=track('b');a.alignment!.conflicts=[{code:'vad_without_rms_activity',start:9.9,end:11}];const input=args(a,b);expect(makeV30Planner(true,'fixed')(...input).best!.id).toBe(planNext(...input).best!.id)})
 it('distinguishes last beat from the following downbeat and rejects missing observed beats',()=>{const a=track('a');expect(assessExit(a,10).lastBeat).toBe(9.5);a.alignment!.bars[4].valid=false;expect(assessExit(a,10).gridValid).toBe(false)})
})
describe('V3 EQ-only automation',()=>{
 it('responds to source band changes with no gain or duration automation and bounded slopes',()=>{const a=track('a'),b=track('b'),p=planNext(...args(a,b)).best!,quiet=buildV30Eq(a,b,p);b.alignment!.bandFrames[0].low=-4;const loud=buildV30Eq(a,b,p);expect(loud.b).not.toEqual(quiet.b);expect('aGain' in loud).toBe(false);expect(loud.evidence[0].a.rows[0]).toBe(1);for(const [points,base] of [[loud.a,loud.template.a],[loud.b,loud.template.b]] as const)for(let i=0;i<points.length;i++)for(const band of ['low','mid','high'] as const){expect(Math.abs(points[i][band]-base[band])).toBeLessThanOrEqual(band==='mid'?2.00001:3.00001);if(i)expect(Math.abs(points[i][band]-points[i-1][band])/(points[i].t-points[i-1].t)).toBeLessThanOrEqual(3.00001)}})
 it('keeps cue decisions identical between fixed and dynamic EQ',()=>{const a=track('a'),b=track('b');for(const adjust of [false,true]){const f=makeV30Planner(adjust,'fixed')(...args(a,b)).best!,d=makeV30Planner(adjust,'dynamic')(...args(a,b)).best!;expect(d.id).toBe(f.id);expect(d.start).toBe(f.start);expect(d.duration).toBe(f.duration);expect(d.midDuck).toBe(f.midDuck);expect(d.v30Eq).toBeTruthy()}})
 it('refuses dynamic mode on energy gaps instead of silently substituting fixed EQ',()=>{const a=track('a'),b=track('b');b.alignment!.bandFrames=[];const r=makeV30Planner(false,'dynamic')(...args(a,b));expect(r.best).toBeNull();expect(r.exclusions.some(e=>e.code==='v30_eq_unavailable')).toBe(true);expect(makeV30Planner(false,'fixed')(...args(a,b)).best).toBeTruthy()})
})
