import {completedAudition} from './feedback'
import {useEffect,useMemo,useRef,useState} from 'react'
import type {Plan,Track} from '../realtime/planner'
import {makeV30Planner} from './planner'
import {planV31,V31_RELEASE} from '../v31-release/release'
import {loadJson} from '../phrase/load'
import {LiveTransport} from '../realtime/transport'
import {AudioBufferPool} from '../realtime/cache'
import MixStoryboard from '../v31/MixStoryboard'
import logo from '../analysis/assets/harbeat-logo.png'
import '../v31/v31.css'
import './tuning.css'
type Arm='original-fixed'|'original-dynamic'|'tuned-fixed'|'tuned-dynamic'
type Case={id:string;a:string;b:string;position:number;group:string}
const armNames:Record<Arm,string>={'original-fixed':'① 原 V3 · 固定 EQ','original-dynamic':'② 原 V3 · 动态 EQ','tuned-fixed':'③ 小幅核验 · 固定 EQ','tuned-dynamic':'④ 小幅核验 · 动态 EQ'}
const arms=Object.keys(armNames) as Arm[],base=new URL('.',location.href),ratingKey=V31_RELEASE.feedbackKey
const planner=(arm:Arm)=>makeV30Planner(arm.startsWith('tuned'),arm.endsWith('dynamic')?'dynamic':'fixed')
const download=(v:unknown,name:string)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function EqChart({plan}:{plan:Plan}){
 const eq=plan.v30Eq,template={a:{low:-9,mid:0,high:-1.4},b:{low:-7,mid:plan.midDuck?-5:0,high:1.2}},x=(t:number)=>60+t/plan.duration*620,y=(d:number)=>30+(4-d)/18*160
 return <div className="eq-charts">{(['a','b'] as const).map(deck=><article key={deck}><h3>{deck.toUpperCase()} 的 EQ · {eq?'动态曲线':'原 V3 固定参数'}</h3><svg viewBox="0 0 720 235" role="img" aria-label={`${deck.toUpperCase()} 实际 EQ 控制曲线`}>{[-12,-8,-4,0,4].map(d=><g key={d}><line x1="60" x2="680" y1={y(d)} y2={y(d)} stroke="#e3e8df"/><text x="8" y={y(d)+4}>{d} dB</text></g>)}{(['low','mid','high'] as const).map((band,i)=>{const points=eq?.[deck]||[{t:0,...template[deck]},{t:plan.duration,...template[deck]}],color=['#527d36','#ad623d','#46769d'][i];return <g key={band}><line x1="60" x2="680" y1={y(template[deck][band])} y2={y(template[deck][band])} stroke={color} strokeDasharray="4 5" opacity=".45"/><path d={points.map((p,i)=>`${i?'L':'M'}${x(p.t)},${y(p[band])}`).join(' ')} fill="none" stroke={color} strokeWidth="2.5"/><text x={60+i*175} y="224" fill={color}>{['低频','中频','高频'][i]}</text></g>})}<text x="60" y="207">混入 0 秒</text><text x="680" y="207" textAnchor="end">接管 {plan.duration.toFixed(2)} 秒</text></svg></article>)}<p className="quiet">实线是滤波器的控制值，虚线是 V3 固定值。B 最后半小节通过原有干湿混合恢复原声，因此接管时即使系数不为 0，也不再听到该滤波支路。曲线不是输出响度。</p></div>
}
export default function V30Lab({officialRelease=false}:{officialRelease?:boolean}={}){
 const names=officialRelease?{...armNames,'original-dynamic':'V3.1 · 动态 EQ'}:armNames,visibleArms:Arm[]=officialRelease?[V31_RELEASE.acceptedArm]:arms
 const selectPlanner=(m:Arm)=>officialRelease&&m===V31_RELEASE.acceptedArm?planV31:planner(m)
 const policyVersion=officialRelease?V31_RELEASE.policyVersion:'v30-small-tuning-v1',filePrefix=officialRelease?'HarBeat-v3.1':'HarBeat-v30-small-tuning'
 const [pack,setPack]=useState<{tracks:Track[];cases:Case[];coverage:any}|null>(null),[aId,setA]=useState(''),[bId,setB]=useState(''),[position,setPosition]=useState(30),[arm,setArm]=useState<Arm>(officialRelease?V31_RELEASE.acceptedArm:'original-fixed'),[tab,setTab]=useState<'compare'|'live'>(officialRelease?'live':'compare'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[,refresh]=useState(0)
 const [feedback,setFeedback]=useState<Record<string,any>>(()=>{try{return JSON.parse(localStorage.getItem(ratingKey)||'{}')}catch{return {}}})
 const [heard,setHeard]=useState<{a:string;b:string;position:number;arm:Arm;planId:string}|null>(null)
 const player=useRef<LiveTransport|null>(null),key=useRef(''),init=useRef<Promise<void>|null>(null),pool=useRef(new AudioBufferPool()),rev=useRef(0),timer=useRef<ReturnType<typeof setTimeout>|null>(null)
 useEffect(()=>{let alive=true;Promise.all(['catalog.json','cases.json'].map(f=>loadJson(f,base))).then(([c,s])=>{if(!alive)return;setPack({tracks:c.tracks,cases:s.cases,coverage:s.coverage});const first=s.cases[0];setA(first.a);setB(first.b);setPosition(first.position)}).catch(e=>setError(e.message));return()=>{alive=false;rev.current++;if(timer.current)clearTimeout(timer.current);player.current?.dispose()}},[])
 const searches=useMemo(()=>{const a=pack?.tracks.find(t=>t.id===aId);if(!a||!pack)return null;return Object.fromEntries((officialRelease?['original-fixed','original-dynamic'] as Arm[]:arms).map(m=>[m,selectPlanner(m)(a,pack.tracks,position,{kind:'next',targetId:bId},new Set(),18,false)])) as Record<Arm,ReturnType<ReturnType<typeof planner>>>},[pack,aId,bId,position,officialRelease])
 const execution=player.current?.logs.filter(e=>e.kind==='plan_scheduled').at(-1)
 const activeId=player.current?.current?.id
 useEffect(()=>{if(tab==='live'&&activeId&&pack){if(aId!==activeId){setA(activeId);setPosition(0)}if(bId===activeId)setB(pack.tracks.find(t=>t.id!==activeId)!.id)}},[activeId,tab,pack,aId,bId])
 const completed=completedAudition(player.current?.logs||[])
 useEffect(()=>{if(completed)setHeard({...completed,arm})},[completed?.executionId,completed?.sessionId])
 if(!pack||!searches)return <main className="v31"><h1>HarBeat · {officialRelease?'V3.1 实时混音':'V3 小幅调整'}</h1><p role="status">{error||'正在读取 20 首曲目的原 V3 素材与核验证据…'}</p></main>
 const {tracks}=pack,a=tracks.find(t=>t.id===aId)!,p=player.current,locked=busy||!!p?.busy,caseId=`${aId}|${bId}|${position}`
 const actual=p?.pending?.plan||p?.lastPlan,q=tab==='live'&&actual?actual:searches[arm].best,original=searches['original-fixed'].best
 function stop(){rev.current++;if(timer.current)clearTimeout(timer.current);player.current?.stop();setBusy(false)}
 function reset(){stop();player.current?.dispose();player.current=null;key.current='';init.current=null;setHeard(null)}
 async function run(fn:()=>Promise<void>){const token=++rev.current;if(timer.current)clearTimeout(timer.current);setError('');setBusy(true);try{await fn()}catch(e){if(token===rev.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}finally{if(token===rev.current)setBusy(false)}}
 async function ensure(){const token=rev.current;if(player.current&&key.current===arm){const t=player.current;await init.current;if(token!==rev.current||player.current!==t)throw new DOMException('已取消','AbortError');return t}player.current?.dispose();const t=new LiveTransport(tracks,()=>refresh(n=>n+1),base,{planner:selectPlanner(arm),audioPool:pool.current,autoNext:false,prewarm:false,policyVersion,release:officialRelease?V31_RELEASE:undefined,noPlanMessage:'原 V3 的 18 秒范围内没有当前目标的可执行窗口，继续播放。可查看日志后重新请求。'});player.current=t;key.current=arm;init.current=t.initialize();try{await init.current}catch(e){if(player.current===t){player.current=null;key.current=''}t.dispose();throw e}if(token!==rev.current||player.current!==t)throw new DOMException('已取消','AbortError');t.log('source_catalog',{version:officialRelease?V31_RELEASE.id:'v30-tuning-20260924',release:officialRelease?V31_RELEASE:null,arm,base:'original twenty-track V3 catalog, original windows',changes:{adjacentBarCorrection:arm.startsWith('tuned'),dynamicEqOnly:arm.endsWith('dynamic'),gain:'original V3 full-overlap linear',maxWait:18,energyStyleRanking:false}});return t}
 async function audition(){const plan=searches![arm].best;if(!plan)return;setHeard(null);const t=await ensure();t.log('comparison_analysis',{caseId,arm,original:searches!['original-fixed'],selected:searches![arm],eqDoesNotChangeCues:true});await t.playComparison(plan,position,{experimentId:policyVersion,arm:arm==='original-fixed'?'baseline':'variant',midDb:-5,comparisonId:caseId+'|'+arm,skipWaiting:true,horizonSec:18})}
 async function inspect(trackId:string,time:number){const t=await ensure(),token=rev.current;t.log('source_inspection',{trackId,time,durationSec:8});await t.start(trackId,time);if(token===rev.current)timer.current=setTimeout(()=>t.stop(),8000)}
 async function prepare(){const t=await ensure(),from=t.current||a,pos=t.current?t.position:position,r=selectPlanner(arm)(from,tracks,pos,{kind:'next',targetId:bId},t.cache.ready,18,false);if(!r.best)throw Error('当前请求位置没有计划，请选择其他曲对或位置');const b=tracks.find(t=>t.id===r.best!.to)!;t.cache.protected=new Set([from.native.url,b.native.url,r.best.asset.url]);await Promise.all([from.native,b.native,r.best.asset].map(asset=>t.cache.load(asset)));t.log('manual_preload',{planId:r.best.id,doesNotSchedule:true});t.status='素材已准备；触发接歌时按当下位置重新规划'}
 function rate(value:string){if(!heard)return;const id=`${heard.a}|${heard.b}|${heard.position}|${heard.arm}`,row={...heard,value,at:new Date().toISOString()};setFeedback(current=>{let previous={};try{previous=JSON.parse(localStorage.getItem(ratingKey)||'{}')}catch{}const saved={...previous,...current,[id]:row};try{localStorage.setItem(ratingKey,JSON.stringify(saved))}catch{setError('反馈暂存在本页，请导出备份')}return saved})}
 return <main className="v31"><header><img src={logo} alt="HarBeat"/><div><div className="eyebrow">{officialRelease?"V3.1 · ACCEPTED RELEASE · 3.1.0":"V3 · SMALL CHANGES · SAME OVERLAP"}</div><h1>{officialRelease?"V3.1 · 保留完整的渐进交接。":"保留 V3 的渐进交接。"}</h1><p>{officialRelease?"你已认可的原 V3 选点＋动态 EQ，正式保存为 V3.1。":"先固定混合方式，再分别试听边界核验与动态 EQ。"}</p></div><a className="old-version" href="../v3-live-baseline-20260922/index.html">回到原 V3 实时版 ↗</a></header>
 <nav><button aria-pressed={tab==='compare'} onClick={()=>{reset();setTab('compare')}}>① 同曲对照</button><button aria-pressed={tab==='live'} onClick={()=>{reset();setTab('live')}}>② 播放中实时接歌</button><a href="/analysis-lab?tab=mix-debug">分析平台 / 历史日志 ↗</a><a href="../v31-candidate-20260923/index.html">{officialRelease?"历史保护版候选与偏好 ↗":"原 V3／V3.1 偏好记录 ↗"}</a>{officialRelease&&<a href={V31_RELEASE.experimentUrl}>原四项对照与反馈 ↗</a>}</nav>
 <aside className="scope">{officialRelease?"A 在完整重叠期间逐渐退出，B 同时逐渐进入。使用原 V3 的选点、素材和渐变时长，由动态 EQ 根据预处理证据调整频段。段落与人声核验保留为可查看的依据。":"A 从交接开始便逐渐退让，B 同时逐渐铺入，保持原 V3 的完整混合时长。边界核验最多把整段交接后移一个相邻小节；没有明确改善就保持原计划。动态 EQ 单独改变频段处理，不参与选歌或缩短交接。"}</aside>
 <section><h2>{officialRelease?"选择曲目，实时接歌":"每次只改变一个变量"}</h2><p>{officialRelease?"播放 A 后可随时请求切换到 B；也可以到“同曲对照”页快速试听一个转场。需要比较固定 EQ 时，可打开上方原四项对照。":"① 对比 ②，只听 EQ；① 对比 ③，只看边界是否微调；③ 对比 ④，在同一微调选点上听 EQ。若界面显示“后移 0 秒”，① 与 ③、② 与 ④的处理相同。"}</p>
 <label>试听曲对<select aria-label="试听曲对" disabled={locked||!!p?.active} value={pack.cases.find(c=>`${c.a}|${c.b}|${c.position}`===caseId)?.id||''} onChange={e=>{const c=pack.cases.find(c=>c.id===e.target.value)!;reset();setA(c.a);setB(c.b);setPosition(c.position)}}><option value="" disabled>自选曲对</option>{pack.cases.map(c=><option key={c.id} value={c.id}>{c.group==='boundary_examples'?'边界变化示例 · ':''}{tracks.find(t=>t.id===c.a)?.title} → {tracks.find(t=>t.id===c.b)?.title} · {c.position}s</option>)}</select></label>
 <div className="fields"><label>A 当前曲<select value={aId} disabled={locked||!!p?.active} onChange={e=>{reset();setA(e.target.value);if(e.target.value===bId)setB(tracks.find(t=>t.id!==e.target.value)!.id)}}>{tracks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>B 下一首<select value={bId} disabled={locked||!!p?.pending} onChange={e=>{setB(e.target.value);setHeard(null)}}>{tracks.filter(t=>t.id!==aId).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>A 请求位置（秒）<input aria-label="A 请求位置" type="number" min="0" max={a.duration-1} step=".1" value={position} disabled={locked||!!p?.active} onChange={e=>{reset();setPosition(Math.max(0,Math.min(a.duration-1,Number(e.target.value)||0)))}}/></label></div>
 <div className="variant-grid">{visibleArms.map(m=><button key={m} aria-pressed={arm===m} disabled={locked||tab==='live'&&!!p?.active} onClick={()=>{reset();setArm(m)}}><strong>{names[m]}</strong><span>{searches[m].best?`${searches[m].best!.duration.toFixed(2)} 秒重叠 · 后移 ${searches[m].best!.v30Tune!.shiftSec.toFixed(2)} 秒`:'当前位置没有计划'}</span></button>)}</div>
 {tab==='compare'?<div className="actions"><button className="primary" disabled={locked||!searches[arm].best} onClick={()=>run(audition)}>试听当前版本</button><span className="quiet">从混入前 4 秒开始，播放至交接后 8 秒。</span></div>:<div className="actions"><button disabled={locked||!!p?.active} onClick={()=>run(async()=>{const t=await ensure();await t.start(aId,position)})}>播放 A</button><button disabled={locked||!!p?.pending} onClick={()=>run(prepare)}>准备下一首素材</button><button className="primary" disabled={locked||!p?.active||!!p?.pending||p.current?.id===bId} onClick={()=>run(async()=>{await p!.request({kind:'next',targetId:bId},18)})}>现在请求接歌</button><button disabled={!p?.active} onClick={()=>run(()=>p!.togglePause())}>{p?.paused?'继续':'暂停'}</button><button disabled={!p?.pending} onClick={()=>p?.cancel()}>取消待执行接歌</button></div>}
 <div className="player-bar"><span role="status">{p?.status||'等待试听'}{p?.current?` · ${p.current.title} ${p.position.toFixed(2)}s`:''}</span><button onClick={stop}>停止</button><button disabled={!p} onClick={()=>download(p!.export(),filePrefix+'-session.json')}>导出完整日志</button></div>{error&&<p role="alert" className="error">{error}</p>}<p className="quiet">共用原曲和进入片段缓存，首次素材准备完成后，切换对照版本可复用音频。当前包含 {tracks.length} 首原曲、{pack.cases.filter(c=>c.group==='original20').length} 组原试听位置；无窗口的样本也保留。</p></section>
 <section><h2>{tab==='live'&&actual?'本次执行的计划':'试听前的计划'} · {names[arm]}</h2>{q?<>
 <div className="unchanged"><strong>完整重叠 {q.duration.toFixed(3)} 秒</strong><span>A 渐弱 {q.duration.toFixed(3)} 秒 / B 渐强 {q.duration.toFixed(3)} 秒</span><span>B 片段 {q.window.start.toFixed(2)}–{q.window.end.toFixed(2)} 秒 · {q.rate.toFixed(3)}×</span></div>
 <p>{q.v30Tune?.reason}</p><div className="table-scroll"><table><thead><tr><th>对齐证据</th><th>原 V3</th><th>当前方案</th></tr></thead><tbody><tr><td>A 混入 → 退出</td><td>{q.v30Tune?.originalStart.toFixed(3)} → {q.v30Tune?.originalEnd.toFixed(3)}s</td><td>{q.start.toFixed(3)} → {q.end.toFixed(3)}s</td></tr><tr><td>退出前小节的最后一拍</td><td>{q.v30Tune?.before.lastBeat?.toFixed(3)??'缺失'}s</td><td>{q.v30Tune?.after.lastBeat?.toFixed(3)??'缺失'}s</td></tr><tr><td>退出落在人声活动内？</td><td>{q.v30Tune?.before.sourceBound?(q.v30Tune.before.activePhraseId?'是，仍待试听核验':'未检出'):'证据不可用'}</td><td>{q.v30Tune?.after.sourceBound?(q.v30Tune.after.activePhraseId?'是，保持风险提示':'未检出'):'证据不可用'}</td></tr></tbody></table></div>
 <p className="quiet">最后一拍的起点与下一小节首拍是两个时刻。这里只校验观察拍点，不把尾音吸附或剪短到拍点；声学活动间隙不等于已确认的歌词句末。</p>
 <MixStoryboard a={tracks.find(t=>t.id===q.from)!} b={tracks.find(t=>t.id===q.to)!} plan={q} position={tab==='live'&&heard?heard.position:position} playTime={p?.pending?p.ctx.currentTime-p.pending.start:undefined} onInspect={(id,t)=>run(()=>inspect(id,t))}/><EqChart plan={q}/>
 <details><summary>此次微调理由、源数据行号与 EQ 控制点</summary><pre>{JSON.stringify({boundary:q.v30Tune,eq:q.v30Eq||'V3 固定 EQ',originalPlanId:original?.id},null,2)}</pre></details>
 </>:<p className="empty">{[...new Set(searches[arm].exclusions.filter(e=>['v30_eq_unavailable','deadline','missing_variant','grid_error'].includes(e.code)).map(e=>e.reason))].join('；')||'原 V3 在此请求位置没有可执行的计划。'}。当前音乐继续播放，不强行改变素材或缩短交接。</p>}
 <details><summary>原 V3 全部候选与当前搜索记录</summary><pre>{JSON.stringify(tab==='live'&&p?.lastSearch?p.lastSearch:searches[arm],null,2)}</pre></details></section>
 <section><h2>计划与实际执行</h2>{execution?<div className="table-scroll"><table><thead><tr><th>动作</th><th>计划音频时钟</th><th>音频线程观察</th><th>偏差</th></tr></thead><tbody>{execution.events.map((e:any)=>{const o=p?.logs.find(l=>l.kind==='audio_observation'&&l.planId===e.planId&&l.name===e.name);return <tr key={e.name}><td>{e.name}</td><td>{(e.frame/p!.ctx.sampleRate).toFixed(3)}s</td><td>{o?.observedContextSec?.toFixed(3)??'未发生'}</td><td>{o?.observationDeltaMs?.toFixed(2)??'—'} ms</td></tr>})}</tbody></table></div>:<p>触发转场后，显示混入、EQ 恢复、退出与接管的时刻。</p>}<p className="quiet">这是浏览器音频线程观察值，不是扬声器或蓝牙延迟测量。</p></section>
 <section><h2>保留试听偏好</h2><p>{heard?`${tracks.find(t=>t.id===heard.a)?.title} → ${tracks.find(t=>t.id===heard.b)?.title} · ${names[heard.arm]} · 请求位置 ${heard.position.toFixed(2)}s`:'先试听一个版本，再记录本次结果。'}</p><div className="actions">{['喜欢这版','与原 V3 差不多','仍有截句','衔接太突兀','EQ 不自然'].map(v=><button key={v} disabled={!heard} aria-pressed={!!heard&&feedback[`${heard.a}|${heard.b}|${heard.position}|${heard.arm}`]?.value===v} onClick={()=>rate(v)}>{v}</button>)}</div><button onClick={()=>download(feedback,filePrefix+'-feedback.json')}>导出本轮反馈（{Object.keys(feedback).length} 条）</button><p className="quiet">{officialRelease?"沿用你在原四项对照中保存的全部反馈。原记录及版本标识保持原样，新试听结果继续保存到同一本浏览器记录中。":"本轮使用独立记录。你已在原 V3／V3.1 页面保存的偏好不改动，仍可从顶部链接查看。"}</p></section>
 <footer>HarBeat · {officialRelease?"V3.1 正式版 3.1.0":"V3 小幅调整"} / 2026.09.24 · 20 首已有素材（每首最多 150 秒）。未重新训练识别模型；EQ 为基于预处理的局部控制规则，效果由同曲试听判断。</footer></main>
}
