const HBContent = Object.freeze({
  meta: {
    product: 'HarBeat',
    version: '1.0',
    date: '2026-08-18',
    specFile: '2026-08-18-harbeat-mobile-app-product-design.md',
    dataLabel: '演示数据 / Mock API',
  },
  views: {
    V01: { canonical: 'H01', name: '首页', section: 'home' },
    V02: { canonical: 'M01', name: '音乐 / 推荐', section: 'music' },
    V03: { canonical: 'M01', name: '搜索 / 导入', section: 'music' },
    V04: { canonical: 'M01 子页面', name: '歌曲详情', section: 'music' },
    V05: { canonical: 'M01', name: '曲库 / 歌单', section: 'music' },
    V06: { canonical: 'D01', name: '设备列表', section: 'device' },
    V07: { canonical: 'D01 配对状态', name: '配对', section: 'device' },
    V08: { canonical: 'D01 已连接状态', name: '设备面板', section: 'device' },
    V09: { canonical: 'D02', name: 'Pad 编辑', section: 'device' },
  },
  scenarios: {
    discover: { label: '发现音乐', steps: ['V01', 'V02', 'V04', 'V05'], doneMessage: '音乐已保存到曲库' },
    import: { label: '搜索或导入', steps: ['V02', 'V03', 'V04', 'V05'], doneMessage: '导入结果已保存' },
    device: { label: '配置设备', steps: ['V06', 'V07', 'V08', 'V09', 'V08'], doneMessage: 'Pad 预设已同步' },
  },
  songs: [
    { id: 'trk-electric', title: 'Electric Motion', artist: 'Nova Circuit', style: 'Popping', bpm: 104, key: 'F minor', energy: 82, resource: 'available', accent: 'violet' },
    { id: 'trk-lock', title: 'Lock It Down', artist: 'Pocket Theory', style: 'Locking', bpm: 110, key: 'A minor', energy: 76, resource: 'available', accent: 'mint' },
    { id: 'trk-midnight', title: 'After Midnight', artist: 'Velvet Transit', style: 'Hip-Hop', bpm: 96, key: 'D minor', energy: 64, resource: 'metadata_only', accent: 'orange' },
    { id: 'trk-rubber', title: 'Rubber Frame', artist: 'Signal Arcade', style: 'Popping', bpm: 108, key: 'C minor', energy: 88, resource: 'available', accent: 'red' },
    { id: 'trk-sidewalk', title: 'Sidewalk Syntax', artist: 'Blue Basement', style: 'Hip-Hop', bpm: 92, key: 'G minor', energy: 58, resource: 'available', accent: 'blue' },
    { id: 'trk-pocket', title: 'Pocket Parade', artist: 'The Breakmakers', style: 'Locking', bpm: 114, key: 'E minor', energy: 84, resource: 'available', accent: 'acid' },
    { id: 'trk-concrete', title: 'Concrete Breeze', artist: 'Low Rise Club', style: 'House', bpm: 124, key: 'B minor', energy: 71, resource: 'unavailable', accent: 'slate' },
    { id: 'trk-echo', title: 'Echo Practice', artist: 'Mono Steps', style: 'Popping', bpm: 100, key: 'F major', energy: 54, resource: 'available', accent: 'pink' },
  ],
  playlists: [
    { id: 'pl-practice', name: '本周练习', trackIds: [] },
    { id: 'pl-battle', name: 'Battle Warm-up', trackIds: ['trk-lock'] },
    { id: 'pl-late', name: 'Late Night Cypher', trackIds: ['trk-midnight', 'trk-sidewalk'] },
  ],
  devices: [
    { id: 'rk-stage-01', name: 'HarBeat Stage 01', host: '192.168.31.88', online: true, latency: 18, presetVersion: 3 },
    { id: 'rk-practice-02', name: 'Practice Room 02', host: '192.168.31.52', online: false, latency: null, presetVersion: 1 },
  ],
  sounds: ['Air Horn', 'Crowd Up', 'Hit', 'Scratch Stop'],
  pads: Array.from({ length: 8 }, (_, index) => ({
    id: `pad-${index + 1}`,
    label: `Pad ${index + 1}`,
    sound: index < 3 ? ['Air Horn', 'Crowd Up', 'Hit'][index] : null,
  })),
  handbookSections: ['定位', '系统职责', '目标用户', '信息架构', '关键流程', 'P0 边界', '协作清单'],
  annotations: {
    V01: {
      purpose: '汇总最近内容、设备状态和推荐入口',
      entry: '用户完成登录或从底部导航进入首页',
      primaryAction: '进入音乐推荐或设备页面',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock HomeSummary', 'Mock DeviceSummary', 'Mock RecommendationRail'],
      events: ['home_recommendation_opened', 'home_device_opened'],
      acceptance: ['无设备时仍可进入音乐功能', '设备摘要与 D01 状态一致'],
    },
    V02: {
      purpose: '根据舞种偏好和个人行为展示推荐音乐',
      entry: '从首页推荐卡或音乐 Tab 进入',
      primaryAction: '选择歌曲并进入详情试听',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock RecommendationSection[]', 'Mock TrackSummary[]'],
      events: ['recommendation_impression', 'recommendation_track_opened'],
      acceptance: ['活动 Session 行为不写入个人画像', '每首歌曲显示舞种与 BPM'],
    },
    V03: {
      purpose: '统一处理站内搜索、外部链接和本地文件导入',
      entry: '从音乐页搜索框或导入按钮进入',
      primaryAction: '选择合法可用的匹配结果',
      states: ['idle', 'loading', 'results', 'empty', 'error', 'offline'],
      data: ['示例 SearchRequest', '示例 ImportSource', 'Mock MatchResult[]'],
      events: ['music_search_submitted', 'external_link_parsed', 'local_file_selected'],
      acceptance: ['来源始终可见', '链接解析不承诺未经授权下载', '失败原因可以区分'],
    },
    V04: {
      purpose: '展示歌曲分析、资源状态并完成试听和保存',
      entry: '从推荐、搜索结果或曲库点击歌曲',
      primaryAction: '试听并保存到曲库或歌单',
      states: ['loading', 'available', 'metadata_only', 'unavailable', 'error', 'offline'],
      data: ['Mock TrackDetail', 'Mock AudioAnalysis', '待确认 ResourceAvailability'],
      events: ['track_preview_started', 'save_sheet_opened', 'track_saved'],
      acceptance: ['展示 BPM、调性、能量与段落', '仅元数据资源不能显示为可播放完整音频'],
    },
    V05: {
      purpose: '管理个人曲库与歌单并验证保存结果',
      entry: '从音乐页分区、保存成功反馈或底部导航进入',
      primaryAction: '查看歌曲或把歌曲加入歌单',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock LibraryTrack[]', 'Mock Playlist[]'],
      events: ['library_opened', 'playlist_opened', 'playlist_track_added'],
      acceptance: ['刚保存的歌曲立即出现', '曲库与歌单状态可区分'],
    },
    V06: {
      purpose: '展示最近设备并提供手动局域网地址入口',
      entry: '从设备 Tab 或首页设备卡进入',
      primaryAction: '选择设备或输入局域网地址',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock DeviceSummary[]', '待确认 ManualHostInput'],
      events: ['device_selected', 'manual_host_submitted'],
      acceptance: ['在线和离线设备可区分', '无设备时可以手动输入地址'],
    },
    V07: {
      purpose: '用配对码确认用户正在连接目标 RK3588',
      entry: '从 V06 选择在线设备或提交地址',
      primaryAction: '提交四位配对码',
      states: ['idle', 'submitting', 'invalid_code', 'error', 'offline'],
      data: ['示例 PairingRequest', '待确认 PairingResult'],
      events: ['pairing_code_submitted', 'pairing_succeeded', 'pairing_failed'],
      acceptance: ['错误配对码不会建立连接', '目标设备名称与地址始终可见'],
    },
    V08: {
      purpose: '解释设备连接、资源和 App/设备预设版本状态',
      entry: '配对成功或进入已连接的设备 Tab',
      primaryAction: '进入 Pad 编辑或处理版本差异',
      states: ['connected', 'syncing', 'dirty', 'synced', 'error', 'offline'],
      data: ['Mock DeviceDetail', '待确认 SyncStatus', '待确认 PresetVersion'],
      events: ['device_dashboard_opened', 'sync_requested', 'device_disconnected'],
      acceptance: ['同时显示 App 与设备版本', '掉线后明确说明不可同步'],
    },
    V09: {
      purpose: '编辑八个独立 Pad 槽位并明确同步到设备',
      entry: '从 V08 的 Pad 预设卡进入',
      primaryAction: '保存 App 版本并确认覆盖设备',
      states: ['ready', 'dirty', 'saving', 'syncing', 'synced', 'error', 'offline'],
      data: ['Mock PadSlot[8]', '待确认 PadPreset', '待确认 SyncJob'],
      events: ['pad_sound_assigned', 'preset_saved', 'preset_sync_confirmed'],
      acceptance: ['固定核心按键不可编辑', '同步前显示设备和版本变化', '同步成功后版本一致'],
    },
  },
});

globalThis.HBContent = HBContent;
if (typeof module !== 'undefined') module.exports = HBContent;
