const HBContent = Object.freeze({
  meta: {
    product: 'HarBeat',
    version: '1.0',
    date: '2026-08-18',
    specFile: '2026-08-18-harbeat-mobile-app-product-design.md',
    dataLabel: '演示数据 / Mock API',
  },
  views: {
    V01: { canonical: 'H01', name: '首页', section: 'home' },
    V02: { canonical: 'M01', name: '音乐 / 推荐', section: 'music' },
    V03: { canonical: 'M01', name: '搜索 / 导入', section: 'music' },
    V04: { canonical: 'M01 子页面', name: '歌曲详情', section: 'music' },
    V05: { canonical: 'M01', name: '曲库 / 歌单', section: 'music' },
    V06: { canonical: 'D01', name: '设备列表', section: 'device' },
    V07: { canonical: 'D01 配对状态', name: '配对', section: 'device' },
    V08: { canonical: 'D01 已连接状态', name: '设备面板', section: 'device' },
    V09: { canonical: 'D02', name: 'Pad 编辑', section: 'device' },
  },
  scenarios: {
    discover: { label: '发现音乐', steps: ['V01', 'V02', 'V04', 'V05'], doneMessage: '音乐已保存到曲库' },
    import: { label: '搜索或导入', steps: ['V02', 'V03', 'V04', 'V05'], doneMessage: '导入结果已保存' },
    device: { label: '配置设备', steps: ['V06', 'V07', 'V08', 'V09', 'V08'], doneMessage: 'Pad 预设已同步' },
  },
  songs: [
    { id: 'trk-electric', title: 'Electric Motion', artist: 'Nova Circuit', style: 'Popping', bpm: 104, key: 'F minor', energy: 82, resource: 'available', accent: 'violet' },
    { id: 'trk-lock', title: 'Lock It Down', artist: 'Pocket Theory', style: 'Locking', bpm: 110, key: 'A minor', energy: 76, resource: 'available', accent: 'mint' },
    { id: 'trk-midnight', title: 'After Midnight', artist: 'Velvet Transit', style: 'Hip-Hop', bpm: 96, key: 'D minor', energy: 64, resource: 'metadata_only', accent: 'orange' },
    { id: 'trk-rubber', title: 'Rubber Frame', artist: 'Signal Arcade', style: 'Popping', bpm: 108, key: 'C minor', energy: 88, resource: 'available', accent: 'red' },
    { id: 'trk-sidewalk', title: 'Sidewalk Syntax', artist: 'Blue Basement', style: 'Hip-Hop', bpm: 92, key: 'G minor', energy: 58, resource: 'available', accent: 'blue' },
    { id: 'trk-pocket', title: 'Pocket Parade', artist: 'The Breakmakers', style: 'Locking', bpm: 114, key: 'E minor', energy: 84, resource: 'available', accent: 'acid' },
    { id: 'trk-concrete', title: 'Concrete Breeze', artist: 'Low Rise Club', style: 'House', bpm: 124, key: 'B minor', energy: 71, resource: 'unavailable', accent: 'slate' },
    { id: 'trk-echo', title: 'Echo Practice', artist: 'Mono Steps', style: 'Popping', bpm: 100, key: 'F major', energy: 54, resource: 'available', accent: 'pink' },
  ],
  playlists: [
    { id: 'pl-practice', name: '本周练习', trackIds: [] },
    { id: 'pl-battle', name: 'Battle Warm-up', trackIds: ['trk-lock'] },
    { id: 'pl-late', name: 'Late Night Cypher', trackIds: ['trk-midnight', 'trk-sidewalk'] },
  ],
  devices: [
    { id: 'rk-stage-01', name: 'HarBeat Stage 01', host: '192.168.31.88', online: true, latency: 18, presetVersion: 3 },
    { id: 'rk-practice-02', name: 'Practice Room 02', host: '192.168.31.52', online: false, latency: null, presetVersion: 1 },
  ],
  sounds: ['Air Horn', 'Crowd Up', 'Hit', 'Scratch Stop'],
  pads: Array.from({ length: 8 }, (_, index) => ({
    id: `pad-${index + 1}`,
    label: `Pad ${index + 1}`,
    sound: index < 3 ? ['Air Horn', 'Crowd Up', 'Hit'][index] : null,
  })),
  handbookSections: [
    {
      id: 'positioning',
      eyebrow: 'PRODUCT ROLE',
      title: '手机负责准备，硬件负责稳定执行',
      summary: 'HarBeat App 是音乐内容管理器、个人练习播放器、设备配置器和现场状态解释层。',
      body: '<p>正式活动中，RK3588 负责稳定出声和执行实时音频动作；App 负责找歌、整理曲库、配置 Pad、同步资源和提供备用控制。手机断开后，实体控制器仍能使用已经同步的内容。</p>',
      relatedViewIds: ['V01', 'V08'],
    },
    {
      id: 'system',
      eyebrow: 'SYSTEM OWNERSHIP',
      title: '四个部分各自承担清楚的责任',
      summary: 'App 管配置与内容，云端管账号和分析，RK3588 管现场事实，实体控制器管主要操作。',
      body: '<div class="responsibility-grid"><article><b>App</b><span>搜索、试听、曲库、歌单、Pad 编辑和状态显示</span></article><article><b>云端</b><span>账号、元数据、分析任务和个人推荐</span></article><article><b>RK3588</b><span>资源缓存、播放事实、同步版本和实时音频</span></article><article><b>实体控制器</b><span>固定核心按键与八个自定义 Pad 的现场触发</span></article></div>',
      relatedViewIds: ['V06', 'V08', 'V09'],
    },
    {
      id: 'users',
      eyebrow: 'USERS',
      title: '组织者与个人舞者共用资产，但不共用画像',
      summary: '组织者或 MC 需要准备和确认现场；个人舞者需要发现、收藏和练习。',
      body: '<p>个人推荐只学习显式舞种偏好和手机端个人行为。活动 Session 的播放、换歌和升降能量不写回个人推荐画像，避免一次活动改变长期口味。</p>',
      relatedViewIds: ['V02', 'V05'],
    },
    {
      id: 'ia',
      eyebrow: 'INFORMATION ARCHITECTURE',
      title: '四个底部 Tab，音乐内部集中完成内容任务',
      summary: '常驻导航为首页、音乐、设备、我的；正在使用是临时全屏任务，不是第五个 Tab。',
      body: '<p>音乐页内部依次提供推荐、搜索、曲库和歌单。推荐是默认分区，首页只放轻量推荐入口。设备页负责发现、配对、连接状态和 Pad 预设。</p>',
      relatedViewIds: ['V01', 'V02', 'V03', 'V05', 'V06'],
    },
    {
      id: 'journeys',
      eyebrow: 'KEY JOURNEYS',
      title: '三个原型场景都走到可验证的完成状态',
      summary: '发现并保存、搜索或导入、连接设备并同步 Pad。',
      body: '<ol><li>首页 → 推荐 → 歌曲详情 → 保存 → 曲库可见。</li><li>搜索或导入 → 匹配结果 → 保存 → 曲库可见。</li><li>设备列表 → 配对 → 设备面板 → Pad 编辑 → 确认同步 → 版本一致。</li></ol>',
      relatedViewIds: ['V01', 'V03', 'V06'],
    },
    {
      id: 'scope',
      eyebrow: 'P0 BOUNDARY',
      title: '手机独立可听歌，连接设备后才承担现场配置',
      summary: '手机独立模式支持搜索、试听、上传、曲库、歌单、推荐和练习播放。',
      body: '<p>App 不承诺专业自动 DJ、Stems 实时处理或低延迟现场音效。QQ 音乐、网易云等外部链接在 P0 只承诺元数据解析和合法资源匹配，不把未经授权的完整音频下载描述为产品能力。</p>',
      relatedViewIds: ['V03', 'V04', 'V08'],
    },
    {
      id: 'handoff',
      eyebrow: 'TEAM HANDOFF',
      title: '页面、状态和契约同时交付',
      summary: '产品给目标、流程、状态和验收；后端给对象、错误和事件；前端用 Mock 并行开发。',
      body: '<ul><li>页面必须覆盖加载、空、错误、离线和权限状态。</li><li>接口未确认时显示 Mock 或待确认标签。</li><li>Pad 先保存 App 版本，再由用户明确覆盖 RK3588。</li><li>OpenAPI、WebSocket 事件和状态枚举由前后端共同冻结。</li></ul>',
      relatedViewIds: ['V04', 'V08', 'V09'],
    },
  ],
  annotations: {
    V01: {
      purpose: '汇总最近内容、设备状态和推荐入口',
      entry: '用户完成登录或从底部导航进入首页',
      primaryAction: '进入音乐推荐或设备页面',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock HomeSummary', 'Mock DeviceSummary', 'Mock RecommendationRail'],
      events: ['home_recommendation_opened', 'home_device_opened'],
      acceptance: ['无设备时仍可进入音乐功能', '设备摘要与 D01 状态一致'],
    },
    V02: {
      purpose: '根据舞种偏好和个人行为展示推荐音乐',
      entry: '从首页推荐卡或音乐 Tab 进入',
      primaryAction: '选择歌曲并进入详情试听',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock RecommendationSection[]', 'Mock TrackSummary[]'],
      events: ['recommendation_impression', 'recommendation_track_opened'],
      acceptance: ['活动 Session 行为不写入个人画像', '每首歌曲显示舞种与 BPM'],
    },
    V03: {
      purpose: '统一处理站内搜索、外部链接和本地文件导入',
      entry: '从音乐页搜索框或导入按钮进入',
      primaryAction: '选择合法可用的匹配结果',
      states: ['idle', 'loading', 'results', 'empty', 'error', 'offline'],
      data: ['示例 SearchRequest', '示例 ImportSource', 'Mock MatchResult[]'],
      events: ['music_search_submitted', 'external_link_parsed', 'local_file_selected'],
      acceptance: ['来源始终可见', '链接解析不承诺未经授权下载', '失败原因可以区分'],
    },
    V04: {
      purpose: '展示歌曲分析、资源状态并完成试听和保存',
      entry: '从推荐、搜索结果或曲库点击歌曲',
      primaryAction: '试听并保存到曲库或歌单',
      states: ['loading', 'available', 'metadata_only', 'unavailable', 'error', 'offline'],
      data: ['Mock TrackDetail', 'Mock AudioAnalysis', '待确认 ResourceAvailability'],
      events: ['track_preview_started', 'save_sheet_opened', 'track_saved'],
      acceptance: ['展示 BPM、调性、能量与段落', '仅元数据资源不能显示为可播放完整音频'],
    },
    V05: {
      purpose: '管理个人曲库与歌单并验证保存结果',
      entry: '从音乐页分区、保存成功反馈或底部导航进入',
      primaryAction: '查看歌曲或把歌曲加入歌单',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock LibraryTrack[]', 'Mock Playlist[]'],
      events: ['library_opened', 'playlist_opened', 'playlist_track_added'],
      acceptance: ['刚保存的歌曲立即出现', '曲库与歌单状态可区分'],
    },
    V06: {
      purpose: '展示最近设备并提供手动局域网地址入口',
      entry: '从设备 Tab 或首页设备卡进入',
      primaryAction: '选择设备或输入局域网地址',
      states: ['loading', 'ready', 'empty', 'error', 'offline'],
      data: ['Mock DeviceSummary[]', '待确认 ManualHostInput'],
      events: ['device_selected', 'manual_host_submitted'],
      acceptance: ['在线和离线设备可区分', '无设备时可以手动输入地址'],
    },
    V07: {
      purpose: '用配对码确认用户正在连接目标 RK3588',
      entry: '从 V06 选择在线设备或提交地址',
      primaryAction: '提交四位配对码',
      states: ['idle', 'submitting', 'invalid_code', 'error', 'offline'],
      data: ['示例 PairingRequest', '待确认 PairingResult'],
      events: ['pairing_code_submitted', 'pairing_succeeded', 'pairing_failed'],
      acceptance: ['错误配对码不会建立连接', '目标设备名称与地址始终可见'],
    },
    V08: {
      purpose: '解释设备连接、资源和 App/设备预设版本状态',
      entry: '配对成功或进入已连接的设备 Tab',
      primaryAction: '进入 Pad 编辑或处理版本差异',
      states: ['connected', 'syncing', 'dirty', 'synced', 'error', 'offline'],
      data: ['Mock DeviceDetail', '待确认 SyncStatus', '待确认 PresetVersion'],
      events: ['device_dashboard_opened', 'sync_requested', 'device_disconnected'],
      acceptance: ['同时显示 App 与设备版本', '掉线后明确说明不可同步'],
    },
    V09: {
      purpose: '编辑八个独立 Pad 槽位并明确同步到设备',
      entry: '从 V08 的 Pad 预设卡进入',
      primaryAction: '保存 App 版本并确认覆盖设备',
      states: ['ready', 'dirty', 'saving', 'syncing', 'synced', 'error', 'offline'],
      data: ['Mock PadSlot[8]', '待确认 PadPreset', '待确认 SyncJob'],
      events: ['pad_sound_assigned', 'preset_saved', 'preset_sync_confirmed'],
      acceptance: ['固定核心按键不可编辑', '同步前显示设备和版本变化', '同步成功后版本一致'],
    },
  },
});

const contractStatuses = {
  V01: 'Mock API',
  V02: 'Mock API',
  V03: '待确认：搜索与导入 API',
  V04: '待确认：资源可用性 API',
  V05: 'Mock API',
  V06: '待确认：设备发现 API',
  V07: '待确认：RK 配对 API',
  V08: '待确认：设备状态与 WebSocket 事件',
  V09: '待确认：PadPreset 与 SyncJob',
};
for (const [viewId, contractStatus] of Object.entries(contractStatuses)) {
  HBContent.annotations[viewId].contractStatus = contractStatus;
}

globalThis.HBContent = HBContent;
if (typeof module !== 'undefined') module.exports = HBContent;
