from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.database import Base


class Session(Base):
    __tablename__ = "sessions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False, index=True)
    mode: Mapped[str] = mapped_column(String(50), nullable=False)
    start_time: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    end_time: Mapped[Optional[datetime]] = mapped_column(DateTime)


class SessionEvent(Base):
    __tablename__ = "session_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    session_id: Mapped[int] = mapped_column(ForeignKey("sessions.id"), nullable=False, index=True)
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)
    event_value: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)


class UserInteractionLog(Base):
    """用户与歌曲交互日志：播放、跳过、AB Loop、BPM调整等"""
    __tablename__ = "user_interaction_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(Integer, index=True, nullable=False)
    track_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    action_type: Mapped[str] = mapped_column(String(50), nullable=False)
    listen_mode: Mapped[str] = mapped_column(String(50), nullable=False, default="normal")
    current_dance_style: Mapped[str] = mapped_column(String(100), nullable=False, default="")
    play_duration_sec: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    completion_rate: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    skip_timestamp: Mapped[float | None] = mapped_column(Float, nullable=True)
    drum_boost_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    bpm_adjusted_to: Mapped[float | None] = mapped_column(Float, nullable=True)
    ab_loop_used: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    cue_points_added: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    rewind_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=func.now())


class RKSessionEvent(Base):
    """RK3588 edge-side session event (cypher protocol P7 SessionEvent).

    Unlike SessionEvent, session_id is TEXT (UUID, generated by RK),
    data is JSON, and rk_id identifies the device.
    """
    __tablename__ = "rk_session_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    session_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    rk_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    ts: Mapped[datetime] = mapped_column(DateTime, nullable=False, index=True)
    type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    data: Mapped[Optional[dict]] = mapped_column(JSON)
    received_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=func.now())
