FROM --platform=linux/amd64 registry-1.docker.io/library/python:3.11-slim
RUN apt-get update && apt-get install -y --no-install-recommends libsndfile1 libfftw3-single3 libyaml-0-2 && rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
COPY requirements-models.txt /tmp/models.txt
RUN pip install --no-cache-dir -r /tmp/models.txt
ENV PYTHONPATH=/workspace
ENTRYPOINT ["python"]
