import {loadJson} from './load'
import {useEffect,useMemo,useRef,useState} from 'react'
import {type Track,type planNext} from '../realtime/planner'
import {guardPlan,type GuardCatalog} from '../guarded/planner'
import {makePhrasePlanner} from './planner'
import {LiveTransport} from '../realtime/transport'
import {AudioBufferPool} from '../realtime/cache'
import MixStoryboard from '../v31/MixStoryboard'
import PhraseStory from './PhraseStory'
import logo from '../analysis/assets/harbeat-logo.png'
import '../v31/v31.css'
type Arm='old'|'fixed'|'adaptive'
type Case={a:string;b:string;position:number;mode:'section'|'phrase';paired:boolean}
type Pack={catalog:{tracks:Track[];audit:any[]};old:GuardCatalog;cases:Case[]}
const base=new URL('.',location.href),names:Record<Arm,string>={old:'V3.1 原版',fixed:'乐句保护 + 固定 EQ',adaptive:'乐句保护 + 动态 EQ'}
const download=(v:unknown,name:string)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(v,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export default function PhraseLab(){
 const [pack,setPack]=useState<Pack|null>(null),[aId,setA]=useState(''),[bId,setB]=useState(''),[position,setPosition]=useState(0),[mode,setMode]=useState<'section'|'phrase'>('section'),[arm,setArm]=useState<Arm>('fixed'),[tab,setTab]=useState<'compare'|'live'>('compare'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[,refresh]=useState(0),[feedback,setFeedback]=useState<Record<string,any>>(()=>{try{return JSON.parse(localStorage.getItem('harbeat-phrase-energy-feedback-v1')||'{}')}catch{return {}}})
 const player=useRef<LiveTransport|null>(null),playerKey=useRef(''),initPromise=useRef<Promise<void>|null>(null),pool=useRef(new AudioBufferPool()),rev=useRef(0),inspectTimer=useRef<ReturnType<typeof setTimeout>|null>(null)
 useEffect(()=>{let alive=true;Promise.all(['catalog.json','baseline.json','cases.json'].map(f=>loadJson(f,base))).then(([catalog,old,cases])=>{if(!alive)return;const first=cases.cases.find((c:Case)=>c.paired&&c.mode==='section')||cases.cases.find((c:Case)=>c.mode==='section');setPack({catalog,old,cases:cases.cases});if(first){setA(first.a);setB(first.b);setPosition(first.position);setMode(first.mode)}else{setA(catalog.tracks[0].id);setB(catalog.tracks[1].id)}}).catch(e=>setError(e.message));return()=>{alive=false;rev.current++;if(inspectTimer.current)clearTimeout(inspectTimer.current);player.current?.dispose()}},[])
 const searches=useMemo(()=>{if(!pack)return null;const a=pack.catalog.tracks.find(t=>t.id===aId),oldA=pack.old.tracks.find(t=>t.id===aId);if(!a||!oldA)return null;const args=[a,pack.catalog.tracks,position,{kind:'next' as const,targetId:bId},new Set<string>(),a.duration-position,false] as const;const fixed=makePhrasePlanner(pack.catalog.tracks,mode,'fixed')(...args);let adaptive:ReturnType<typeof planNext>;try{adaptive=makePhrasePlanner(pack.catalog.tracks,mode,'adaptive')(...args)}catch(e){adaptive={best:null,candidates:[],exclusions:[{trackId:aId,track:a.title,code:'energy_unavailable',reason:(e as Error).message,count:1}],rejected:[]}}return {old:guardPlan(pack.old,{},oldA,pack.old.tracks,position,args[3],args[4],args[5],false),fixed,adaptive}},[pack,aId,bId,position,mode])
 const activeId=player.current?.current?.id
 useEffect(()=>{if(tab==='live'&&activeId&&pack){if(aId!==activeId){setA(activeId);setPosition(0)}if(bId===activeId)setB(pack.catalog.tracks.find(t=>t.id!==activeId)!.id)}},[activeId,tab,pack,aId,bId])
 if(!pack||!searches)return <main className="v31"><h1>HarBeat · 乐句与动态 EQ</h1><p role="status">{error||'正在读取预处理证据与试听样本…'}</p></main>
 const tracks=pack.catalog.tracks,a=tracks.find(t=>t.id===aId)!,b=tracks.find(t=>t.id===bId)!,p=player.current,locked=busy||!!p?.busy,id=`${mode}|${aId}|${bId}|${position}`,execution=p?.logs.filter(e=>e.kind==='plan_scheduled').at(-1),actual=p?.pending?.plan||p?.lastPlan
 function stop(){rev.current++;if(inspectTimer.current)clearTimeout(inspectTimer.current);player.current?.stop();setBusy(false)}
 function reset(){stop();player.current?.dispose();player.current=null;playerKey.current=''}
 async function run(fn:()=>Promise<void>){const token=++rev.current;if(inspectTimer.current)clearTimeout(inspectTimer.current);setError('');setBusy(true);try{await fn()}catch(e){if(token===rev.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}finally{if(token===rev.current)setBusy(false)}}
 async function ensure(which:Arm){const key=which+'|'+mode;const token=rev.current;if(player.current&&playerKey.current===key){const t=player.current;await initPromise.current;if(token!==rev.current||player.current!==t)throw new DOMException('已取消','AbortError');return t;}player.current?.dispose();const ts=which==='old'?pack!.old.tracks:tracks;const planner:typeof planNext=which==='old'?(a,ts,pos,i,r,budget=18,ready=true)=>guardPlan(pack!.old,{},a,ts,pos,i,r,budget,ready):makePhrasePlanner(ts,mode,which);const t=new LiveTransport(ts,()=>refresh(n=>n+1),base,{planner,audioPool:pool.current,autoNext:false,prewarm:false,policyVersion:which==='old'?'protected-v31-candidate-v1':'phrase-energy-candidate-v1',noPlanMessage:'当前没有符合声学乐句、拍点和人声间距的窗口，继续播放。不会降级成提前切断。'});player.current=t;playerKey.current=key;initPromise.current=t.initialize();try{await initPromise.current}catch(e){if(player.current===t){player.current=null;playerKey.current=''}t.dispose();throw e}if(token!==rev.current||player.current!==t)throw new DOMException('已取消','AbortError');t.log('source_catalog',{version:'v32-candidate-20260924',arm:which,mode,energyStyleRanking:false,semanticPhraseConfirmed:false});return t}
 async function audition(which:Arm){const q=searches![which].best;if(!q)return;setArm(which);const t=await ensure(which);t.log('comparison_analysis',{caseId:id,mode,old:searches!.old,fixed:searches!.fixed,adaptive:searches!.adaptive,eqComparisonSamePoints:true});await t.playComparison(q,position,{experimentId:'phrase-energy-v1',arm:which==='old'?'baseline':'variant',midDb:-5,comparisonId:id+'|'+which,skipWaiting:true,horizonSec:a.duration-position})}
 async function inspect(which:Arm,trackId:string,time:number){const t=await ensure(which),token=rev.current;t.log('source_inspection',{trackId,sourceStart:time,durationSec:8,notMix:true});await t.start(trackId,time);if(token===rev.current)inspectTimer.current=setTimeout(()=>t.stop(),8000)}
 async function prepare(){const t=await ensure(arm),from=t.current||a,pos=t.current?t.position:position;const r=arm==='old'?guardPlan(pack!.old,{},from,pack!.old.tracks,pos,{kind:'next',targetId:bId},t.cache.ready,from.duration-pos,false):makePhrasePlanner(tracks,mode,arm)(from,tracks,pos,{kind:'next',targetId:bId},t.cache.ready,from.duration-pos,false);if(!r.best){t.log('preload_rejected',{position:pos,exclusions:r.exclusions});throw Error('此曲对没有可用窗口；请查看排除原因或选择预设样本')}const target=tracks.find(t=>t.id===r.best!.to)!;t.cache.protected=new Set([from.native.url,target.native.url,r.best.asset.url]);await Promise.all([from.native,target.native,r.best.asset].map(x=>t.cache.load(x)));t.log('manual_preload',{planId:r.best.id,doesNotSchedule:true});t.status='素材已就绪；实时请求时仍会重新选点'}
 const ratedPlan=tab==='live'?execution?.plan:null,ratedPosition=ratedPlan?(p?.logs.find(e=>e.kind==='request_received'&&e.requestId===execution?.requestId)?.sourcePosition??position):position,ratedMode=ratedPlan?.phrase?.mode||mode,ratedA=ratedPlan?.from||aId,ratedB=ratedPlan?.to||bId,ratingId=`${ratedMode}|${ratedA}|${ratedB}|${ratedPosition}`
 function rate(value:string){const row={preference:value,mode:ratedMode,a:ratedA,b:ratedB,position:ratedPosition,planId:ratedPlan?.id||searches![arm].best?.id,at:new Date().toISOString()};setFeedback(current=>{const merged={...current,[ratingId]:row};try{const stored=JSON.parse(localStorage.getItem('harbeat-phrase-energy-feedback-v1')||'{}');const saved={...stored,...merged};localStorage.setItem('harbeat-phrase-energy-feedback-v1',JSON.stringify(saved));return saved}catch{setError('反馈暂存在当前页面，请导出备份。旧版反馈未修改');return merged}})}
 const q=tab==='live'&&actual?actual:searches[arm].best
 return <main className="v31"><header><img src={logo} alt="HarBeat"/><div><div className="eyebrow">PHRASE · TIMING · ENERGY</div><h1>让上一句唱完，再交接。</h1><p>乐句与动态 EQ 实验版 · {tracks.length} 首原曲 · 保留 V3／V3.1</p></div><a className="old-version" href="../v31-candidate-20260923/index.html">原 V3.1 与已保存偏好 ↗</a></header>
 <nav><button aria-pressed={tab==='compare'} onClick={()=>{reset();setTab('compare')}}>① 同曲对照</button><button aria-pressed={tab==='live'} onClick={()=>{reset();setTab('live')}}>② 播放中实时接歌</button><a href="/analysis-lab?tab=mix-debug">分析平台 / 历史日志 ↗</a></nav>
 <aside className="scope">本次把“退出点合适”与“什么时候开始降低 A 音量”分开：A 保持原声至检测尾音结束，再退场。B 可以带人声进入，但首句必须在 A 尾音之后，间距最多两拍（最低 1.2 秒）。动态 EQ 只控制频段叠加，不参与选歌。声学乐句与模型段落仍待试听确认。</aside>
 <section><h2>选择同一曲对，分开比较两项改动</h2><label>预设可执行样本<select aria-label="预设可执行样本" disabled={locked} value={pack.cases.some(c=>`${c.mode}|${c.a}|${c.b}|${c.position}`===id)?id:''} onChange={e=>{const c=pack.cases.find(c=>`${c.mode}|${c.a}|${c.b}|${c.position}`===e.target.value)!;reset();setA(c.a);setB(c.b);setPosition(c.position);setMode(c.mode)}}><option value="" disabled>自选曲对</option>{pack.cases.map(c=><option key={`${c.mode}|${c.a}|${c.b}|${c.position}`} value={`${c.mode}|${c.a}|${c.b}|${c.position}`}>{tracks.find(t=>t.id===c.a)?.title} → {tracks.find(t=>t.id===c.b)?.title} · {c.mode==='section'?'段落＋乐句':'乐句完整'} · {c.paired?'含旧版对照':'旧版无窗口'}</option>)}</select></label>
 <div className="fields"><label>A<select value={aId} disabled={locked||!!p?.active} onChange={e=>{reset();setA(e.target.value);setPosition(0);if(e.target.value===bId)setB(tracks.find(t=>t.id!==e.target.value)!.id)}}>{tracks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>B<select value={bId} disabled={locked||!!p?.pending} onChange={e=>setB(e.target.value)}>{tracks.filter(t=>t.id!==aId&&t.id!==p?.current?.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>A 请求位置（秒）<input aria-label="A 请求位置" type="number" min="0" max={a.duration-1} step=".1" value={Number(position.toFixed(3))} disabled={locked||!!p?.active} onChange={e=>setPosition(Math.max(0,Math.min(a.duration-1,Number(e.target.value)||0)))}/></label></div>
 <label>完整性模式<select value={mode} disabled={locked||!!p?.active} onChange={e=>{reset();setMode(e.target.value as typeof mode)}}><option value="phrase">乐句完整：允许在完整声学乐句之后、段落内部交接</option><option value="section">段落＋乐句：还须与模型段尾相容；无窗口时不会自动放宽</option></select></label>
 <p className="quiet">预设样本筛选的是可执行条件，并非随机抽样或成功率证明。全部 20 首与未通过原因保留在下方。原 V3.1 仍用原规则选点；两种新 EQ 版本使用完全相同的新选点和增益。</p>
 {tab==='compare'?<div className="actions">{(['old','fixed','adaptive'] as const).map(m=><button key={m} aria-pressed={arm===m} disabled={locked} onClick={()=>{stop();setArm(m)}}>{names[m]} · {searches[m].best?'有计划':'无窗口'}</button>)}<button className="primary" disabled={locked||!q} onClick={()=>run(()=>audition(arm))}>试听当前版本</button></div>:<><label>实时处理版本<select value={arm} disabled={locked||!!p?.active} onChange={e=>{reset();setArm(e.target.value as Arm)}}>{(['old','fixed','adaptive'] as const).map(m=><option key={m} value={m}>{names[m]}</option>)}</select></label><div className="actions"><button disabled={locked||!!p?.active} onClick={()=>run(async()=>{const t=await ensure(arm);await t.start(aId,position)})}>播放 A</button><button disabled={locked||!!p?.pending} onClick={()=>run(prepare)}>准备下一首素材</button><button className="primary" disabled={locked||!p?.active||!!p?.pending||p.current?.id===bId} onClick={()=>run(async()=>{await p!.request({kind:'next',targetId:bId},p!.current!.duration-p!.position)})}>现在请求接歌</button><button disabled={!p?.active} onClick={()=>run(()=>p!.togglePause())}>{p?.paused?'继续':'暂停'}</button><button disabled={!p?.pending} onClick={()=>p?.cancel()}>取消待执行接歌</button></div></>}
 <div className="player-bar"><span role="status">{p?.status||'等待试听'}{p?.current?` · ${p.current.title} ${p.position.toFixed(2)}s`:''}</span><button onClick={stop}>停止</button><button disabled={!p} onClick={()=>download(p!.export(),'HarBeat-phrase-energy-session.json')}>导出完整日志</button></div>{error&&<p role="alert" className="error">{error}</p>}<p className="quiet">共用原曲和已校验的音频缓存。第一次使用新进入片段需要准备；播放混合、增益和 EQ 在浏览器实时执行。</p></section>
 <section><h2>{tab==='live'&&actual?'本次执行的计划':'试听前的计划'} · {names[arm]}</h2>{q?(q.phrase?<PhraseStory a={tracks.find(t=>t.id===q.from)!} b={tracks.find(t=>t.id===q.to)!} p={q} onInspect={(id,t)=>run(()=>inspect(arm,id,t))}/>:<MixStoryboard a={pack.old.tracks.find(t=>t.id===q.from)!} b={pack.old.tracks.find(t=>t.id===q.to)!} plan={q} position={position} onInspect={(id,t)=>run(()=>inspect('old',id,t))}/>):<div className="empty"><h3>本次没有满足条件的计划</h3><ul>{[...new Set(searches[arm].exclusions.map(x=>x.reason))].map(x=><li key={x}>{x}</li>)}</ul><p>继续当前曲。选择上方可执行样本试听，或在下方查看哪些原始边界存在冲突。</p></div>}<details><summary>全部候选与排除理由</summary><pre>{JSON.stringify(tab==='live'&&p?.lastSearch?p.lastSearch:searches[arm],null,2)}</pre></details></section>
 <section><h2>预处理到底提供了什么</h2><p>每个小节分别保存首拍、最后一拍、下一小节首拍；人声保存声学活动、保护尾音、下一句开始及原始行号。它们与原报告、母带和人声分轨指纹绑定。</p><div className="table-scroll"><table><thead><tr><th>曲目</th><th>声学乐句</th><th>可用小节</th><th>完整句尾退出点</th><th>同时匹配段尾</th><th>待确认冲突</th></tr></thead><tbody>{tracks.map(t=><tr key={t.id}><td>{t.title}</td><td>{t.alignment?.phrases.length}</td><td>{t.alignment?.bars.filter(b=>b.valid).length}</td><td>{t.alignment?.exits.length}</td><td>{t.alignment?.exits.filter(e=>e.sectionAligned).length}</td><td>{t.alignment?.conflicts.length}</td></tr>)}</tbody></table></div>{[a,b].map(t=><details key={t.id}><summary>{t.title}：查看原始段落、声学乐句、拍点、冲突记录</summary><pre>{JSON.stringify({reportId:t.reportId,sections:t.sections,alignment:t.alignment},null,2)}</pre></details>)}</section>
 <section><h2>计划与实际执行</h2>{execution?<div className="table-scroll"><table><thead><tr><th>动作</th><th>计划音频时钟</th><th>音频线程观察</th><th>偏差</th></tr></thead><tbody>{execution.events.map((e:any)=>{const o=p?.logs.find(l=>l.kind==='audio_observation'&&l.planId===e.planId&&l.name===e.name);return <tr key={e.name}><td>{e.name}</td><td>{(e.frame/p!.ctx.sampleRate).toFixed(3)}s</td><td>{o?.observedContextSec?.toFixed(3)??'未发生'}s</td><td>{o?.observationDeltaMs?.toFixed(2)??'—'} ms</td></tr>})}</tbody></table></div>:<p>开始转场后显示，包括新增的“A 尾音保护结束 / 开始退让”事件。</p>}<p className="quiet">观察点用于核对浏览器音频时钟，不代表蓝牙或扬声器输出测量。</p>{p&&<details><summary>本次全部触发与执行日志</summary><pre>{JSON.stringify(p.logs,null,2)}</pre></details>}</section>
 <section><h2>记录这组试听偏好</h2><p>{tracks.find(t=>t.id===ratedA)?.title} → {tracks.find(t=>t.id===ratedB)?.title} · 请求位置 {ratedPosition.toFixed(2)}s</p><div className="actions">{['原 V3.1 更好','乐句保护更好','动态 EQ 更好','差不多','仍有截句 / 空缺'].map(v=><button key={v} aria-pressed={feedback[ratingId]?.preference===v} onClick={()=>rate(v)}>{v}</button>)}</div><button onClick={()=>download(feedback,'HarBeat-phrase-energy-feedback.json')}>导出本轮反馈（{Object.keys(feedback).length} 组）</button><p className="quiet">本轮使用独立反馈记录；原 V3／V3.1 已保存的选择保留在原页面。</p></section>
 <footer>HarBeat · Phrase & Energy Candidate / 2026.09.24 · 当前只覆盖原 20 首最多 150 秒试听素材。没有重新训练分轨、段落或人声识别模型，尚未证明语义乐句准确率与听感提升。</footer></main>
}
