import {it,expect} from 'vitest'
import {phrasePlan} from './planner'
import type {Track} from '../realtime/planner'
function t(id:string):Track{return {id,title:id,bpm:120,duration:120,style:'Trap',styleScore:1,native:{url:id,sha256:id,duration:120,bytes:1},bars:[0,2,4,6,8,10,12,14,16,18,20],sections:[{start:0,end:16,label:'verse'}],vocals:[[1,10]],energy:[],windows:[],provenance:{masterSha256:id,reportSha256:'r',vocalSha256:'v'},reportId:'r',alignment:{schema:'harbeat.phrase_alignment.v1',status:'candidate',source:{masterSha256:id,reportSha256:'r',reportId:'r',vocalSha256:'v'},bars:Array.from({length:10},(_,i)=>({index:i,start:i*2,lastBeat:i*2+1.5,end:i*2+2,beats:[i*2,i*2+.5,i*2+1,i*2+1.5],valid:true})),phrases:[],exits:[],conflicts:[],bandFrames:[],limitations:[]}}}
function pair(){const a=t('a'),b=t('b');a.alignment!.exits=[{id:'e',cut:16,voiceEnd:14.7,tailEnd:14.8,phraseId:'p',nextVoiceStart:18,sectionEnd:15,sectionAligned:true,lastBeat:15.5,barStart:14,gridError:0,reason:'test'}];b.alignment!.phrases=[{id:'b1',start:2.9,end:9,tailEnd:9.08,nextStart:null,sectionIndex:0,sourceRows:{vad:[1],rms:[1]},semanticStatus:'unverified'}];b.windows=[{id:'w',start:0,end:4,bars:2,role:'intro',energy:0,variants:{a:{url:'entry',sha256:'entry',duration:4,bytes:1,rate:1}}}];return {a,b}}
it('allows incoming vocals after the protected tail and records the separate last beat / downbeat',()=>{const {a,b}=pair();const r=phrasePlan([a,b],'section',a,[a,b],0,{kind:'next',targetId:'b'},new Set(),40,false);expect(r.best?.start).toBe(12);expect(r.best?.phrase?.fadeStart).toBe(14.8);expect(r.best?.phrase?.incomingVocalRender).toBeCloseTo(14.9);expect(r.best?.phrase?.exit.lastBeat).toBe(15.5)})
it('rejects vocal overlap and an outgoing next phrase before the chosen exit',()=>{const {a,b}=pair();b.alignment!.phrases[0].start=2;expect(phrasePlan([a,b],'section',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull();b.alignment!.phrases[0].start=2.9;a.alignment!.exits[0].nextVoiceStart=15.9;expect(phrasePlan([a,b],'section',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull()})
it('does not silently change section mode or permit a long vocal gap',()=>{const {a,b}=pair();a.alignment!.exits[0].sectionAligned=false;expect(phrasePlan([a,b],'section',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull();expect(phrasePlan([a,b],'phrase',a,[a,b],0,{kind:'next'},new Set(),40,false).best).not.toBeNull();b.alignment!.phrases[0].start=10;expect(phrasePlan([a,b],'phrase',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull()})

it('rejects inherited windows and outgoing entry spans with missing observed beats',()=>{const {a,b}=pair();b.alignment!.bars[1].valid=false;expect(phrasePlan([a,b],'section',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull();b.alignment!.bars[1].valid=true;a.alignment!.bars[6].valid=false;expect(phrasePlan([a,b],'section',a,[a,b],0,{kind:'next'},new Set(),40,false).best).toBeNull()})
