const fs = require('fs');
const css = fs.readFileSync(process.argv[2],'utf8');
console.log('len=', css.length);
const hex = [...css.matchAll(/#[0-9a-fA-F]{3,8}\b/g)].map(m=>m[0].toLowerCase());
const freq = {};
for (const h of hex) freq[h]=(freq[h]||0)+1;
const top = Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,30);
console.log('=== top hex colors ===');
top.forEach(([c,n])=>console.log(`${n.toString().padStart(4)} ${c}`));
console.log('=== font-family ===');
[...new Set([...css.matchAll(/font-family:([^;}]+)/g)].map(m=>m[1].trim()))].forEach(f=>console.log(f));
console.log('=== @import ===');
[...css.matchAll(/@import[^;]+/g)].forEach(m=>console.log(m[0]));
console.log('=== border-radius distribution ===');
const radii = [...css.matchAll(/border-radius:([^;}]+)/g)].map(m=>m[1].trim());
const rfreq={};radii.forEach(r=>rfreq[r]=(rfreq[r]||0)+1);
Object.entries(rfreq).sort((a,b)=>b[1]-a[1]).slice(0,15).forEach(([r,n])=>console.log(`${n.toString().padStart(4)} ${r}`));
console.log('=== border (with px solid) frequency ===');
const borders = [...css.matchAll(/border:([^;}]+)/g)].map(m=>m[1].trim());
const bfreq={};borders.forEach(b=>bfreq[b]=(bfreq[b]||0)+1);
Object.entries(bfreq).sort((a,b)=>b[1]-a[1]).slice(0,15).forEach(([b,n])=>console.log(`${n.toString().padStart(4)} ${b}`));
console.log('=== background-color top ===');
const bgs = [...css.matchAll(/background-color:([^;}]+)/g)].map(m=>m[1].trim());
const bfreq2={};bgs.forEach(b=>bfreq2[b]=(bfreq2[b]||0)+1);
Object.entries(bfreq2).sort((a,b)=>b[1]-a[1]).slice(0,15).forEach(([b,n])=>console.log(`${n.toString().padStart(4)} ${b}`));
