import type {DecisionTrace} from './trace'
import './decision-trace.css'
const fmt=(x:unknown)=>typeof x==='number'&&Number.isFinite(x)?x.toFixed(3):'未记录'
const safe=(s:unknown)=>typeof s==='string'&&(s.startsWith('/')&&!s.startsWith('//')||/^https?:\/\//.test(s))?s:undefined
function TrackEvidence({track,side}:{track:DecisionTrace['a'];side:string}){
 const t=track
 return <details className="trace-source" open><summary>{side} · {t.title} · 原曲 {fmt(t.sourceWindow[0])}–{fmt(t.sourceWindow[1])} 秒</summary>
 <p>{t.binding==='verified_snapshot'?'已绑定同一报告版本与原曲指纹。':t.binding==='snapshot_mismatch'?'证据快照与本次曲目身份不一致，未关联原始行。':'旧目录缺少原始分析快照；以下只能展示当时运行输入，无法补认原始行。'}</p>
 <div className="trace-links">{t.reportId&&<a href={`/analysis-lab?report=${encodeURIComponent(t.reportId)}&tab=evidence`} target="_blank" rel="noreferrer">打开分析平台原报告 ↗</a>}{safe(t.snapshotUrl)&&<a href={safe(t.snapshotUrl)} target="_blank" rel="noreferrer">本次固定版本分析快照 ↗</a>}</div>
 <h4>段落：预处理原始行 → 运行时段落</h4><div className="trace-scroll"><table><thead><tr><th>运行时段落</th><th>对应原报告行与起止秒</th><th>识别置信度</th></tr></thead><tbody>{t.sections.map(s=><tr key={s.runtimeRow}><td>第 {s.runtimeRow} 行 · {s.label}<br/>{fmt(s.start)}–{fmt(s.end)}</td><td>{s.sourceRows.length?s.sourceRows.map(r=><div key={r.row}>第 {r.row} 行 · {r.label} · {fmt(r.start_ms/1000)}–{fmt(r.end_ms/1000)}<br/><code>{r.path}</code></div>):'缺少可核对的原始行'}</td><td>{s.sourceRows.map(r=><div key={r.row}>第 {r.row} 行：{r.confidence==null?'模型未提供':fmt(r.confidence)}</div>)}</td></tr>)}</tbody></table></div>
 <h4>拍网格与实际选点</h4><div className="trace-scroll"><table><thead><tr><th>实际选点（原曲秒）</th><th>最近运行网格</th><th>原始依据</th></tr></thead><tbody>{t.cues.map(c=><tr key={c.name}><td>{c.name} · {fmt(c.sec)}</td><td>{fmt(c.nearest?.sec)} · 偏差 {fmt((c.nearest?.distanceSec??NaN)*1000)} ms</td><td>{c.gridBasis}{c.sourceRow?` · 小节候选第 ${c.sourceRow} 行`:c.beatRow?` · 拍点第 ${c.beatRow} 行`:''}<br/><code>{c.path}</code></td></tr>)}</tbody></table></div>
 <h4>人声区间与占比计算</h4><p>{t.vocals.available?`本窗口扩展后人声覆盖 ${fmt(t.vocals.unionSec)} 秒，占 ${fmt((t.vocals.fraction??0)*100)}%；精确接管/退出点${t.vocals.activeAtCut?'仍在':'不在'}未扩展人声区间内。`:'人声区间缺失，不能视为无人声。'}{t.vocals.probabilityReason}</p>
 {t.vocals.nextInterval&&<p>从退出／接管点往后，下一条仍有效的人声检测区间为 {fmt(t.vocals.nextInterval.start)}–{fmt(t.vocals.nextInterval.end)} 秒（运行输入第 {t.vocals.nextInterval.runtimeRow} 行）；它是活动检测区间，不是已确认的歌词句子。</p>}<p>每段两侧各扩展 0.3 秒，裁剪到本窗口，再合并重叠区间；V3 占比门槛 5%、持续门槛 0.5 秒。保护版使用方式见上方表格。</p>
 <div className="trace-scroll"><table><thead><tr><th>原报告人声行</th><th>原始起止（秒）</th><th>扩展后（秒）</th><th>窗口内实际参与计算（秒）</th></tr></thead><tbody>{t.vocals.rows.map(r=><tr key={r.runtimeRow}><td>{r.sourceRow?`第 ${r.sourceRow} 行`:`仅运行输入第 ${r.runtimeRow} 行`}<br/><code>{r.path}</code></td><td>{r.raw.map(fmt).join('–')}</td><td>{r.padded.map(fmt).join('–')}</td><td>{r.clipped.map(fmt).join('–')}</td></tr>)}</tbody></table></div>{!t.vocals.rows.length&&<p>没有与这个窗口相交的扩展人声区间。</p>}
 {t.acoustic&&<><h4>保护版实际使用的分离人声能量</h4><p>低活动间隙 {fmt(t.acoustic.evidence.quietStart)}–{fmt(t.acoustic.evidence.quietEnd)} 秒；记录最大值 {fmt(t.acoustic.evidence.maxRmsDbfs)} dBFS，门槛 {fmt(t.acoustic.evidence.thresholdDbfs)} dBFS。{t.acoustic.note}</p><details><summary>查看该间隙的 {t.acoustic.rows.length} 条原始测量帧</summary><div className="trace-scroll"><table><thead><tr><th>原报告行</th><th>原曲秒</th><th>RMS dBFS</th></tr></thead><tbody>{t.acoustic.rows.map(r=><tr key={r.row}><td>{r.row}<br/><code>{r.path}</code></td><td>{fmt(r.start)}–{fmt(r.end)}</td><td>{fmt(r.rms_dbfs)}</td></tr>)}</tbody></table></div></details></>}
 <details><summary>模型、BPM、风格原分数、已分析模块与版本指纹</summary><pre>{JSON.stringify({tempo:t.sourceTempo,runtime:t.runtime,genre:t.sourceGenre,vocalModel:t.vocals.model,vocalSource:t.vocals.source,acousticSource:t.acoustic?{asset:t.acoustic.sourceAsset,algorithm:t.acoustic.sourceAlgorithm}:null,extensions:t.availableExtensions,reportId:t.reportId,reportSha256:t.reportSha256,masterSha256:t.masterSha256},null,2)}</pre></details></details>
}
export default function DecisionTracePanel({trace}:{trace?:DecisionTrace|null}){
 if(!trace)return <p className="decision-trace">这份旧记录没有逐行证据快照；保留原有决策 JSON，不能用今天的分析结果补认当时使用的数据。请在证据联通版重新试听并记录。</p>
 return <section className="decision-trace" aria-label="预处理到混音的证据链"><h3>预处理 → 选点 → 音频执行</h3><p>模式：{trace.mode==='v3-ranking'?'V3 普通选点':trace.mode==='protected-auto'?'自动声学保护':'人工核验保护'}。本表对应这一份计划；排名和落选原因在同次请求的候选表中。</p>
 <div className="trace-scroll"><table><thead><tr><th>预处理信息</th><th>这一次实际怎么用</th></tr></thead><tbody>{trace.features.map(f=><tr key={f.key}><td>{f.name}<br/><code>{f.source}</code></td><td>{f.effect}</td></tr>)}</tbody></table></div>
 <h4>混音处理与听感排查</h4><p>{trace.strategy.reason}。没有比较多种混音算法后择优。</p><ul>{trace.strategy.facts.map(f=><li key={f}>{f}</li>)}</ul><p>{trace.strategy.interpretation}</p>
 <TrackEvidence track={trace.a} side="A 当前歌"/><TrackEvidence track={trace.b} side="B 下一首"/>
 <h4>实际播放素材</h4><p>变速素材的目标时长：{trace.material.tempoPreparation?`${trace.material.tempoPreparation.bars} × 240 ÷ ${trace.material.tempoPreparation.aBpm} = ${fmt(trace.material.tempoPreparation.nominalTargetSec)} 秒；窗口原长 ÷ 目标时长 = ${fmt(trace.material.tempoPreparation.derivedRate)} 倍速。实际片段时长还受采样帧取整影响。`:"旧日志未保存素材时长推导。"}</p><p>进入素材类型：{trace.material.lane}；B 进入片段来自原曲 {fmt(trace.material.sourceMapping.bStart)}–{fmt(trace.material.sourceMapping.bEnd)} 秒，以 {fmt(trace.material.sourceMapping.rate)} 倍速播放 {fmt(trace.material.sourceMapping.overlapSec)} 秒后，接回原曲正文。</p><div className="trace-scroll"><table><thead><tr><th>播放角色</th><th>实际文件与指纹</th></tr></thead><tbody>{[["A 原曲",trace.material.a],["B 正文",trace.material.b],["B 变速进入片段",trace.material.entry]].map(([label,asset]:any)=><tr key={label}><td>{label}</td><td><code>{asset.url}</code><br/><code>{asset.sha256}</code></td></tr>)}</tbody></table></div><details><summary>实际播放什么素材、如何从进入片段接回正文</summary><p>A、B 原曲和变速进入素材各自记录文件指纹；不把分轨分析来源误当成实际播放分轨。</p><pre>{JSON.stringify(trace.material,null,2)}</pre></details>
 {trace.protection&&<details><summary>保护规则的全部放行证据（含自动／人工来源）</summary><pre>{JSON.stringify(trace.protection,null,2)}</pre></details>}
 </section>
}
