import {describe,it,expect} from 'vitest'
import {evaluateEvidence} from './evidence'
import type {Track,Window} from './planner'
const frame=(start:number,end:number,dbfs:number|null)=>({start,end,dbfs,coverage:1,status:dbfs===null?'missing':'measured'})
function make(id:string,db:number):Track {return {id,title:id,bpm:100,duration:120,style:'Trap',styleScore:.9,native:{url:id,sha256:id,duration:120,bytes:1},bars:[],sections:[],vocals:[],energy:[],windows:[],mixProfile:{schema:'harbeat.mix_profiles.v1',policy:{calibrationId:'master-rms-common-digital-full-scale-v1',energyUnit:'dBFS_RMS'},source:{masterSha256:id},energyCurve:[],energyFrames:[frame(0,120,db)],sections:[],windows:[]},provenance:{masterSha256:id}} as Track}
const w={id:'w',start:0,end:8,bars:4,role:'intro',energy:.9,variants:{}} as Window
function local(b:Track,status='model_candidate',style='Trap') {b.mixProfile!.windows=[{id:'w',entry:{start:0,end:8,style:{status:'needs_review',top:[],reasons:['short_context']}},takeover:{start:8,end:24,style:{status,top:[{style,score:.4}],reasons:[]}},sustain:[]}] as any}
describe('candidate-specific joint evidence',()=>{
 it('compares actual A exit candidate, not button time or song-relative energy',()=>{const a=make('a',-16),b=make('b',-12);a.mixProfile!.energyFrames=[frame(0,20,-16),frame(20,120,-8)];expect(evaluateEvidence(a,b,w,16,{kind:'up'}).accepted).toBe(true);expect(evaluateEvidence(a,b,w,28,{kind:'up'}).accepted).toBe(false)})
 it('fails closed for stale profiles that only carry a coarse display curve',()=>{const a=make('a',-16),b=make('b',-12);b.mixProfile!.energyCurve=b.mixProfile!.energyFrames!;delete b.mixProfile!.energyFrames;expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('energy_missing');expect(evaluateEvidence(a,b,w,16,{kind:'next'}).accepted).toBe(true)})
 it('does not smear a transient outside the selected interval into it',()=>{const a=make('a',-17.908),b=make('b',-18);a.mixProfile!.energyFrames=[frame(0,.2,-20),frame(.2,.25,0),frame(.25,120,-20)];const result=evaluateEvidence(a,b,w,4.25,{kind:'up'});expect(result.accepted).toBe(true);expect(result.deltasDb[0]).toBeCloseTo(2)})
 it('rejects an initial rise followed by an energy collapse',()=>{const a=make('a',-16),b=make('b',-12);b.mixProfile!.energyFrames=[frame(0,12,-10),frame(12,120,-20)];expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('energy_not_sustained')})
 it('jointly filters local style and energy and permits an uncertain intro',()=>{const a=make('a',-16),b=make('b',-12);local(b);expect(evaluateEvidence(a,b,w,16,{kind:'up',style:'Trap'}).accepted).toBe(true);expect(evaluateEvidence(a,b,w,16,{kind:'up',style:'Grime'}).code).toBe('local_style_mismatch');local(b,'needs_review');expect(evaluateEvidence(a,b,w,16,{kind:'up',style:'Trap'}).code).toBe('local_style_pending')})
 it('never substitutes missing energy or global style for local evidence',()=>{const a=make('a',-16),b=make('b',-12);delete b.mixProfile;expect(evaluateEvidence(a,b,w,16,{kind:'up'}).accepted).toBe(false);expect(evaluateEvidence(a,b,w,16,{kind:'style',style:'Trap'}).accepted).toBe(false);expect(evaluateEvidence(a,b,w,16,{kind:'next'}).accepted).toBe(true)})
 it('rejects partial coverage, wrong identities, mismatched calibration and excessive jumps',()=>{const a=make('a',-16),b=make('b',-12);b.mixProfile!.energyFrames=[frame(8,10,-12)];expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('energy_missing');b.mixProfile={...b.mixProfile!,energyFrames:[frame(0,120,-2)]};expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('energy_jump');b.mixProfile!.source.masterSha256='wrong';expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('profile_identity');b.mixProfile!.source.masterSha256='b';b.mixProfile!.policy.calibrationId='other';expect(evaluateEvidence(a,b,w,16,{kind:'up'}).code).toBe('energy_calibration')})
})
