import {useEffect,useRef,useState} from 'react'
import {LiveTransport} from './transport'
import {Track,Intent} from './planner'
import logo from '../analysis/assets/harbeat-logo.png'
import './realtime.css'
const time=(n:number)=>`${Math.floor(Math.max(0,n)/60)}:${(Math.max(0,n)%60).toFixed(1).padStart(4,'0')}`
export default function RealtimeLab(){
 const [catalog,setCatalog]=useState<any>(null),[error,setError]=useState(''),[selected,setSelected]=useState(''),[target,setTarget]=useState(''),[style,setStyle]=useState('Trap'),[budget,setBudget]=useState(18),[version,refresh]=useState(0),[initializing,setInitializing]=useState(false)
 const player=useRef<LiveTransport|null>(null);const base=new URL('.',window.location.href)
 useEffect(()=>{let alive=true;fetch(new URL('catalog.json',base)).then(r=>{if(!r.ok)throw new Error('素材目录读取失败');return r.json()}).then(x=>{if(alive){setCatalog(x);setSelected((x.tracks.find((t:Track)=>t.title==='Big Girls')||x.tracks[0]).id)}}).catch(e=>setError(e.message));return()=>{alive=false;player.current?.dispose()}},[])
 const p=player.current;const current=p?.current;const pending=p?.pending;const position=p?.position||0;const tracks:Track[]=catalog?.tracks||[]
 async function getPlayer(){if(player.current)return player.current;const live=new LiveTransport(tracks,()=>refresh(v=>v+1),base);player.current=live;try{await live.initialize();return live}catch(e){live.dispose();player.current=null;throw e}}
 async function start(){setError('');setInitializing(true);try{const live=await getPlayer();await live.start(selected)}catch(e){setError((e as Error).message)}finally{setInitializing(false)}}
 async function request(intent:Intent){setError('');try{await p?.request(intent,budget)}catch(e){setError((e as Error).message)}}
 function download(){if(!p)return;const url=URL.createObjectURL(new Blob([JSON.stringify(p.export(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='HarBeat-V3-Live-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const events=p?.logs.filter(x=>x.kind==='audio_observation').slice(-12)||[];const latest=p?.logs.filter(x=>x.kind==='plan_scheduled').at(-1);const plan=p?.lastPlan;const next=tracks.find(t=>t.id===pending?.plan.to)
 return <main className="live-shell" data-revision={version}>
  <header className="live-header"><a className="live-brand" href="/analysis-lab"><img src={logo}/><span>HarBeat<small>LIVE MIX LAB</small></span></a><a href="/analysis-lab">返回分析平台 ↗</a></header>
  <section className="live-intro"><div><span className="live-eyebrow">V3 · REALTIME PREVIEW 0.1</span><h1>你决定方向，<br/>音乐在下一处交接。</h1><p>边听边换歌、调整能量或切换 Trap／Grime。系统从原始小节网格选窗口，在浏览器实时执行 EQ 和淡化。</p></div><aside><b>实时发生的部分</b><p>选歌 · 选点 · EQ · 双路叠加</p><small>保调变速素材提前准备。这里没有播放预先混好的整场音频；浏览器 DSP 并非原 FFmpeg 的逐样本复现。</small></aside></section>
  {error&&<div role="alert" className="live-error">{error}</div>}
  {!catalog?<p>正在读取六首演示曲目…</p>:<>
  <section className="live-console">
   <div className="live-deck"><div className="live-eyebrow">正在播放 / A</div><h2>{current?.title||'先选一首开始试听'}</h2><p>{current?`${current.bpm} BPM · 模型候选 ${current.style}`:'六首已有分析的 Hip-Hop 曲目，每首最多前 150 秒'}</p><div className="live-timing"><strong>{time(position)}</strong><span>/ {time(current?.duration||0)}</span><span className="live-phase">{pending?(p!.ctx.currentTime>=pending.start?'正在交接':'等待进歌'):p?.paused?'已暂停':p?.playing?'播放中':'待播放'}</span></div>
   <input aria-label="播放位置" type="range" min="0" max={current?.duration||1} step=".1" value={position} disabled={!current||!!pending||p?.busy} onChange={e=>{void p?.seek(Number(e.target.value)).catch(e=>setError(e.message))}}/>
   <div className="live-markers">{current?.sections.filter(s=>s.start<current.duration).map((s,i)=><button key={i} disabled={!!pending||p?.busy} onClick={()=>void p?.seek(s.start).catch(e=>setError(e.message))}>{s.label} <small>{time(s.start)}</small></button>)}</div>
   <div className="live-playrow"><button disabled={!current} onClick={()=>void p?.togglePause().catch(e=>setError(e.message))}>{p?.paused?'继续播放':'暂停'}</button><button disabled={!current&&!p?.busy} onClick={()=>p?.stop()}>停止</button><label>输出音量<input aria-label="输出音量" type="range" min="0" max="1" defaultValue=".85" step=".01" onChange={e=>p?.setVolume(Number(e.target.value))}/></label></div>
   </div>
   <div className="live-controls"><label>开始歌曲<select aria-label="开始歌曲" value={selected} onChange={e=>setSelected(e.target.value)}>{tracks.map(t=><option value={t.id} key={t.id}>{t.title} · {t.style}</option>)}</select></label><button className="live-primary" disabled={initializing} onClick={start}>{initializing?'正在准备…':current?'重新从所选歌曲开始':'开始实时试听'}</button>
    <label>从点击到交接完成的等待预算<select aria-label="等待预算" value={budget} onChange={e=>setBudget(Number(e.target.value))}><option value="10">快速 · 最多 10 秒</option><option value="18">平衡 · 最多 18 秒</option><option value="30">完整 · 最多 30 秒</option></select></label>
    <div className="live-actiongrid"><button disabled={!p?.playing} onClick={()=>void request({kind:'next'})}>下一首 ↗</button><button disabled={!p?.playing} onClick={()=>void request({kind:'up'})}>能量提高 ↑</button><button disabled={!p?.playing} onClick={()=>void request({kind:'down'})}>能量降低 ↓</button></div>
    <div className="live-inline"><select aria-label="目标风格" value={style} onChange={e=>setStyle(e.target.value)}><option>Trap</option><option>Grime</option></select><button disabled={!p?.playing} onClick={()=>void request({kind:'style',style})}>切换风格</button></div>
    <div className="live-inline"><select aria-label="指定下一首" value={target} onChange={e=>setTarget(e.target.value)}><option value="">指定下一首…</option>{tracks.filter(t=>t.id!==current?.id).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button disabled={!p?.playing||!target} onClick={()=>void request({kind:'next',targetId:target})}>按窗口接入</button></div>
   </div>
  </section>
  <div role="status" className="live-status"><span className={p?.playing?'live-dot active':'live-dot'}/><span>{p?.status||'首次读取歌曲需要准备；开始后会提前准备少量候选。'}{pending&&<b> · {next?.title}：{Math.max(0,pending.start-p!.ctx.currentTime).toFixed(1)} 秒后混入，{Math.max(0,pending.end-p!.ctx.currentTime).toFixed(1)} 秒后接管</b>}</span><small>音频缓存 {p?.cache.sizeMB||0} MB</small>{(pending||p?.busy)&&<button onClick={()=>p?.cancel()}>取消待执行请求</button>}</div>
  <section className="live-review"><div className="live-sectiontop"><div><span className="live-eyebrow">PLAN → AUDIO CLOCK</span><h2>下一次交接为什么这样做</h2></div><button disabled={!p?.logs.length} onClick={download}>导出全部日志 ↓</button></div>
   {!plan?<p className="live-muted">播放后点击“下一首”，这里会显示目标窗口、人声依据、速度映射和实际音频线程记录。没有合适方案时会继续播放当前歌曲。</p>:<><div className="live-facts"><div><small>进入歌曲</small><b>{tracks.find(t=>t.id===plan.to)?.title}</b></div><div><small>A 混入 → 退出</small><b>{time(plan.start)} → {time(plan.end)}</b></div><div><small>B 进入窗口</small><b>{time(plan.window.start)} → {time(plan.window.end)}</b></div><div><small>转场与速度</small><b>{plan.window.bars} 小节 / ×{plan.rate.toFixed(3)}</b></div><div><small>人声窗口占比 A / B</small><b>{(plan.aVocal*100).toFixed(0)}% / {(plan.bVocal*100).toFixed(0)}%</b></div><div><small>B 中频</small><b>{plan.midDuck?'−5 dB → 0 dB':'不触发人声衰减'}</b></div></div><p>{plan.reason}。A 开始位置距原始首拍 {(plan.gridError*1000).toFixed(0)} ms；B 交接后从 {time(plan.window.end)} 恢复原速。</p><p className="live-muted">固定规则：A 低频 −9 dB，B 低频 −7 dB；B 最后半小节由滤波声恢复原声。模型边界未人工确认；能量按钮使用原有局部曲线作候选比较。</p></>}
   <div className="live-tablewrap"><table><thead><tr><th>交接 / 事件</th><th>计划时间*</th><th>音频线程记录*</th><th>观察偏差</th></tr></thead><tbody>{events.length?events.map((e,i)=><tr key={i}><td><small>{(()=>{const record=p?.logs.find(x=>x.kind==='plan_scheduled'&&x.planId===e.planId);return record?tracks.find(t=>t.id===record.plan.from)?.title+' → '+tracks.find(t=>t.id===record.plan.to)?.title:''})()}</small><br/>{e.name}</td><td>{e.plannedContextSec.toFixed(3)} s</td><td>{e.observedContextSec.toFixed(3)} s</td><td>{e.observationDeltaMs.toFixed(2)} ms</td></tr>):<tr><td colSpan={4}>交接执行后显示音频线程记录。</td></tr>}</tbody></table></div><small className="live-muted">* 这里使用同一个 AudioContext 时钟。记录分辨率为一个音频处理块，保护限幅另增加约 5 ms；没有测量扬声器或蓝牙实际出声时间，也不以回调到达界面的时间冒充出声时间。</small>
   {p?.lastSearch&&<details><summary>查看候选与排除原因</summary><ul>{p.lastSearch.rejected.map((r:any,i:number)=><li key={i}>{r.track}：{r.reason}</li>)}</ul><div className="live-tablewrap"><table><thead><tr><th>候选歌曲</th><th>完成点</th><th>窗口</th><th>规则分</th></tr></thead><tbody>{p.lastSearch.candidates.slice(0,10).map((x:any)=><tr key={x.id}><td>{tracks.find(t=>t.id===x.to)?.title}</td><td>{time(x.end)}</td><td>{x.window.bars} 小节</td><td>{x.score.toFixed(3)}</td></tr>)}</tbody></table></div></details>}
   <details><summary>本次操作记录（{p?.logs.length||0} 条）</summary><ol className="live-logs">{p?.logs.slice(-30).reverse().map((e,i)=><li key={i}><code>{e.contextSec.toFixed(2)} s</code><b>{e.kind}</b><span>{e.message||e.intent?.kind||e.name||e.to||''}</span></li>)}</ol></details>
  </section>
  <footer><b>这是浏览器实时原型，尚未集成原生 App。</b><p>普通请求可在锁定前修改；开始交接后仅保存最新请求，完成后处理。暂停会暂停整个音频时钟。iOS／Android 锁屏、后台与蓝牙链路需要在对应真机另行验收。</p><details><summary>素材与能力边界</summary><ul>{catalog.limitations.map((s:string)=><li key={s}>{s}</li>)}</ul><a href="catalog.json" download>下载素材与预处理依据</a></details></footer>
  </>}
 </main>
}
