import {describe,it,expect} from 'vitest'
import {buildDecisionTrace} from './trace'
import {planNext,type Track} from './planner'
const track=(id:string):Track=>({id,title:id,bpm:120,style:'House',styleScore:.4,duration:90,native:{url:id,sha256:id,duration:90,bytes:1},bars:[0,2,4,6,8,10,12,14,16,18,20,22],sections:[{start:0,end:16,label:'verse'}],vocals:[[1,3],[3.2,5]],energy:[],windows:[],reportId:id,provenance:{masterSha256:id,reportSha256:'hash'},preprocessing:{schema:'harbeat.preprocessing-evidence.v1',reportId:id,reportSha256:'hash',masterSha256:id,reportSnapshotUrl:'evidence/'+id+'.json',sections:{source:'songformer',items:[{start_ms:0,end_ms:8000,label:'verse'},{start_ms:8000,end_ms:16000,label:'verse'}]},beatGrid:{bars_ms:[0,2000,4000,6000,8000,10000,12000,14000,16000,18000,20000,22000],beats_ms:[]},tempo:{bpm:120},vocalActivity:{intervals:[{start_ms:1000,end_ms:3000},{start_ms:3200,end_ms:5000}],producer:{model:'silero_vad',parameters:{threshold:.5}}},energy:{},extensions:[],genre:{},vocalRms:{points:[]},bindingChecks:{reportHash:true,masterHash:true}}})
function fixture(){const a=track('a'),b=track('b');b.windows=[{id:'w',start:0,end:8,bars:4,role:'verse',energy:0,variants:{a:{url:'head',sha256:'head',bytes:1,duration:8,rate:1}}}];return {a,b,p:{...planNext(a,[a,b],0,{kind:'next',targetId:'b'},new Set(),18,false).best!,start:0,end:8,aVocal:4.6/8}}}
describe('preprocessing decision bridge',()=>{
 it('maps merged runtime sections to all original rows and unions padded vocals without claiming probability',()=>{const {a,b,p}=fixture();const t=buildDecisionTrace(a,b,p);expect(t.a.sections[0].sourceRows.map(x=>x.row)).toEqual([1,2]);expect(t.a.vocals.rows.map(x=>x.sourceRow)).toEqual([1,2]);expect(t.a.vocals.unionSec).toBeCloseTo(4.6);expect(t.a.vocals.modelProbability).toBeNull();expect(t.a.vocals.fraction).toBeCloseTo(p.aVocal);expect(t.strategy.multipleAlgorithmsCompared).toBe(false)})
 it('never mutates decision inputs or changes planning and handles old catalog evidence missing',()=>{const {a,b,p}=fixture(),before=JSON.stringify({a,b,p});buildDecisionTrace(a,b,p);expect(JSON.stringify({a,b,p})).toBe(before);delete a.preprocessing;const t=buildDecisionTrace(a,b,p);expect(t.a.binding).toBe('missing_snapshot');expect(t.a.sections[0].sourceRows).toEqual([]);expect(t.a.vocals.rows[0].sourceRow).toBeNull()})
 it('refuses mismatched snapshot identity',()=>{const {a,b,p}=fixture();a.preprocessing!.masterSha256='other';const t=buildDecisionTrace(a,b,p);expect(t.a.binding).toBe('snapshot_mismatch');expect(t.a.sections[0].sourceRows).toEqual([])})
 it('distinguishes automatic protection from original vocal score and records actual EQ override',()=>{const {a,b,p}=fixture();(p as any).protection={exit:{sectionEnd:7,cut:8},automaticExit:{quietStart:7.9,quietEnd:8.2,thresholdDbfs:-32,maxRmsDbfs:-36},entry:{lane:'original_silent'},sectionTailDelaySec:1};p.midDuck=false;const t=buildDecisionTrace(a,b,p,-8);expect(t.mode).toBe('protected-auto');expect(t.strategy.actualBMidDb).toBe(0);expect(t.features.find(x=>x.key==='vocals')?.effect).toContain('硬约束');expect(t.protection).toEqual((p as any).protection)})
})
