import {AudioCache} from './cache'
import {planNext,RequestGate,Track,Intent,Plan} from './planner'
export type Log=Record<string,any>
type Deck={track:Track;sources:AudioBufferSourceNode[];nodes:AudioNode[];gain:GainNode;dry:GainNode;wet:GainNode;low:BiquadFilterNode;high:BiquadFilterNode;mid:BiquadFilterNode;at:number;offset:number;headEnd?:number;bodyOffset?:number;rate?:number}
type Pending={plan:Plan;deck:Deck;start:number;end:number;id:string;committed:boolean}
export class LiveTransport{
 ctx:AudioContext;cache:AudioCache;gate=new RequestGate();logs:Log[]=[];active:Deck|null=null;pending:Pending|null=null;status='选择歌曲后开始播放';lastPlan:Plan|null=null;lastSearch:any=null;paused=false;busy=false;private monitor!:AudioWorkletNode;private volume:GainNode;private timer:number;private starting=0;private autoTried=false;private base:URL;private dead=false;private deferredDeadline=0
 constructor(public tracks:Track[],private update:()=>void,base:URL){this.base=base;this.ctx=new AudioContext({sampleRate:44100,latencyHint:'interactive'});this.volume=this.ctx.createGain();this.volume.gain.value=.85;this.volume.connect(this.ctx.destination);this.cache=new AudioCache(this.ctx,base,s=>{if(this.busy||!this.active){this.status=s;this.update()}});this.timer=window.setInterval(()=>this.tick(),80);this.ctx.onstatechange=()=>{this.log('context_state',{state:this.ctx.state});this.update()}}
 async initialize(){await this.ctx.audioWorklet.addModule(new URL('v3-clock.js',this.base));this.monitor=new AudioWorkletNode(this.ctx,'v3-clock',{outputChannelCount:[2]});this.monitor.connect(this.volume);this.monitor.port.onmessage=({data})=>{this.log('audio_observation',{...data,plannedContextSec:data.frame/this.ctx.sampleRate,observedContextSec:data.observedFrame/this.ctx.sampleRate,observationDeltaMs:(data.observedFrame-data.frame)/this.ctx.sampleRate*1000,messageReceivedContextSec:this.ctx.currentTime,basis:'Audio-thread render quantum observation; not measured source onset, device output or Bluetooth latency'});this.sync();this.update()}}
 log(kind:string,data:Log={}){this.logs.push({kind,wallTime:new Date().toISOString(),contextSec:this.ctx.currentTime,...data});if(this.logs.length>1500)this.logs.shift()}
 get position(){if(!this.active)return 0;return Math.min(this.active.track.duration,this.active.offset+Math.max(0,this.ctx.currentTime-this.active.at))}
 get current(){return this.active?.track||null}
 get playing(){return !!this.active&&!this.paused&&this.ctx.state==='running'}
 setVolume(value:number){this.volume.gain.setTargetAtTime(Math.max(0,Math.min(1,value)),this.ctx.currentTime,.015)}
 private hold(p:AudioParam,value:number){const now=this.ctx.currentTime;if(p.cancelAndHoldAtTime)p.cancelAndHoldAtTime(now);else p.cancelScheduledValues(now);p.linearRampToValueAtTime(value,now+.02)}
 private graph(track:Track,at:number,offset:number):Deck{
  const input=this.ctx.createGain(),low=this.ctx.createBiquadFilter(),high=this.ctx.createBiquadFilter(),mid=this.ctx.createBiquadFilter(),wet=this.ctx.createGain(),dry=this.ctx.createGain(),gain=this.ctx.createGain()
  low.type='lowshelf';low.frequency.value=140;high.type='highshelf';high.frequency.value=3600;mid.type='peaking';mid.frequency.value=1200;mid.Q.value=1.05
  input.connect(low);low.connect(high);high.connect(mid);mid.connect(wet);input.connect(dry);wet.connect(gain);dry.connect(gain);gain.connect(this.monitor);wet.gain.value=0;dry.gain.value=1;gain.gain.value=.76
  return {track,sources:[],nodes:[input,low,high,mid,wet,dry,gain],gain,wet,dry,low,high,mid,at,offset}
 }
 private source(d:Deck,buffer:AudioBuffer,at:number,offset:number,until?:number,edge=false){const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=buffer;s.connect(g);g.connect(d.nodes[0]);s.start(at,offset);if(until){g.gain.setValueAtTime(1,Math.max(at,until-.004));g.gain.linearRampToValueAtTime(0,until);s.stop(until)}else if(edge){g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(1,at+.004)}d.sources.push(s);d.nodes.push(g)}
 private retire(d:Deck,fade=true){const now=this.ctx.currentTime;if(fade)this.hold(d.gain.gain,0);for(const s of d.sources){try{s.stop(now+(fade?.025:0))}catch{}}setTimeout(()=>d.nodes.forEach(n=>{try{n.disconnect()}catch{}}),80)}
 private protected(){this.cache.protected=new Set([this.active?.track.native.url,this.pending?.deck.track.native.url,this.pending?.plan.asset.url].filter(Boolean) as string[])}
 async start(id:string,offset=0){const token=++this.starting;this.stop(false);this.busy=true;this.status='正在准备原曲…';this.update();await this.ctx.resume();const t=this.tracks.find(t=>t.id===id);if(!t)throw new Error('歌曲不存在');try{this.cache.protected=new Set([t.native.url]);const buffer=await this.cache.load(t.native);if(token!==this.starting||this.dead)return;const at=this.ctx.currentTime+.08;this.active=this.graph(t,at,Math.max(0,Math.min(t.duration-1,offset)));this.source(this.active,buffer,at,this.active.offset);this.active.gain.gain.setValueAtTime(0,at);this.active.gain.gain.linearRampToValueAtTime(.76,at+.02);this.paused=false;this.status='正在播放';this.autoTried=false;this.log('track_start',{track:t.id,sourceOffset:this.active.offset,scheduledAt:at,assetSha256:t.native.sha256});this.protected();}finally{if(token===this.starting){this.busy=false;this.update();if(this.active)void this.prewarm()}}}
 stop(invalidate=true){if(invalidate)this.starting++;this.gate.reset();if(this.pending)this.retire(this.pending.deck);if(this.active)this.retire(this.active);this.pending=null;this.active=null;this.busy=false;this.paused=false;this.autoTried=false;this.monitor?.port.postMessage({kind:'clear'});this.cache.protected.clear();this.status='已停止';this.log('stop');this.update()}
 async togglePause(){if(!this.active)return;if(this.paused){await this.ctx.resume();this.paused=false;this.status='继续播放'}else{await this.ctx.suspend();this.paused=true;this.status='已暂停，交接时钟同时暂停'}this.log('pause',{paused:this.paused});this.update()}
 async seek(position:number){if(!this.active)return;const id=this.active.track.id;this.log('seek',{position});await this.start(id,position)}
 private sync(){const p=this.pending;if(!p)return;const now=this.ctx.currentTime;if(now>=p.start-.15)this.gate.locked=true;if(now>=p.end){const old=this.active;this.active=p.deck;this.active.at=p.end;this.active.offset=p.plan.window.end;this.pending=null;this.gate.locked=false;this.autoTried=false;if(old)this.retire(old,false);this.log('handoff_state_commit',{planId:p.id,to:this.active.track.id,bodySourceOffset:this.active.offset,scheduledContextSec:p.end});this.status='交接完成，正文恢复原速';this.protected();const next=this.gate.deferred;this.gate.deferred=null;if(next){const remaining=this.deferredDeadline-now;if(remaining>0)void this.request(next,remaining);else{this.status='等待上限已到，保留当前播放；请重新选择';this.log('request_expired',{intent:next,deadline:this.deferredDeadline})}}else void this.prewarm()}}
 private tick(){if(this.dead)return;this.sync();if(this.active&&this.ctx.state==='running'&&!this.paused&&!this.pending&&!this.busy){const left=this.active.track.duration-this.position;if(left<20&&!this.autoTried){this.autoTried=true;void this.request({kind:'next'},18)}if(left<=.01){this.stop();this.status='本段试听已播完';this.log('source_end')}}this.update()}
 cancel(){this.sync();if(this.gate.locked){this.status='交接已锁定；可停止播放，普通请求将在完成后处理';this.update();return false}this.starting++;this.gate.reset();this.busy=false;this.cancelScheduled();this.protected();this.log('request_cancelled');this.status='已取消待执行转场';this.update();return true}
 private cancelScheduled(){const p=this.pending;if(!p)return;this.monitor.port.postMessage({kind:'cancel',planId:p.id});this.retire(p.deck,false);if(this.active){this.hold(this.active.gain.gain,.76);this.hold(this.active.wet.gain,0);this.hold(this.active.dry.gain,1)}this.log('plan_cancelled',{planId:p.id});this.pending=null;this.protected()}
 async request(intent:Intent,budget=18){this.sync();if(!this.active||this.paused){this.status='请先播放歌曲';this.update();return}const token=this.gate.replace(intent);this.log('intent',{intent,revision:token,sourcePosition:this.position,budget});if(token===null){this.deferredDeadline=this.ctx.currentTime+budget;this.status='当前交接已锁定，将在完成后处理最新请求';this.update();return}this.cancelScheduled();const source=this.active.track;const requestedAt=this.ctx.currentTime;this.busy=true;this.status='正在选择可用交接窗口…';this.update()
  try{let result=planNext(source,this.tracks,this.position,intent,this.cache.ready,budget);if(!result.best){const preview=planNext(source,this.tracks,this.position,intent,this.cache.ready,budget,false);this.lastSearch=preview;if(!preview.best)throw new Error('等待范围内没有符合目标的窗口。可以改用较长等待或选择其他歌曲。');const b=this.tracks.find(t=>t.id===preview.best!.to)!;this.cache.protected.add(b.native.url);this.cache.protected.add(preview.best.asset.url);await this.cache.load(b.native);if(!this.gate.isCurrent(token))return;await this.cache.load(preview.best.asset);if(!this.gate.isCurrent(token))return;const remaining=budget-(this.ctx.currentTime-requestedAt);result=planNext(source,this.tracks,this.position,intent,this.cache.ready,remaining)}
   if(!this.gate.isCurrent(token)||this.active?.track.id!==source.id)return;this.lastSearch=result;this.log('candidates',{intent,revision:token,candidates:result.candidates.slice(0,20),rejected:result.rejected,elapsedPreparation:this.ctx.currentTime-requestedAt});if(!result.best)throw new Error('素材已准备，但原来的交接窗口已错过。当前歌曲继续播放，请再次选择。');this.schedule(result.best,requestedAt,intent)
  }catch(e){if(this.gate.isCurrent(token)){this.status=(e as Error).message;this.log('request_failed',{message:this.status,intent})}}finally{if(this.gate.isCurrent(token)){this.busy=false;this.protected();this.update()}}}
 private schedule(plan:Plan,requestedAt:number,intent:Intent){const a=this.active!;const b=this.tracks.find(t=>t.id===plan.to)!;const start=a.at+(plan.start-a.offset),end=start+plan.duration;const restore=end-Math.min(plan.duration,120/a.track.bpm);if(start<this.ctx.currentTime+.2)throw new Error('距离进歌点太近，已保留当前播放');const native=this.cache.buffers.get(b.native.url)!,clip=this.cache.buffers.get(plan.asset.url)!;const deck=this.graph(b,end,plan.window.end);this.source(deck,clip,start,0,end);this.source(deck,native,end,plan.window.end,undefined,true)
  a.low.gain.setValueAtTime(-9,start);a.high.gain.setValueAtTime(-1.4,start);a.mid.gain.setValueAtTime(0,start);a.wet.gain.setValueAtTime(0,start);a.wet.gain.linearRampToValueAtTime(1,start+.02);a.dry.gain.setValueAtTime(1,start);a.dry.gain.linearRampToValueAtTime(0,start+.02);a.gain.gain.setValueAtTime(.76,start);a.gain.gain.linearRampToValueAtTime(0,end)
  deck.low.gain.value=-7;deck.high.gain.value=1.2;deck.mid.gain.value=plan.midDuck?-5:0;deck.wet.gain.setValueAtTime(1,start);deck.wet.gain.setValueAtTime(1,restore);deck.wet.gain.linearRampToValueAtTime(0,end);deck.dry.gain.setValueAtTime(0,start);deck.dry.gain.setValueAtTime(0,restore);deck.dry.gain.linearRampToValueAtTime(1,end);deck.gain.gain.setValueAtTime(0,start);deck.gain.gain.linearRampToValueAtTime(.76,end)
  const id=`${this.gate.revision}-${plan.id}`;this.pending={plan,deck,start,end,id,committed:false};this.lastPlan=plan;const events=[{name:'B 开始混入',time:start},{name:'B EQ 开始恢复',time:restore},{name:'A 退出 / B 正文接管',time:end}].map(e=>({planId:id,name:e.name,frame:Math.round(e.time*this.ctx.sampleRate)}));this.monitor.port.postMessage({kind:'arm',events});this.log('plan_scheduled',{planId:id,intent,requestedAt,start,end,restore,plan,events,eqImplementation:'WebAudio Biquad, V3 gains/frequencies; 20ms outgoing EQ enable smoothing; 4ms head/body edge fades',limiter:'5ms lookahead browser protection, not original FFmpeg alimiter',sourceHashes:{a:a.track.native.sha256,b:b.native.sha256,entry:plan.asset.sha256}});this.status='已安排转场';this.protected();this.update()}
 private async prewarm(){const a=this.active;if(!a)return;const revision=this.starting;const intents:Intent[]=[{kind:'next'},{kind:'style',style:a.track.style==='Trap'?'Grime':'Trap'}];for(const intent of intents){if(this.pending||this.busy||this.active!==a||revision!==this.starting)return;const p=planNext(a.track,this.tracks,Math.max(this.position,(a.track.bars[0]||0)+1),intent,this.cache.ready,30,false).best;if(!p)continue;try{const b=this.tracks.find(t=>t.id===p.to)!;await this.cache.load(b.native);if(this.active!==a||this.pending)return;await this.cache.load(p.asset)}catch(e){this.log('prewarm_failed',{message:(e as Error).message})}}this.update()}
 export(){return {schema:'harbeat.v3_live_session.v1',catalog:this.tracks.map(t=>({id:t.id,reportId:t.reportId,native:t.native,style:t.style,styleScore:t.styleScore,warnings:t.warnings})),sampleRate:this.ctx.sampleRate,baseLatency:this.ctx.baseLatency,outputLatency:this.ctx.outputLatency,logs:this.logs,limitations:['Audio observations locate render quanta, not physical source onset/speaker output','Single-song tempo assets were prepared ahead; selection/EQ/fade/mixing run live','Browser DSP is not bit-identical to FFmpeg V3','Local energy is uncalibrated; all structural candidates need listening confirmation']}}
 dispose(){this.dead=true;this.stop();clearInterval(this.timer);this.cache.dispose();void this.ctx.close()}
}
