import json,html,sys
from pathlib import Path
out=Path(sys.argv[1]);plan=json.loads((out/'plan.json').read_text());log=json.loads((out/'execution.json').read_text())
def esc(x):return html.escape(str(x))
def stamp(v):return f'{int(v)//60}:{v%60:06.3f}'
rows=''.join(f'<li><span>{i+1:02d}</span><div><b>{esc(t["title"])}</b><small>原曲首次副歌结束候选 {t["end_sec"]:.3f}s · 变速 {log["tracks"][i]["rate"]:.4f}×</small></div></li>' for i,t in enumerate(plan['tracks']))
clips=''.join(f'<article><div class="eyebrow">TRANSITION {c["number"]:02d} · {c["overlap_bars"]} 小节</div><h3>{esc(c["a"])} <span>→</span> {esc(c["b"])}</h3><p>{stamp(c["entry_sec"])} 开始交接 → {stamp(c["handoff_sec"])} 完成 · B 中频 {c["mid_cut_db"]} dB</p><audio controls preload="none" src="{c["file"]}"></audio><div class="links"><button onclick="seek({max(0,c["entry_sec"]-8)})">在完整串烧中定位</button><a href="{c["file"]}" download>下载片段</a></div></article>' for c in log['clips'])
events=''.join(f'<tr><td>{e["pair"]}</td><td>{esc(e["name"])}</td><td>{stamp(e["planned_sec"])}</td><td>{stamp(e["actual_sec"])}</td><td>{e["delta_ms"]:+.4f} ms</td></tr>' for e in log['events'])
adjustments=''.join(f'<tr><td>{esc(t["title"])}</td><td>{t["preview_estimation"]["first_recorded_bar_sec"]:.3f}s</td><td>{t["preview_estimation"]["first_bar_sec"]:.3f}s</td><td>{max(abs(x["delta_ms"]) for x in t["preview_estimation"]["adjustments"].values()):.0f} ms</td></tr>' for t in plan['tracks'])
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HarBeat · DEMO 1.0 试混</title><style>
*{box-sizing:border-box}body{margin:0;background:#f6f5f1;color:#172421;font:15px/1.65 system-ui,-apple-system,sans-serif}main{max-width:1120px;margin:auto;padding:28px 28px 70px}header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #d9ddd5;padding-bottom:18px}header img{width:36px;height:36px;object-fit:contain;vertical-align:middle;margin-right:12px}.eyebrow{letter-spacing:.16em;font-size:11px;font-weight:700;color:#66756e}h1{font-size:clamp(34px,5vw,58px);line-height:1.2;letter-spacing:-.04em;margin:24px 0 14px}h2{font-size:23px;margin:32px 0 14px}h3{font-size:18px;line-height:1.45;margin:8px 0}h3 span{color:#8da59a}p{color:#586960}a{color:#205d49}button{font:inherit;color:#205d49;border:1px solid #ccd8d0;background:white;padding:6px 12px;border-radius:6px;cursor:pointer}audio{width:100%;margin-top:8px}.hero{background:#fff;border:1px solid #dfe2da;border-radius:16px;padding:28px;margin-top:26px}.badge{display:inline-block;font-size:12px;padding:4px 10px;border-radius:20px;background:#eee6d2;color:#6c5126}.stats{display:flex;gap:30px;margin:20px 0}.stats b{display:block;font-size:26px}.stats small{color:#738278}.links{display:flex;gap:18px;align-items:center;margin-top:12px}.note{border-left:3px solid #bd9856;padding:8px 16px;margin:24px 0;background:#f3ecdd}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}article{background:white;border:1px solid #dfe2da;border-radius:12px;padding:22px}article p{font-size:12px}ol{list-style:none;padding:0}li{display:flex;gap:18px;padding:13px 0;border-bottom:1px solid #dfe2da}li>span{font-size:12px;color:#8a978d;padding-top:4px}li small{display:block;color:#738278;font-size:12px}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{text-align:left;padding:9px;border-bottom:1px solid #dfe2da;white-space:nowrap}details{margin-top:24px}summary{cursor:pointer;font-weight:600}footer{margin-top:40px;font-size:12px;color:#738278}@media(max-width:720px){main{padding:18px}.grid{grid-template-columns:1fr}.hero{padding:20px}.stats{gap:18px}.stats b{font-size:22px}}
</style><main><header><b><img src="logo.png" alt="HarBeat">HarBeat / Listening Lab</b><a href="/analysis-lab">返回分析平台</a></header><div class="hero"><div class="eyebrow">PLAN → RENDER → LISTEN</div><h1>六首歌，一份接歌计划。</h1><span class="badge">DEMO 1.0 · 待试听确认</span><p>首遍副歌结束交接 · 前奏对齐 · 常规音量与中频衰减</p><div class="stats"><div><b>DURATION</b><small>完整串烧</small></div><div><b>100 BPM</b><small>全程统一速度</small></div><div><b>5 次</b><small>独立转场片段</small></div></div><audio id="full" controls preload="metadata" src="HarBeat-DEMO-1.0-preview.mp3"></audio><div class="links"><a href="HarBeat-DEMO-1.0-preview.mp3" download>下载完整 MP3</a><a href="decision-log.html">详细混音日志</a><a href="plan.json" download>查看接歌计划</a><a href="execution.json" download>查看执行记录</a></div></div><div class="note"><b>这是一版试混，不是人工验收结果。</b><br>原有拍网格缺少前奏首拍；本版根据已有小节推算规则网格，并把段落边界吸附到候选首拍。调整量完整保留，原分析和人工确认状态没有改写。B 从文件头静音预播放，进入计划区间才逐渐放出声音。请重点听段落选得是否正确、鼓点是否齐、人声是否冲突。</div><h2>播放顺序</h2><ol>TRACKS</ol><h2>逐一试听五次转场</h2><p>片段包含交接前 8 秒、完整交接区间与交接后 8 秒。</p><div class="grid">CLIPS</div><details><summary>计划时间与离线执行时间</summary><p>执行时间来自渲染器实际应用音量／EQ 数组的采样位置；不代表浏览器按时播放，也不证明音乐拍点识别准确。</p><div class="table"><table><thead><tr><th>转场</th><th>动作</th><th>计划</th><th>执行</th><th>偏差</th></tr></thead><tbody>EVENTS</tbody></table></div></details><details><summary>查看本版拍网格推算与边界调整</summary><div class="table"><table><thead><tr><th>歌曲</th><th>原记录首小节</th><th>本版推算首小节</th><th>最大边界调整</th></tr></thead><tbody>ADJUSTMENTS</tbody></table></div><p>完整原始边界、候选边界、每项偏差及原阻塞原因见 plan.json。所有候选仍未获人工确认。</p></details><footer>LEVELS<br>算法：完整原曲恒速保调变速、线性音量交接、250–4000 Hz 中频衰减；触发时最后半小节从 -9 dB 恢复到 0 dB。没有使用旧版本约 125 秒选点。</footer></main><script>function seek(t){const a=document.getElementById('full');a.currentTime=t;a.scrollIntoView({behavior:'smooth',block:'center'});a.play().catch(()=>{})}document.querySelectorAll('audio').forEach(a=>a.addEventListener('play',()=>document.querySelectorAll('audio').forEach(b=>{if(b!==a)b.pause()})))</script></html>'''
for key,value in [('DURATION',f'{int(log["duration_sec"])//60}:{int(log["duration_sec"])%60:02d}'),('TRACKS',rows),('CLIPS',clips),('EVENTS',events),('ADJUSTMENTS',adjustments),('LEVELS',f'WAV 实测综合响度 {log["levels_after"]["input_i"]} LUFS · 真峰值 {log["levels_after"]["input_tp"]} dBTP · MP3 真峰值 {log["mp3_levels"]["input_tp"]} dBTP')]:page=page.replace(key,value)
(out/'index.html').write_text(page)
