import {memo,useMemo} from 'react'
import {mergeSections} from '../guarded/planner'
import type {Track,Plan} from '../realtime/planner'
import {buildScene,sectionName,sourceAtRenderTime,type Span} from './scene'
const sec=(v:number)=>`${Math.floor(v/60)}:${(v%60).toFixed(1).padStart(4,'0')}`
export default memo(function MixStoryboard({a,b,plan,position,playTime,onInspect}:{a:Track;b:Track;plan:Plan;position:number;playTime?:number;onInspect?:(id:string,time:number)=>void}){
 const s=useMemo(()=>buildScene(a,b,plan,position),[a,b,plan,position]),W=740,L=100,R=720,x=(t:number)=>L+(t-s.min)/(s.max-s.min)*(R-L)
 const row=(spans:Span[],y:number,h:number,kind:string)=>spans.map((p,i)=><g key={i}><rect x={x(p.start)} y={y} width={Math.max(.7,x(p.end)-x(p.start))} height={h} rx={kind==='section'?4:1} className={kind}/>{kind==='section'&&x(p.end)-x(p.start)>45&&<text x={x(p.start)+6} y={y+21}>{sectionName(p.label||'unknown')}</text>}<title>{kind==='vocal'?'模型人声活动':sectionName(p.label||'unknown')} · 转场相对 {p.start.toFixed(2)}–{p.end.toFixed(2)} 秒</title></g>)
 const acoustic=(plan as any).protection
 const ticks=Array.from({length:6},(_,i)=>s.min+(s.max-s.min)*i/5)
 return <article className="story"><div className="story-top"><span className={'pill '+(s.protected?'green':'blue')}>{s.protected?'V3.1 候选 · 保护版':'V3 普通接歌'}</span><span>交接共 {plan.duration.toFixed(1)} 秒</span></div>
 <div className="story-metrics"><div><strong>{s.waitSec.toFixed(1)}s</strong><span>从请求到完成交接</span></div><div><strong>{s.overlapSec===null?'未知':s.overlapSec.toFixed(2)+'s'}</strong><span>模型人声区间同时活动</span></div><div><strong>{s.sectionTailSec===null?'未知':s.sectionTailSec>=0?'段尾之后':'段尾之前'}</strong><span>{s.sectionTailSec===null?'无段落依据':`${Math.abs(s.sectionTailSec).toFixed(2)} 秒退出 A`}</span></div></div>
 <p className="story-summary">{s.protected?'先等 A 到段尾附近的人声间隙，让 B 的无人声片段铺入。':'按规则评分选点；人声冲突会扣分，但不禁止提前结束乐段。'}</p>
 <p className="quiet">原曲选段：深色边框是使用的范围，竖线是 A 退出 / B 接管位置。框外段落仍保留，方便判断有没有提前结束。</p><div className="timeline-scroll"><svg viewBox={`0 0 ${W} 120`} role="img" aria-label="A 和 B 原曲完整段落与所选片段">{[{t:a,start:plan.start,end:plan.end,y:12,name:'A 原曲'},{t:b,start:plan.window.start,end:plan.window.end,y:68,name:'B 原曲'}].map(({t,start,end,y,name})=>{const sx=(v:number)=>L+Math.min(t.duration,Math.max(0,v))/t.duration*(R-L);return <g key={name}><text x="10" y={y+20}>{name}</text>{mergeSections(t.sections).filter(z=>z.start<t.duration).map((z,i)=><g key={i}><rect x={sx(z.start)} y={y} width={Math.max(.5,sx(z.end)-sx(z.start))} height="28" fill={i%2?'#e7eeda':'#d3e1c3'}/>{sx(z.end)-sx(z.start)>45&&<text x={sx(z.start)+4} y={y+19} fontSize="11">{sectionName(z.label)}</text>}<title>{sectionName(z.label)} · {sec(z.start)}–{sec(z.end)}</title></g>)}{(t.vocals||[]).filter(([lo])=>lo<t.duration).map(([lo,hi],i)=><rect key={i} x={sx(lo)} y={y+31} width={Math.max(.5,sx(hi)-sx(lo))} height="5" className="vocal"/>)}<rect x={sx(start)} y={y-2} width={sx(end)-sx(start)} height="31" fill="none" stroke="#235439" strokeWidth="2"/><line x1={sx(end)} x2={sx(end)} y1={y-5} y2={y+39} stroke="#234b32" strokeWidth="2"/><text x={L} y={y+49} fontSize="11">0:00</text><text x={R} y={y+49} textAnchor="end" fontSize="11">{sec(t.duration)}</text></g>})}</svg></div>
 <p className="quiet">转场放大：下面只画实际播放的部分。</p><div className="timeline-scroll"><svg viewBox={`0 0 ${W} 326`} role="img" aria-label={`${a.title} 到 ${b.title} 的段落、人声与交接时间轴`}>
 <rect x={x(0)} y="38" width={x(plan.duration)-x(0)} height="202" className="mix-zone"/>
 {ticks.map((t,i)=><g key={i}><line x1={x(t)} x2={x(t)} y1="39" y2="286" className="grid-line"/><text x={x(t)} y="310" textAnchor="middle">{t.toFixed(1)}s</text></g>)}
 <text x="10" y="79" className="axis-title">A 当前曲</text><text x="10" y="108">人声活动</text>{row(s.aSections,55,34,'section')}{row(s.aVocals,99,12,'vocal')}
 <text x="10" y="171" className="axis-title">B 下一首</text><text x="10" y="200">人声活动</text>{row(s.bSections,147,34,'section')}{row(s.bVocals,191,12,'vocal')}
 {s.overlaps.map((p,i)=><rect key={i} x={x(p.start)} width={x(p.end)-x(p.start)} y="118" height="12" className="collision"><title>此范围内 A 和 B 的模型人声区间重叠</title></rect>)}
 <text x="10" y="255">播放增益</text><path d={`M${x(s.min)},235 L${x(0)},235 L${x(plan.duration)},276`} className="gain-a"/><path d={`M${x(0)},276 L${x(plan.duration)},235 L${x(s.max)},235`} className="gain-b"/>
 <line x1={x(0)} x2={x(0)} y1="31" y2="285" className="cue-line"/><text x={x(0)} y="21" textAnchor="middle">① B 铺入</text>
 <line x1={x(plan.duration)} x2={x(plan.duration)} y1="31" y2="285" className="cue-line"/><text x={x(plan.duration)+6} y="21">② A 退出，B 接管</text>
 <line x1={x(plan.restore-plan.start)} x2={x(plan.restore-plan.start)} y1="210" y2="281" className="restore-line"/>
 {playTime!==undefined&&playTime>=s.min&&playTime<=s.max&&<line x1={x(playTime)} x2={x(playTime)} y1="32" y2="287" className="playhead"/>}
 </svg></div><div className="legend"><span><i className="section"/>模型段落</span><span><i className="vocal"/>模型人声活动</span><span><i className="collision"/>同时活动</span><span><i className="mix-zone"/>两曲衔接区</span></div>
 <p className="quiet">横轴以 B 开始铺入为 0 秒。B 进入段已按 {plan.rate.toFixed(3)}× 变速；接管后恢复原速。人声活动不等于歌词句子，重叠秒数也不是听感评分。</p>
 <div className="source-cues"><div><b>A · {a.title}</b><p>原曲 {sec(plan.start)} 开始渐弱 → {sec(plan.end)} 退出</p>{s.sectionEnd!==null&&<p>混出所在段的模型段尾 {sec(s.sectionEnd)} · {sectionName(s.exitSection)}</p>}{acoustic?.automaticExit&&<p>退出所用人声间隙：{sec(acoustic.automaticExit.quietStart)}–{sec(acoustic.automaticExit.quietEnd)}；分离人声最高 {acoustic.automaticExit.maxRmsDbfs.toFixed(1)} dBFS，阈值 {acoustic.automaticExit.thresholdDbfs} dBFS。</p>}<button onClick={()=>onInspect?.(a.id,Math.max(0,plan.end-4))}>听 A 退出点前后</button></div><div><b>B · {b.title}</b><p>原曲 {sec(plan.window.start)} → {sec(plan.window.end)} 铺入（{plan.window.bars} 小节）</p><p>{sec(plan.window.end)} 开始正文 · {sectionName(plan.window.role)}</p>{acoustic?.automaticEntry&&<p>整个入口通过 VAD 排除与低人声能量检查；最高 {acoustic.automaticEntry.maxRmsDbfs.toFixed(1)} dBFS。这是活动强度，不是“人声概率”。</p>}<button onClick={()=>onInspect?.(b.id,Math.max(0,plan.window.start-2))}>听 B 原曲进入片段</button></div></div>
 {playTime!==undefined&&<p className="quiet">播放位置：A {sourceAtRenderTime(plan,'a',playTime)===null?'已退出':sec(sourceAtRenderTime(plan,'a',playTime)!)} · B {sourceAtRenderTime(plan,'b',playTime)===null?'尚未进入':sec(sourceAtRenderTime(plan,'b',playTime)!)}</p>}
 <details><summary>为什么选这里，以及素材来自哪里</summary><ol>{s.why.map(x=><li key={x}>{x}</li>)}</ol><p>{s.certainty}</p><p>A 报告 <a href={a.preprocessing?.reportSnapshotUrl} target="_blank" rel="noreferrer">{a.reportId?.slice(0,12)}…</a> · B 报告 <a href={b.preprocessing?.reportSnapshotUrl} target="_blank" rel="noreferrer">{b.reportId?.slice(0,12)}…</a></p><p>人声来自原有 VAD 与分离人声 RMS；段落来自 {String(a.provenance?.sectionSource||'现有模型')}。未新增歌词识别，也未加入能量、风格奖励。</p></details>
 </article>
})
