import {useEffect,useMemo,useRef,useState} from 'react'
import {planNext,type Plan,type Track} from '../realtime/planner'
import {guardPlan,type GuardCatalog} from '../guarded/planner'
import {LiveTransport} from '../realtime/transport'
import DecisionHistory from '../realtime/DecisionHistory'
import {buildDecisionTrace} from '../realtime/trace'
import DecisionTracePanel from '../realtime/DecisionTracePanel'
import MixStoryboard from './MixStoryboard'
import logo from '../analysis/assets/harbeat-logo.png'
import './v31.css'
import {AudioBufferPool} from '../realtime/cache'
import {readRatings,writeRating,BACKUP_KEY} from './ratings'
const base=new URL('.',location.href)
type Case={id:string;a:string;b:string;position:number;v3:boolean;protected:boolean;reason?:string}
type Pack={v3:GuardCatalog;protected:GuardCatalog;audit:any;cases:Case[];coverage:any}
function download(value:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const choose=(c:GuardCatalog,a:Track,b:string,pos:number,mode:'v3'|'protected')=>mode==='v3'?planNext(a,c.tracks,pos,{kind:'next',targetId:b},new Set(),18,false):guardPlan(c,{},a,c.tracks,pos,{kind:'next',targetId:b},new Set(),Math.max(0,a.duration-pos),false)
export default function V31Lab(){
 const [pack,setPack]=useState<Pack|null>(null),[error,setError]=useState(''),[tab,setTab]=useState<'compare'|'live'>('compare'),[aId,setA]=useState(''),[bId,setB]=useState(''),[position,setPosition]=useState(0),[skip,setSkip]=useState(true),[warm,setWarm]=useState(''),[working,setWorking]=useState(false),[initializing,setInitializing]=useState(false),[,refresh]=useState(0),[ratings,setRatings]=useState<Record<string,any>>(()=>{try{return readRatings(localStorage)}catch{return {}}})
 const audioPool=useRef(new AudioBufferPool()),dirtyRatings=useRef<Record<string,any>>({})
 const actionRevision=useRef(0),initPromise=useRef<Promise<void>|null>(null),playRole=useRef<'idle'|'native'|'mix'|'inspection'>('idle')
 const player=useRef<LiveTransport|null>(null),playerMode=useRef(''),warmNonce=useRef(0),inspection=useRef<ReturnType<typeof setTimeout>|null>(null)
 useEffect(()=>{let alive=true;Promise.all(['v3-catalog.json','auto-catalog.json','corpus-audit.json','cases.json'].map(async f=>{const r=await fetch(new URL(f,base));if(!r.ok)throw Error(`${f} 加载失败 (${r.status})`);return r.json()})).then(([v3,protectedCatalog,audit,cases])=>{if(!alive)return;setPack({v3,protected:protectedCatalog,audit,cases:cases.cases,coverage:cases.coverage});const first=cases.cases.find((x:Case)=>x.v3&&x.protected)||cases.cases[0];setA(first.a);setB(first.b);setPosition(first.position)}).catch(e=>setError(e.message));return()=>{alive=false;warmNonce.current++;if(inspection.current)clearTimeout(inspection.current);player.current?.dispose()}},[])
 const searches=useMemo(()=>{if(!pack)return null;const a=pack.v3.tracks.find(t=>t.id===aId),g=pack.protected.tracks.find(t=>t.id===aId);if(!a||!g)return null;return {v3:choose(pack.v3,a,bId,position,'v3'),protected:choose(pack.protected,g,bId,position,'protected')}},[pack,aId,bId,position])
 const activeId=player.current?.current?.id
 useEffect(()=>{if(tab==='live'&&activeId&&aId!==activeId){setA(activeId);setPosition(0)}if(tab==='live'&&pack&&activeId&&bId===activeId){setB(pack.protected.tracks.find(t=>t.id!==activeId)!.id);setWarm('')}},[activeId,pack,bId,tab,aId])
 if(!pack||!searches)return <main className="v31"><h1>HarBeat · V3.1 试听实验室</h1><p role="status">{error||'正在加载曲库、预处理依据和对照样本…'}</p></main>
 const p=player.current,tracks=pack.protected.tracks,a=tracks.find(t=>t.id===aId)!,b=tracks.find(t=>t.id===bId)!,locked=!!p?.busy||working||initializing,current=p?.current,caseId=`${aId}|${bId}|${position}`,selectedRating=ratings[caseId]||{}
 const execution=p?.logs.filter(x=>x.kind==='plan_scheduled').at(-1),latestRequest=p?.logs.filter(x=>x.kind==='request_received').at(-1),events=execution?.events||[]
 const last=playRole.current==='mix'?(p?.pending?.plan||(execution?.requestId===latestRequest?.requestId?p?.lastPlan:null)):null
 async function ensure(mode:'v3'|'protected'){
  const revision=actionRevision.current
  if(player.current&&playerMode.current===mode){const existing=player.current;await initPromise.current;if(revision!==actionRevision.current||player.current!==existing)throw new DOMException('操作已取消','AbortError');return existing}
  player.current?.dispose();const c=pack![mode];const next:typeof planNext=(a,ts,pos,intent,ready,budget=18,requireReady=true)=>mode==='v3'?planNext(a,ts,pos,intent,ready,budget,requireReady):guardPlan(c,{},a,ts,pos,intent,ready,budget,requireReady)
  const t=new LiveTransport(c.tracks,()=>refresh(n=>n+1),base,{audioPool:audioPool.current,planner:next,autoNext:false,prewarm:false,policyVersion:mode==='protected'?'protected-v31-candidate-v1':undefined,noPlanMessage:'没有合格的后续窗口，当前曲继续播放。下方保留未通过原因；不会为了缩短等待而强制接歌。'});player.current=t;playerMode.current=mode
  setInitializing(true);initPromise.current=t.initialize()
  try{await initPromise.current;t.log('source_catalog',{version:'v31-candidate-20260923',mode,selectionOrDSPModified:false,previewLimitSec:150,humanReviewsGenerated:false})}catch(e){t.dispose();if(player.current===t)player.current=null;throw e}finally{if(!player.current||player.current===t)setInitializing(false)}
  if(revision!==actionRevision.current||player.current!==t)throw new DOMException('操作已取消','AbortError');return t
 }
 async function run(fn:()=>Promise<void>){const revision=++actionRevision.current;warmNonce.current++;setWorking(false);if(inspection.current)clearTimeout(inspection.current);setError('');try{await fn()}catch(e){if(revision===actionRevision.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}}
 function stop(){actionRevision.current++;playRole.current='idle';warmNonce.current++;setWorking(false);setWarm('');if(inspection.current)clearTimeout(inspection.current);player.current?.stop()}
 function changeCase(x:Case){stop();setA(x.a);setB(x.b);setPosition(x.position);setWarm('')}
 async function audition(mode:'v3'|'protected'){
  const plan=searches![mode].best;if(!plan)return;const t=await ensure(mode);const comparisonId=caseId;t.log('comparison_analysis',{comparisonId,triggerSourceSec:position,baseline:searches!.v3,variant:searches!.protected,sameTrigger:true,energyStyleEnabled:false});playRole.current='mix';await t.playComparison(plan,position,{experimentId:'v31-candidate',comparisonId,arm:mode==='v3'?'baseline':'variant',midDb:-5,skipWaiting:skip,horizonSec:mode==='v3'?18:a.duration-position})
 }
 async function inspect(mode:'v3'|'protected',id:string,time:number){const revision=actionRevision.current,t=await ensure(mode);playRole.current='inspection';t.log('source_inspection',{trackId:id,sourceStart:time,durationSec:8,notMix:true});await t.start(id,time);if(revision!==actionRevision.current||player.current!==t)return;inspection.current=setTimeout(()=>{if(player.current===t)t.stop()},8000)}
 async function preload(){
  const token=++warmNonce.current;setWorking(true);setWarm('准备中…');try{const t=await ensure('protected');if(token!==warmNonce.current)return;const from=t.current||a,pos=t.current?t.position:position,r=choose(pack!.protected,from,bId,pos,'protected');if(!r.best){setWarm('没有合格窗口，详见预览或本次决策日志。');t.log('preload_rejected',{from:from.id,to:bId,position:pos,exclusions:r.exclusions});return}
   const target=tracks.find(x=>x.id===bId)!;t.cache.protected=new Set([from.native.url,target.native.url,r.best.asset.url]);t.log('manual_preload',{from:from.id,to:bId,planId:r.best.id,sourcePosition:pos,doesNotSchedule:true});for(const asset of [from.native,target.native,r.best.asset]){await t.cache.load(asset);if(token!==warmNonce.current)return}setWarm('素材已准备。点击接歌时会按当时播放位置重新选点。')
  }finally{if(token===warmNonce.current)setWorking(false);refresh(n=>n+1)}
 }
 function rate(value:string,notes=selectedRating.notes||''){const entry={preference:value,notes,from:aId,to:bId,position,updatedAt:new Date().toISOString(),version:'v31-candidate-20260923'};dirtyRatings.current[caseId]=entry;setRatings(current=>({...current,[caseId]:entry}));try{setRatings(writeRating(localStorage,ratings,caseId,entry,dirtyRatings.current));dirtyRatings.current={}}catch{setError('本机反馈保存失败，新的反馈暂存在当前页面。请立即导出试听反馈；原有记录未重置。')}}
 return <main className="v31"><header><img src={logo} alt="HarBeat"/><div><div className="eyebrow">LISTEN · COMPARE · TRACE</div><h1>听清交接，也看清原因。</h1><p>V3.1 保护版候选 · {tracks.length} 首 Hip-Hop／Trap／Grime 曲库试听</p></div><a className="old-version" href="../v3-live-baseline-20260922/index.html">返回保留的 V3 ↗</a></header>
 <nav><button aria-pressed={tab==='compare'} onClick={()=>{stop();player.current?.dispose();player.current=null;setTab('compare')}}>① 多曲对照试听</button><button aria-pressed={tab==='live'} onClick={()=>{stop();player.current?.dispose();player.current=null;setTab('live')}}>② 播放中实时接歌</button><a href="/analysis-lab?tab=mix-debug">分析平台 / 历史日志 ↗</a></nav>
 <aside className="scope">这轮只验证段落与人声保护。沿用 V3 的 EQ 和渐变，不加入能量、风格奖励。每首试听素材最多前 150 秒；风格、段落与拍点仍是模型候选。试听反馈通过后，再决定是否正式采用 V3.1。</aside>
 <p className="coverage-summary">本轮 {tracks.length} 首，预设 {pack.cases.length} 组：{pack.coverage.pairedCaseCount} 组可试听两版，其余保留无窗口原因。可自选任意曲对；约束通过不代表听感一定更好。</p><section className="controls"><div className="section-head"><h2>{tab==='compare'?'同一请求，两种处理':'边播放，边选择下一首'}</h2><span>{Object.keys(ratings).length} 组已记录反馈</span></div>
 {tab==='compare'&&<label className="wide">预设试听样本（含找不到窗口的样本）<select value={pack.cases.some(x=>`${x.a}|${x.b}|${x.position}`===caseId)?caseId:''} disabled={locked} onChange={e=>changeCase(pack.cases.find(x=>`${x.a}|${x.b}|${x.position}`===e.target.value)!)}><option value="" disabled>自选曲对</option>{pack.cases.map((c,i)=><option key={c.id} value={`${c.a}|${c.b}|${c.position}`}>{i+1}. {tracks.find(t=>t.id===c.a)?.title} → {tracks.find(t=>t.id===c.b)?.title} · {c.position.toFixed(1)}s · {c.v3&&c.protected?'两版可比':c.protected?'仅保护版有窗口':c.v3?'保护版暂不放行':'两版均无窗口'}</option>)}</select></label>}
 <div className="fields"><label>A 当前曲<select value={aId} disabled={locked||!!p?.active} onChange={e=>{stop();setA(e.target.value);if(e.target.value===bId)setB(tracks.find(t=>t.id!==e.target.value)!.id);setPosition(0);setWarm('')}}>{tracks.map(t=><option key={t.id} value={t.id}>{t.title} · {t.bpm} BPM</option>)}</select></label><label>B 下一首<select value={bId} disabled={locked} onChange={e=>{warmNonce.current++;setB(e.target.value);setWarm('')}}>{tracks.filter(t=>t.id!==(tab==='live'?(current?.id||aId):aId)).map(t=><option key={t.id} value={t.id}>{t.title} · {t.bpm} BPM</option>)}</select></label><label>预设请求位置（A 原曲秒）<input aria-label="请求位置" type="number" min="0" max={a.duration-1} step="1" value={position} disabled={locked||!!p?.active} onChange={e=>setPosition(Math.max(0,Math.min(a.duration-1,Number(e.target.value)||0)))}/></label></div>
 {tab==='compare'?<><label className="check"><input type="checkbox" checked={skip} onChange={e=>setSkip(e.target.checked)}/>只听转场前 4 秒至交接后 8 秒（保留原请求位置与选点，跳过等待）</label><p className="quiet">两版从同一 A 原曲位置提出请求，因各自规则不同，可能等到不同段落。图中“等待秒数”始终显示完整等待。</p></>:<><div className="actions"><button disabled={locked} onClick={()=>run(async()=>{const t=await ensure('protected');playRole.current='native';await t.start(aId,position)})}>播放 A</button><button disabled={locked||!!p?.pending} onClick={()=>run(preload)}>准备下一首素材</button><button className="primary" disabled={!p?.active||locked||playerMode.current!=='protected'} onClick={()=>run(async()=>{const from=p!.current!;setPosition(p!.position);playRole.current='mix';await p!.request({kind:'next',targetId:bId},Math.max(0,from.duration-p!.position))})}>按当前位置请求接歌</button><button disabled={!p?.active} onClick={()=>run(async()=>{await p!.togglePause()})}>{p?.paused?'继续':'暂停'}</button><button disabled={!p?.pending&&!p?.busy} onClick={()=>{if(p?.cancel())playRole.current='native'}}>取消待执行接歌</button></div><p>{warm||'建议先准备下一首，再请求接歌。准备不会自动启动混音；下载期间 A 可以继续播放。'}</p>{current&&<label>播放进度 · {current.title}<input aria-label="播放进度" type="range" min="0" max={current.duration-1} step=".1" value={Math.min(current.duration-1,p!.position)} disabled={locked||!!p?.pending} onChange={e=>run(()=>{playRole.current='native';return p!.seek(Number(e.target.value))})}/></label>}</>}
 <p className="quiet">音频首次使用需要下载；两版共用已就绪素材，刷新后也可复用浏览器缓存。缓存只存音频，不会清除试听反馈。</p><div className="player-bar"><span role="status">{p?.status||'等待试听'}{current?` · ${current.title} ${p!.position.toFixed(1)}s`:''}</span><button onClick={stop}>停止</button><button disabled={!p} onClick={()=>download(p!.export(),'HarBeat-V31-session.json')}>导出完整日志</button></div>{error&&<p role="alert" className="error">{error}</p>}</section>
 {tab==='compare'?<div className="comparison">{(['v3','protected'] as const).map(mode=>{const c=pack[mode],from=c.tracks.find(t=>t.id===aId)!,to=c.tracks.find(t=>t.id===bId)!,r=searches[mode],q=r.best;return <section key={mode}><div className="section-head"><h2>{mode==='v3'?'V3 · 普通接歌':'V3.1 候选 · 保护接歌'}</h2><button className="primary" disabled={!q||locked} onClick={()=>run(()=>audition(mode))}>试听{mode==='v3'?' V3':'保护版'}</button></div>{q?<MixStoryboard a={from} b={to} plan={q} position={position} playTime={p?.active&&playerMode.current===mode&&last?.id===q.id?(p.current?.id===q.from?p.position-q.start:q.duration+p.position-q.window.end):undefined} onInspect={(id,t)=>run(()=>inspect(mode,id,t))}/>:<div className="empty"><h3>当前没有可执行窗口</h3><p>实时请求时会继续播放 A，不强制接歌。这也是本次测试结果。</p><ul>{[...new Set(r.exclusions.map(x=>x.reason))].slice(0,6).map(x=><li key={x}>{x}</li>)}</ul></div>}<details><summary>查看全部候选和排除依据（{r.candidates.length} 个可执行候选）</summary><pre>{JSON.stringify({candidates:r.candidates.map(x=>({id:x.id,start:x.start,end:x.end,window:x.window.id,score:x.score,reason:x.reason})),exclusions:r.exclusions},null,2)}</pre></details></section>})}</div>:<section><h2>{last?'本次实际选中的交接':'试听前：这个请求位置的保护版计划'}</h2>{(()=>{const q=last||searches.protected.best;if(!q)return <p>当前没有合格计划。可以先播放 A；每次请求都会重新检查并记录原因。</p>;const from=tracks.find(t=>t.id===q.from)!,to=tracks.find(t=>t.id===q.to)!;return <MixStoryboard a={from} b={to} plan={q} position={last?(p!.logs.find(e=>e.kind==='request_received'&&e.requestId===execution?.requestId)?.sourcePosition??position):position} playTime={last&&current?(current.id===q.from?p!.position-q.start:current.id===q.to?q.duration+p!.position-q.window.end:undefined):undefined} onInspect={(id,t)=>run(()=>inspect('protected',id,t))}/>})()}{p?.lastSearch&&<details><summary>本次规划为什么放行或拒绝</summary><pre>{JSON.stringify(p.lastSearch,null,2)}</pre></details>}</section>}
 <section><h2>实际有没有按计划执行</h2>{execution?<><div className="table-scroll"><table><thead><tr><th>事件</th><th>计划音频时钟</th><th>音频线程观察</th><th>偏差</th></tr></thead><tbody>{events.map((e:any)=>{const observed=p?.logs.find(x=>x.kind==='audio_observation'&&x.planId===e.planId&&x.name===e.name);return <tr key={e.name}><td>{e.name}</td><td>{(e.frame/44100).toFixed(3)}s</td><td>{observed?observed.observedContextSec.toFixed(3)+'s':'等待 / 未观察到'}</td><td>{observed?observed.observationDeltaMs.toFixed(2)+'ms':'—'}</td></tr>})}</tbody></table></div><p className="quiet">音频线程观察证明浏览器调度情况，不等同于扬声器、声卡或蓝牙输出实测。</p></>:<p className="quiet">开始一次转场后，这里显示计划与执行的对照。</p>}</section>
 {tab==='compare'&&<section><h2>这组你更喜欢哪一版？</h2><div className="actions">{['V3 更好','保护版更好','差不多','无法比较'].map(x=><button key={x} aria-pressed={selectedRating.preference===x} onClick={()=>rate(x)}>{x}</button>)}</div><label>听到的问题或喜欢的地方<textarea value={selectedRating.notes||''} placeholder="例如：A 人声尾音自然结束，但 B 接管后节奏有跳变。" onChange={e=>rate(selectedRating.preference||'未选择',e.target.value)}/></label><button onClick={()=>download({version:'v31-candidate-20260923',ratings},'HarBeat-V31-listening-feedback.json')}>导出试听反馈</button><button onClick={()=>{const raw=localStorage.getItem(BACKUP_KEY);if(raw)download({originalRaw:raw},'HarBeat-V31-feedback-backup.json')}}>导出更新前备份</button><p className="quiet">原有反馈沿用并自动保留一份更新前备份。反馈保存在此浏览器。此页面是可见版本对照，尚不是盲听实验。</p></section>}
 <section><details><summary>曲库覆盖与局限 · {tracks.length} 首 / 原 6 首 + 新 14 首</summary><p>按照 BPM、人声密度与模型风格差异选曲，未用接歌成功与否筛选。慢速和快速歌曲不一定能在现有限速范围内互接；找不到窗口会保留原因。</p><div className="table-scroll"><table><thead><tr><th>歌曲</th><th>BPM</th><th>风格候选</th><th>人声覆盖</th><th>保护入口</th><th>候选退出点</th></tr></thead><tbody>{tracks.map(t=>{const r=pack.audit.rows.find((r:any)=>r.track_id===t.id);return <tr key={t.id}><td>{t.title}</td><td>{t.bpm}{t.warnings?.some(x=>x.includes('BPM'))?' · 待确认':''}</td><td>{t.style}</td><td>{r?.vocalCoverage!=null?(r.vocalCoverage*100).toFixed(0)+'%':'未知'}</td><td>{t.windows.length}</td><td>{pack.protected.evidence[t.id]?.exits.length||0}</td></tr>})}</tbody></table></div><pre>{JSON.stringify(pack.coverage,null,2)}</pre><a href="corpus-audit.json" target="_blank">完整选曲与排除记录 ↗</a></details></section>
 {execution&&<section><details><summary>技术依据：原始行号、数值、来源指纹和 EQ 自动化</summary><DecisionTracePanel trace={execution.trace||buildDecisionTrace(tracks.find(t=>t.id===execution.plan.from)!,tracks.find(t=>t.id===execution.plan.to)!,execution.plan)}/></details></section>}{p&&<section><details><summary>全部触发记录（包含取消、未放行和失败）</summary><DecisionHistory logs={p.logs} tracks={p.tracks} eventCount={p.logs.length}/></details></section>}<footer>HarBeat · V3.1 Candidate / 2026.09.23 · <a href="../v3-decision-evidence-20260923/index.html">上一版原始证据页 ↗</a></footer></main>
}
